- name: Create Crowdsec folders
  ansible.builtin.file:
    name: '/opt/shift-mon/{{ item }}'
    state: directory
    mode: '770'
  become: true
  with_items:
    - crowdsec
    - crowdsec-config
    - crowdsec-db
    - crowdsec-log

- name: Copy Crowdsec config
  ansible.builtin.copy:
    src: config.yaml
    dest: config.yaml
  become: true

- name: Copy acquis.yaml
  ansible.builtin.template:
    src: acquis.yaml
    dest: /opt/shift-mon/crowdsec-config/acquis.yaml
  become: true
