- name: Install Certbot and Nginx on Debian based systems
  apt:
    name: "{{ packages }}"
    state: present
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: Add EPEL Release on Redhat Based Systems
  dnf:
    name: epel-release
    state: present
  become: true
  when: ansible_facts['os_family'] in ["RedHat","Alma Linux"]

- name: Install Certbot and Nginx on Redhat based systems
  dnf:
    name: "{{ packages }}"
    state: present
  become: true
  when: ansible_facts['os_family'] == "RedHat"

- name: remove default configs from nginx on Debian Based systems
  file: 
    name: "/etc/nginx/sites-enabled/default"
    state: absent
  become: true
  when: ansible_facts['os_family'] == "Debian"


- name: paste in nginx configs on Debian based systems
  template:
    src: "{{ item }}.j2"
    dest: /etc/nginx/sites-available/{{ item }}.conf
  become: true
  with_items: "{{ services }}"
  when: ansible_facts['os_family'] == "Debian"

- name: Change base config for Nginx on Redhat based systems
  copy: 
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  become: true
  when: ansible_facts['os_family'] in ["RedHat","Alma Linux"]

- name: paste in nginx configs on RedHat based systems
  template:
    src: "{{ item }}.j2"
    dest: /etc/nginx/conf.d/{{ item }}.conf
  become: true
  with_items: "{{ services }}"
  when: ansible_facts['os_family'] in ["RedHat","Alma Linux"]

- name: enable nginx configs on Debian Based Systems
  file:
    src: /etc/nginx/sites-available/{{ item}}.conf
    dest: /etc/nginx/sites-enabled/{{ item }}.conf
    state: link
  become: true
  with_items: "{{ services }}"
  when: ansible_facts['os_family'] == "Debian"


- name: get a certificate for influxdb 
  shell: certbot certonly --standalone --pre-hook "sudo systemctl stop nginx" --email {{ certbot_email }} --agree-tos --renew-by-default -d {{ influxdb_fqdn }}
  become: true
  when: nginx
  
- name: Allow httpd to can network connect
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes

- name: Allow nis to enabled
  seboolean:
    name: nis_enabled
    state: yes
    persistent: yes

- name: start and enable nginx
  systemd:
    name: nginx
    state: restarted
    enabled: true
  become: true
