- name: Install packages nginx
  apt:
    name: "{{ packages }}"
    state: present
  become: true

- name: remove default configs from nginx
  file: 
    name: "/etc/nginx/sites-enabled/default"
    state: absent
  become: true


- name: paste in nginx configs
  template:
    src: "{{ item }}.j2"
    dest: /etc/nginx/sites-available/{{ item }}.conf
  become: true
  with_items: "{{ services }}"

- name: enable nginx configs
  file:
    src: /etc/nginx/sites-available/{{ item}}.conf
    dest: /etc/nginx/sites-enabled/{{ item }}.conf
    state: link
  become: true
  with_items: "{{ services }}"

- name: get a certificate for influxdb 
  shell: certbot certonly --standalone --pre-hook "sudo systemctl stop nginx" --email {{ from_email }} --agree-tos --renew-by-default -d {{ influxdb_fqdn }}  become: true
  when: influxdb

- name: get a certificate for grafana
  shell: certbot certonly --standalone --pre-hook "sudo systemctl stop nginx" --email {{ from_email }} --agree-tos --renew-by-default -d {{ grafana_fqdn }}
  become: true
  when: grafana

- name: get a certificate for meshcentral
  shell: certbot certonly --standalone --pre-hook "sudo systemctl stop nginx" --email {{ from_email }} --agree-tos --renew-by-default -d {{ meshcentral_fqdn }}
  become: true
  when: mesh

- name: start and enable nginx
  systemd:
    name: nginx
    state: restarted
    enabled: true
  become: true