- name: Restart Telegraf
  ansible.builtin.systemd:
    name: telegraf
    state: restarted
    daemon_reload: true
    enabled: true
  become: true

- name: Restart Syslog
  ansible.builtin.systemd:
    name: rsyslog
    state: restarted
    enabled: true
  become: true

- name: Restart Journald
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted
    enabled: true
    daemon_reload: true
  become: true
