- name: add signing keys
  apt_key:
    state: present
    url: https://repos.influxdata.com/influxdb.key
  become: true

- name: add influx data repo
  apt_repository:
    repo: "deb https://repos.influxdata.com/ubuntu {{ ansible_facts['lsb']['codename'] }} stable"
    state: present
  become: true

- name:
  apt:
    name: influxdb2
    state: present
  become: true

- name: Start and Enable Influxdb
  systemd: 
    name: influxd
    state: restarted
    enabled: true
  become: true