- name: Install Influxdb from Deb File
  apt:
    deb: https://dl.influxdata.com/influxdb/releases/influxdb_{{ influx_version }}_amd64.deb
  become: true

- name: Start and Enable Influxdb
  systemd: 
    name: influxd
    state: restarted
    enabled: true
  become: true