- name: download and extract influxdb
  unarchive:
    src: https://dl.influxdata.com/influxdb/releases/influxdb_2.0.0-beta.16_linux_amd64.tar.gz
    dest: /usr/local/bin
    remote_src: yes
  become: true

- name: link influxd and influx binaries
  file:
    src: "/usr/local/bin/influxdb_2.0.0-beta.16_linux_amd64/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    state: link
  with_items: "{{ binaries }}"
  become: true
  
- name: remove info files
  file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ info_files }}"
  become: true

- name: create influxdb group
  group:
    name: influxdb
    state: present
  become: true

- name: create influxdb user
  user:
    name: influxdb
    state: present
  become: true

- name: create influxdb storage directories
  file:
    path: "{{ item }}"
    state: directory
    owner: influxdb
    group: influxdb
  become: true
  with_items: "{{ influx_directories }}"

- name: copy influxdb service
  copy:
    src: influxd2.service
    dest: /etc/systemd/system/influxd2.service
  become: true

- name: start and enable influxdb service
  systemd:
    name: influxd2
    state: restarted
    enabled: true
    daemon-reload: true
  become: true


