- name: create grafana directories
  file:
    state: directory
    path: '{{ item }}'
    mode: '770'
    setype: container_file_t
  become: true
  with_items:
    - /opt/shift-mon
    - /opt/shift-mon/grafana-config/provisioning/dashboards
    - /opt/shift-mon/grafana-config/provisioning/datasources
    - /opt/shift-mon/grafana

- name: Copy dashboards
  copy:
    src: dashboards
    dest: /opt/shift-mon/grafana
  become: true

- name: Configure dashboards
  copy:
    src: dashboards.yml
    dest: /opt/shift-mon/grafana-config/provisioning/dashboards/shift-dashboards.yml
  become: true

- name: Configure Datasources
  template:
    src: datasources.yml
    dest: /opt/shift-mon/grafana-config/provisioning/datasources/shift-datasources.yml
  become: true

- name: Copy Grafana config
  template:
    src: grafana.ini
    dest: /opt/shift-mon/grafana-config/grafana.ini
  become: true

- name: Copy LDAP config
  template:
    src: ldap.toml
    dest: /opt/shift-mon/grafana-config/ldap.toml
  become: true
  when: ldap_host is defined

- name: add  grafana config to telegraf
  copy:
    src: grafana-docker.conf
    dest: /etc/telegraf/telegraf.d/grafana-docker.conf
  become: true
  notify: restart telegraf