- name: Copy dashboards
  copy: 
    src: dashboards  
    dest: /opt/shift-mon/grafana
  become: true

- name: create grafana directories
  file:
    state: directory
    path: /opt/shift-mon/grafana-config/provisioning/{{ item }}
  become: true
  with_items:
    - dashboards
    - datasources

- name: Configure dashboards
  copy:
    src: dashboards.yml
    dest: /opt/shift-mon/grafana-config/provisioning/dashboards/shift-dashboards.yml
  become: true

- name: Configure Datasources
  template:
    src: datasources.yml
    dest: /opt/shift-mon/grafana-config/provisioning/datasources/shift-datasources.yml
  become: true

- name: Copy Grafana config
  template:
    src: grafana.ini
    dest: /opt/shift-mon/grafana-config/grafana.ini
  become: true

- name: Copy LDAP config
  template:
    src: ldap.toml
    dest: /opt/shift-mon/grafana-config/ldap.toml
  become: true
  when: ldap_host is defined