- name: add GPG key for repo on Debian based systems
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present
  become: true

- name: add repo for Debian based systems
  apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"
    state: present
    update_cache: no
  become: true

- name: install install packages for grafana
  apt:
    name: "{{ packages }}"
    update_cache: true
    state: present
  become: true

- name: install grafana plugins
  shell: grafana-cli plugins install {{ item }}
  become: true
  with_items: "{{ plugins }}"

- name: start and enable Grafana
  systemd:
    name: grafana-server
    enabled: yes
    state: restarted
  become: true