- name: Make sure user didn't define dashboards folder
  ansible.builtin.fail:
    msg: Please do not use the name foldername dashboards since that is the folder name shift-mon uses for the builtin dashboards
  when: 
    - grafana.dashboard_paths is defined
    - '"dashboards" in grafana.dashboard_paths.keys()'

- name: Create Shift-mon folder
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: shiftmon
    group: shiftmon
    mode: '770'
    setype: container_file_t
  become: true
  with_items:
    - /opt/shift-mon

- name: Create Grafana directories
  ansible.builtin.file:
    state: directory
    path: '{{ item }}'
    mode: '770'
    owner: shiftmon
    group: shiftmon
    setype: container_file_t
  become: true
  with_items:
    - /opt/shift-mon/grafana-config/provisioning/dashboards
    - /opt/shift-mon/grafana-config/provisioning/datasources
    - /opt/shift-mon/grafana-config/provisioning/plugins
    - /opt/shift-mon/grafana-config/provisioning/alerting
    - /opt/shift-mon/grafana-config/provisioning/notifiers
    - /opt/shift-mon/grafana/victoriametrics-dashboards
    - /opt/shift-mon/grafana
    - /opt/shift-mon/valkey

- name: Copy Dashboards
  ansible.builtin.copy:
    src: dashboards
    dest: /opt/shift-mon/grafana
    owner: shiftmon
    group: shiftmon
  become: true

- name: Download Victoriametrics Dashboards
  ansible.builtin.get_url:
    url: 'https://raw.githubusercontent.com/VictoriaMetrics/VictoriaMetrics/master/dashboards/vm/{{ item }}'
    dest: '/opt/shift-mon/grafana/victoriametrics-dashboards/{{ item }}'
    mode: '770'
    owner: shiftmon
    group: shiftmon
  become: true
  with_items:
    - victoriametrics.json
    - vmalert.json
    - vmauth.json
    - victorialogs.json

- name: Download Dashbaords from Grafana.com
  ansible.builtin.get_url:
    url: https://grafana.com/api/dashboards/{{ item.id }}/revisions/{{ item.revision }}/download
    dest: '/opt/shift-mon/grafana/dashboards/{{ item.name }}.json'
    mode: '770'
    owner: shiftmon
    group: shiftmon
  become: true
  with_items:
    - name: alertmanager
      id: 20715
      revision: 1
    - name: vmanomaly-self-monitoring
      id: 22337
      revision: 7
    - name: vmanomaly-stats
      id: 22922
      revision: 1

- name: Configure Dashboard Provisioning 
  ansible.builtin.template:
    src: dashboards.yml
    dest: /opt/shift-mon/grafana-config/provisioning/dashboards/shift-dashboards.yml
    owner: shiftmon
    group: shiftmon
  become: true

- name: Configure Datasource Provisioning
  ansible.builtin.template:
    owner: shiftmon
    group: shiftmon
    src: datasources.yml
    dest: /opt/shift-mon/grafana-config/provisioning/datasources/shift-datasources.yml
  become: true

- name: Copy Grafana config
  ansible.builtin.template:
    src: grafana.ini
    dest: /opt/shift-mon/grafana-config/grafana.ini
    owner: shiftmon
    group: shiftmon
  become: true

- name: Copy LDAP config
  ansible.builtin.template:
    src: ldap.toml
    dest: /opt/shift-mon/grafana-config/ldap.toml
    owner: shiftmon
    group: shiftmon
  become: true
  when: ldap_host is defined

- name: Add user provisioned alerts
  ansible.builtin.copy:
    src: "{{ grafana.alert_path }}"
    dest: /opt/shift-mon/grafana-config/provisioning/alerting/user-alerts.yml
    owner: shiftmon
    group: shiftmon
  become: true
  when: grafana.alert_path is defined

- name: Upload user provisioned dashboards
  ansible.builtin.copy:
    src: "{{ item.value }}"
    dest: "/opt/shift-mon/grafana"
    owner: shiftmon
    group: shiftmon
  become: true
  when: grafana.dashboard_paths is defined
  with_items: "{{ grafana.dashboard_paths | dict2items }}"

