shiftmon_snmp_version: '2'
shiftmon_snmp_auth_protocol: 'MD5'
shiftmon_snmp_auth_priv: 'authNoPriv'
shiftmon_local_syslog_endpoint: "udp://:6667"
shiftmon_remote_syslog_endpoint: "udp://0.0.0.0:6666"
telegraf_traefik_log_file_path: /opt/shift-mon/traefik/access.json
shiftmon_json_apps:
  - 'caddy'
  - 'Nextcloud'
  - '*suricata*'
  - '*loki*'
  - '*grafana*'
  - '*traefik*'
  - '*authentik-server*'
  - '*authentik-worker*'
  - '*falco*'
  - '*mirotalk*'
  - 'blocky'
  - 'shift-mon-vmauth*'
  - 'shift-mon-vmalert*'
  - 'shift-mon-victoria*'
shiftmon_logfmt_apps:
  - '*alertmanager*'
  - '*dendrite-monolith*'
  - '*watchtower*'
  - '*dockerd*'
traefik_container_name: shift-mon_traefik_1
user_secrets: {}
global_telegraf_tags: {}
extra_vars_tags: []
do_not_instrument:
  - 'nftables'
reverse_lookup_adguardhome: true
reverse_lookup_caddy: true
reverse_lookup_http: true
reverse_lookup_remote_syslog: true
reverse_lookup_syslog: true
reverse_lookup_traefik: true
journald_forwarding: true
nut_enabled: false
telegraf_crowdsec_config: false
telegraf_secrets:
  victoria_user: "{{ victoria.user }}"
  victoria_password: "{{ victoria.password }}"
  loki_user: "{{ loki.user }}"
  loki_password: "{{ loki.password }}"
telegraf_root: false
telegraf_user: "{{ 'root' if (telegraf_root) else 'telegraf' }}"
metric_buffer_limit: "10000"
metric_batch_size: "1000"
interval: "10s"
flush_interval: "10s"

