telegraf_traefik_log_file_path: /opt/shift-mon/traefik/access.json
traefik_container_name: shift-mon_traefik_1
user_secrets: {}
global_telegraf_tags: {}
extra_vars_tags: []
do_not_instrument: []
reverse_lookup_adguardhome: true
reverse_lookup_caddy: true
reverse_lookup_http: true
reverse_lookup_remote_syslog: true
reverse_lookup_syslog: true
reverse_lookup_traefik: true
journald_forwarding: true
nut_enabled: false
telegraf_victoriametrics_config: false
telegraf_crowdsec_config: false
telegraf_grafana_config: false
telegraf_loki_config: false
