telegraf_traefik_log_file_path: /opt/shift-mon/traefik/access.json
traefik_container_name: shift-mon_traefik_1
user_secrets: {}
global_telegraf_tags: {}
extra_vars_tags: []
do_not_instrument: []
reverse_lookup_adguardhome: true
reverse_lookup_caddy: true
reverse_lookup_http: true
reverse_lookup_remote_syslog: true
reverse_lookup_syslog: true
reverse_lookup_traefik: true
journald_forwarding: true
nut_enabled: false
telegraf_victoriametrics_config: false
telegraf_crowdsec_config: false
telegraf_grafana_config: false
telegraf_loki_config: false
telegraf_root: false # here to support users that rely on old behavior of allowing to telegraf root by setting a variable
telegraf_secrets:
  victoria_user: "{{ victoria.user }}"
  victoria_password: "{{ victoria.password }}"
  loki_user: "{{ loki.user }}"
  loki_password: "{{ loki.password }}"
telegraf_user: "{{ 'root' if (telegraf_root) else 'telegraf' }}"
telegraf_use_secrets: false
victorialogs_enabled: false
