stages:
    - kics
    - ansible-lint
    - galaxy-publish

kics-scan:
    stage: kics
    image:
      name: checkmarx/kics:latest
      entrypoint: [""]
    script:
        - kics scan --no-progress -p ${PWD} -o ${PWD} --report-formats json --output-name kics-results
    artifacts:
        name: kics-results.json
        paths:
            - kics-results.json
        when: always

ansible-lint:
  stage: ansible-lint
  image: registry.gitlab.com/pipeline-components/ansible-lint:latest
  script:
    - ansible-lint .

galaxy-publish:
  stage: galaxy-publish
  image: registry.gitlab.com/pipeline-components/ansible-galaxy:latest
  script:
    - version=`grep version: galaxy.yml | sed 's:.*\ ::'` && ansible-galaxy collection build --force --token ${GALAXY_API_KEY} && ansible-galaxy collection publish shiftsytsems-shift_mon-${version}.tar.gz --token ${GALAXY_API_KEY}
