stages:
    - kics
    - ansible-lint

kics-scan:
    stage: kics
    image:
      name: checkmarx/kics:latest
      entrypoint: [""]
    script:
        - kics scan --no-progress -p ${PWD} -o ${PWD} --report-formats json --output-name kics-results
    artifacts:
        name: kics-results.json
        paths:
            - kics-results.json
        when: always

ansible-lint:
  stage: ansible-lint
  image: python:3-slim
  script:
    - pip install ansible ansible-lint && ansible-lint .
