stages:
    - shiftmon-release
    - kics
    - ansible-lint
    - galaxy-publish

kics-scan:
  stage: kics
  image:
    name: checkmarx/kics:latest
    entrypoint: [""]
  script:
    - kics scan -p ${PWD} -o ${PWD} --report-formats json --output-name kics-results --exclude-queries 8d29754a-2a18-460d-a1ba-9509f8d359da,c05e2c20-0a2c-4686-b1f8-5f0a5612d4e8,88841d5c-d22d-4b7e-a6a0-89ca50e44b9f
  artifacts:
    name: kics-results.json
    paths:
      - kics-results.json
    when: always

ansible-lint:
  stage: ansible-lint
  image: registry.gitlab.com/pipeline-components/ansible-lint:latest
  script:
    - ansible-lint .

shiftmon-release:
  stage: shiftmon-release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - 'SHIFTMON_RELEASE=v$(grep version: galaxy.yml | sed "s:.*\ ::")'
    - 'echo $SHIFTMON_RELEASE'
  release:
    tag_name: ${SHIFTMON_RELEASE}
    description: './CHANGELOG.md'
  only:
    - main@shiftsystems/shiftmon

galaxy-publish:
  stage: galaxy-publish
  image: quay.io/pulp/galaxy-minimal:latest
  script:
    - 'ansible-galaxy collection build . --force && ansible-galaxy collection publish shiftsystems-shift_mon-$(grep "version: " galaxy.yml | sed "s:.*\ ::").tar.gz --token $GALAXY_API_KEY'
  only:
    - main@shiftsystems/shiftmon

