services:
  grafana:
    image: grafana/grafana-oss:latest
    restart: unless-stopped
    volumes:
      - type: bind
        source: /opt/shift-mon/grafana-config
        target: /etc/grafana
      - type: bind
        source: /opt/shift-mon/grafana
        target: /var/lib/grafana
    ports:
      - 3000:3000
  loki:
    image: grafana/loki:latest
    restart: unless-stopped
    volumes:
      - type: bind
        source: /opt/shift-mon/loki
        target: /loki
      - type: bind
        source: /opt/shift-mon/loki-config
        target: /etc/loki/
    ports:
      - 3100:3100
    command:
      #- "-mount source=loki,target=/loki"
      - "-config.file=/etc/loki/loki-config.yml"
  victoriametrics:
    restart: unless-stopped
    image: victoriametrics/victoria-metrics:latest
    volumes: 
      - type: bind
        source: /opt/shift-mon/victoriametrics-storage
        target: /storage
    ports:
      - 8428:8428
    command:
      - "--retentionPeriod=90d"
      - "--storageDataPath=/victoriametrics-storage"
      - "--httpListenAddr=:8428"
  traefik:
    restart: unless-stopped
    image: traefik:latest
    volumes:
      - type: bind
        source: /opt/shift-mon/traefik
        target: /etc/traefik
    ports:
     - 80:80
     - 443:443
  vmauth:
    restart: unless-stopped
    image: victoriametrics/vmauth:latest
    volumes:
      - type: bind
        source: /opt/shift-mon/victoriametrics
        target: /config
    ports:
      - 8427:8427
    command:
      - "--auth.config=/config/auth-config.yml"