- hosts: all
  tasks:
    - import_role:
        name: uptime-kuma
    - import_role:
        name: victoriametrics
    - import_role:
        name: loki
    - import_role:
        name: grafana
    - import_role:
        name: telegraf
    - import_role:
        name: traefik
    - import_role:
        name: crowdsec
    - import_role:
        name: podman