- hosts: all
  tasks:
    - import_role:
        name: victoriametrics
    - import_role:
        name: loki
    - import_role:
        name: grafana
    - import_role:
        name: nginx
      when: nginx
