- hosts: all
  tasks:
    - name: Set tsdb_date
      ansible.builtin.set_fact:
        loki:
          tsdb_date: "{{ lookup('env', 'TSDB_DATE') }}"
      when: "{{ lookup('env', 'TSDB_DATE', default=False) }}"
    - name: Set Secrets
      ansible.builtin.set_fact:
        oncall_enabled: false
        oncall:
          secret: "{{ lookup('env', 'ONCALL_SECRET') }}"
          domain: "{{ lookup('env', 'ONCALL_DOMAIN') }}"
          # key_path: "{{ playbook_dir }}/files/oncall.key"
          # cert_path: "{{ playbook_dir }}/files/oncall.crt"
        bind_password: "{{ lookup('env', 'BIND_PASSWORD') }}" # optional LDAP Bind Password
        grafana:
          domain: "{{ lookup('env', 'GRAFANA_DOMAIN') }}"
        uptimekuma:
          domain: "{{ lookup('env', 'UPTIMEKUMA_DOMAIN') }}"
        tls:
          email: "{{ lookup('env', 'TLS_EMAIL') }}"
        loki:
          user: telegraf
          password: "{{ lookup('env', 'LOKI_PASSWORD') }}"
          url: "{{ lookup('env', 'LOKI_URL') }}"
          domain: "{{ lookup('env', 'LOKI_DOMAIN') }}"
          retention_period: 90d
          # cert_path: "{{ playbook_dir }}/files/loki.crt" # optional use if you want to use your own cert for Loki
          # key_path: "{{ playbook_dir }}/files/loki.key" # optional use if you want to use your own cert for Loki
        victoria:
          user: telegraf
          password: "{{ lookup('env', 'TELEGRAF_PASSWORD') }}"
          url: "{{ lookup('env', 'VICTORIA_URL') }}"
          retention_period: 90d
          domain: "{{ lookup('env', 'VICTORIA_DOMAIN') }}"
          # cert_path: "{{ playbook_dir }}/files/victoria.crt" # optional use if you want to use your own cert for Victoriametrics
          # key_path: "{{ playbook_dir }}/files/victoria.key" # optional use if you want to use your own cert for Victoriametrics
          # insecure: true # set to true if you need insecure access to Victoriametrics for things that cannot handle SSL or self signed certs
        email:
          enabled: false # uncomment and set to true to allow grafana to send email set to false or uncomment to ignore.
          host: "{{ lookup('env', 'GRAFANA_EMAIL_DOMAIN') }}"
          alert_from_address: "{{ lookup('env', 'TELEGRAF_PASSWORD') }}"
          user: "{{ lookup('env', 'GRAFANA_EMAIL') }}"
          password: "{{ lookup('env', 'GRAFANA_EMAIL') }}"
          alert_from_name: 'Shiftmon Alerts'
          port: '587'
        users: # dictionary of users and their password
          telegraf: "{{ lookup('env', 'TELEGRAF_PASSWORD') }}"
          # fleet_yeet: "{{ lookup('env', 'FLEET_PASSWORD') }}"

- hosts: shiftmon_servers
  tasks:
    - name: Set container_engine
      ansible.builtin.set_fact:
        container_engine: "{{ lookup('env', 'SERVER_CONTAINER_ENGINE', default='podman') }}"
    - name: Deploy Uptime-Kuma
      ansible.builtin.include_role:
        name: shiftsystems.shift_mon.uptime_kuma
        public: true
    - name: Deploy Telegraf
      ansible.builtin.include_role:
        name: shiftsystems.shift_mon.telegraf
        public: true
    - name: Deploy Victoriametrics
      ansible.builtin.include_role:
        name: shiftsystems.shift_mon.victoriametrics
        public: true
    - name: Deploy Loki
      ansible.builtin.include_role:
        name: shiftsystems.shift_mon.loki
        public: true
    - name: Deploy Grafana
      ansible.builtin.include_role:
        name: shiftsystems.shift_mon.grafana
        public: true
    - name: Deploy Traefik
      ansible.builtin.include_role:
        name: shiftsystems.shift_mon.traefik
        public: true
    - name: Deploy Crowdsec
      ansible.builtin.include_role:
        name: shiftsystems.shift_mon.crowdsec
        public: true
    - name: Deploy Podman
      ansible.builtin.include_role:
        name: shiftsystems.shift_mon.podman
        public: true
      when: container_engine == 'podman'
    - name: Deploy Docker
      ansible.builtin.include_role:
        name: shiftsystems.shift_mon.docker
        public: true
      when: container_engine == 'docker'

- hosts: telegraf
  tasks:
    - name: Deploy Telegraf
      ansible.builtin.include_role:
        name: shiftsystems.shift_mon.telegraf
        public: true
