- hosts: all
  tasks:
    - ansible.builtin.include_role:
        name: "{{ role }}"
      loop:
        - telegraf
        - uptime_kuma
        - victoriametrics
        - loki
        - grafana
        - traefik
        - crowdsec
        - podman
      loop_control:
        loop_var: role
