{
 "title": "Linux Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": {
     "query": "label_values(cpu_usage_idle{db=\"linux\"},host)"
    }
   },
   { "name": "metrics", "query": "prometheus" },
   { "name": "logs", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mem_total{host=\"$host\",db=\"linux\"} / 1000000000"
    }
   ]
  },
  {
   "title": "CPU Count",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_n_cpus{host=\"$host\",db=\"linux\"}"
    }
   ]
  },
  {
   "title": "uptime in days",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(system_uptime{host=\"$host\",db=\"linux\"}) / 86400"
    }
   ]
  },
  {
   "title": "Disk Size",
   "type": "stat",
   "gridPos": { "h": 2, "w": 10, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "disk_total{host=\"$host\",db=\"linux\"} / 1073741824",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Load 1",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_load1{host=\"$host\",db=\"linux\"}"
    }
   ]
  },
  {
   "title": "CPU Percent",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - cpu_usage_idle{host=\"$host\",db=\"linux\"}"
    }
   ]
  },
  {
   "title": "Percent Memory",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mem_used_percent{db=\"linux\",host=\"$host\"}"
    }
   ]
  },
  {
   "title": "disk usage",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 7, "x": 13, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "disk_used_percent{host=\"$host\",db=\"linux\"}",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Load 15",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_load15{host=\"$host\",db=\"linux\"}"
    }
   ]
  },
  {
   "title": "OS Version",
   "type": "table",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "targets": [
    {
     "expr": "{host=\"$host\"}| logfmt |~ \"NAME|VERSION\""
    }
   ]
  },
  {
   "title": "Mbytes/sec received",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "deriv(net_bytes_recv{host=\"$host\",db=\"linux\"}) / 1000000",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "mbytes/sec sent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 9 },
   "targets": [
    {
     "expr": "deriv(net_bytes_sent{host=\"$host\",db=\"linux\"}) / 1000000",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Failed Services",
   "type": "table",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 12 },
   "targets": [
    {
     "expr": "systemd_units_active_code{db=\"linux\",host=\"$host\",active=\"failed\"}"
    }
   ]
  },
  {
   "title": "Services",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "systemd_units_active_code{db=\"linux\",host=\"$host\"}"
    }
   ]
  },
  {
   "title": "Crowdsec logs",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cs_bucket_overflowed_total{host=\"$host\"}"
    }
   ]
  },
  {
   "title": "diskio",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 16 },
   "targets": [
    {
     "expr": "(diskio_read_bytes{host=\"$host\",db=\"linux\"} + diskio_read_bytes{host=\"$host\",db=\"linux\"})/ 1000000",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}