{
 "title": "Nginx",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Metrics", "query": "prometheus" },
   { "name": "Logs", "query": "loki" },
   {
    "name": "host",
    "query": "label_values({path=~\"/var/log/nginx/.*\"},host)"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count_over_time({host=\"$host\",path=~\"/var/log/nginx/.*\"}[$__range])"
    }
   ]
  },
  {
   "title": "Redirects",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "{host=\"$host\",path=~\"/var/log/nginx/.*\"} | logfmt | status >= 300  | status < 400"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "{host=\"$host\",path=~\"/var/log/nginx/.*\"} | logfmt | status >= 400"
    }
   ]
  },
  {
   "title": "User Agents",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "{host=\"$host\",path=~\"/var/log/nginx/.*\"} | logfmt"
    }
   ]
  },
  {
   "title": "Request Log",
   "type": "table",
   "gridPos": { "h": 12, "w": 14, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "{path=~\"/var/log/nginx/.*\",host=\"$host\"} | logfmt"
    }
   ]
  },
  {
   "title": "Status Codes",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 5, "x": 14, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "{host=\"$host\",path=~\"/var/log/nginx/.*\"} | logfmt"
    }
   ]
  },
  {
   "title": "Error Requests",
   "type": "table",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "{path=~\"/var/log/nginx/.*\",host=\"$host\"} | logfmt | status >= 400"
    }
   ]
  },
  {
   "title": "top 10 endpoints",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 14, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "{host=\"$host\",path=~\"/var/log/nginx/.*\"} | logfmt"
    }
   ]
  }
 ]
}