- name: Create vmanomaly directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '770'
    setype: container_file_t
    owner: shiftmon
    group: shiftmon
  become: true
  with_items:
    - "/opt/shift-mon/vmanomaly-config"
    - "/opt/shift-mon/vmanomaly-models"
    - "/opt/shift-mon/vmanomaly-data"
    - "/opt/shift-mon/vmanomaly-logs-config"
    - "/opt/shift-mon/vmanomaly-logs-models"
    - "/opt/shift-mon/vmanomaly-logs-data"

- name: Remove legacy vmanomaly config
  ansible.builtin.file:
    path: /opt/shiftmon/vmanomaly-config/config.yml
    state: absent
  become: true

- name: Add vmanomaly metrics config file
  ansible.builtin.template:
    src: "{{ vmanomaly_config_path }}"
    dest: /opt/shift-mon/vmanomaly-config/config.yaml
    owner: shiftmon
    group: shiftmon
    mode: '770'
    setype: container_file_t
  become: true

- name: Add vmanomaly logs config file
  ansible.builtin.copy:
    src: "{{ vmanomaly_logs_config_path }}"
    dest: /opt/shift-mon/vmanomaly-logs-config/config.yaml
    owner: shiftmon
    group: shiftmon
    mode: '770'
    setype: container_file_t
  become: true
