- name: Create vmanomaly directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '770'
    setype: container_file_t
    owner: 1000
    group: 1000
  become: true
  with_items:
    - "/opt/shift-mon/vmanomaly-config"
    - "/opt/shift-mon/vmanomaly-models"

- name: Add config file
  ansible.builtin.template:
    src: "{{ vmanomaly_config_path }}"
    dest: /opt/shift-mon/vmanomaly-config/config.yml
    owner: 1000
    group: 1000
    mode: '770'
    setype: container_file_t
  become: true
