scrape_configs:
- job_name: shiftmon_victoriametrics
  scrape_interval: 30s
  scrape_timeout: 20s
  static_configs:
    - targets:
      - 'http://victoriametrics:8428'
      - 'http://vmalert:9093'
      - 'http://vmauth:8427'
      - 'http://loki:3100'
      - 'http://grafana:3000'
{% if vmanomaly_enabled and victoria.license is defined %}
      - 'http://vmanomaly:8490'
{% endif %}
      labels:
        host: {{ ansible_nodename }}
