services:
  grafana:
    image: grafana/grafana:12.0.2
    user: "{{ shiftmon_user_id.stdout }}:{{ shiftmon_group_id.stdout }}"
    restart: unless-stopped
    volumes:
      - type: bind
        source: /opt/shift-mon/grafana-config
        target: /etc/grafana
      - type: bind
        source: /opt/shift-mon/grafana
        target: /var/lib/grafana
    depends_on:
      valkey:
        condition: service_healthy
    healthcheck:
      test: 'wget -qO- http://127.0.0.1:3000/api/health'
      interval: '30s'
      timeout: '10s'
      retries: 5
    environment:
      GF_INSTALL_PLUGINS: victoriametrics-metrics-datasource,victoriametrics-logs-datasource
  alertmanager:
    image: quay.io/prometheus/alertmanager:v0.28.1
    user: "{{ shiftmon_user_id.stdout }}:{{ shiftmon_group_id.stdout }}"
    restart: unless-stopped
    command:
      - '--config.file=/config/alertmanager.yml'
{% if shiftmon_alertmanager_url is defined %}
      - '--web.external-url={{ shiftmon_alertmanager_url }}'
      - '--web.route-prefix=/'
{% endif %}
      - '--storage.path=/data'
      - '--log.level=debug'
    volumes:
      - type: bind
        source: /opt/shift-mon/alertmanager/data
        target: /data
      - type: bind
        source: /opt/shift-mon/alertmanager/config
        target: /config
    healthcheck:
      test: 'wget -qO- http://127.0.0.1:9093/-/healthy'
      interval: '30s'
      timeout: '10s'
      retries: 5
  loki:
    image: docker.io/grafana/loki:3.5.1
    restart: unless-stopped
    user: "{{ shiftmon_user_id.stdout }}:{{ shiftmon_group_id.stdout }}"
    volumes:
      - type: bind
        source: /opt/shift-mon/loki
        target: /loki
      - type: bind
        source: /opt/shift-mon/loki-config
        target: /etc/loki/
    command:
      - "-config.file=/etc/loki/loki-config.yml"
    healthcheck:
      test: "wget -qO- http://127.0.0.1:3100/ready"
      interval: "30s"
      timeout: "10s"
      retries: 5
  victoriametrics:
    restart: unless-stopped
{% if victoria.license is defined %}
    image: quay.io/victoriametrics/victoria-metrics:v1.119.0-enterprise
{% else %}
    image: quay.io/victoriametrics/victoria-metrics:v1.119.0
{% endif %}
    user: "{{ shiftmon_user_id.stdout }}:{{ shiftmon_group_id.stdout }}"
    volumes:
      - type: bind
        source: /opt/shift-mon/victoriametrics
        target: /victoriametrics
      - type: bind
        source: /opt/shift-mon/victoriametrics-storage
        target: /victoriametrics-storage
    command:
      - "-retentionPeriod={{ victoria.retention_period | default('90d') }}"
      - "-storageDataPath=/victoriametrics-storage"
      - "-httpListenAddr=:8428"
      - "-vmalert.proxyURL=http://vmalert:8880"
      - "-promscrape.config=/victoriametrics/scrape-config.yml"
      - "-relabelConfig=/victoriametrics/relabel-config.yml"
      - "-storage.trackMetricNamesStats"
      #- "-streamAggr.config=/victoriametrics/aggregation-config.yml"
{% if victoria.slow_query_threshold is defined %}
      - "-search.logSlowQueryDuration={{ victoria.slow_query_threshold }}"
{% endif %}
{% if victoriametrics_disable_daily_index %}
      - "-disablePerDayIndex"
{% endif %}
{% if victoria.license is defined %}
      - "-license={{ victoria.license }}"
{% endif %}
{% if victoria.license is defined and victoria.slow_query_threshold is defined %}
      - "-search.logSlowQueryStats={{ victoria.slow_query_threshold }}"
{% endif %}
{% if victoria.license is defined and victoria.retention_filter is defined %}
      - "-retentionFilter={{ victoria.retention_filter }}"
{% endif %}
{% if victoria.license is defined and victoria.downsampling_period is defined %}
      - "-downsampling.period={{ victoria.downsampling_period }}"
{% endif %}
    healthcheck:
      test: "wget -qO- http://127.0.0.1:8428/-/healthy"
      interval: "30s"
      timeout: "10s"
      retries: 5
  vmalert:
    restart: unless-stopped
{% if victoria.license is defined %}
    image: quay.io/victoriametrics/vmalert:v1.119.0-enterprise
{% else %}
    image: quay.io/victoriametrics/vmalert:v1.119.0
{% endif %}
    user: "{{ shiftmon_user_id.stdout }}:{{ shiftmon_group_id.stdout }}"
    volumes:
      - type: bind
        source: /opt/shift-mon/vmalert/rules
        target: /rules
      - type: bind
        source: /opt/shift-mon/vmalert/templates
        target: /templates
    command:
      - "-datasource.url=http://vmauth:8427"
      - "-datasource.bearerToken=vmalert"
      - "-notifier.url=http://alertmanager:9093"
      - "-remoteWrite.url=http://victoriametrics:8428"
      - "-remoteRead.url=http://victoriametrics:8428"
      - "-httpListenAddr=0.0.0.0:8880"
      - "-rule.templates=/templates/*.tpl"
      - "-rule=/rules/*.yaml"
      - "-rule=/rules/*.yml"
      - "-configCheckInterval=1m"
      - "-external.url=https://{{ grafana.domain }}"
{% raw %}
      - -external.alert.source=explore?left={"datasource":"shift-victoriametrics","queries":[{"expr":{{ .Expr|jsonEscape|queryEscape }},"refId":"A"}],"range":{"from":"{{ .ActiveAt.UnixMilli }}","to":"now"}}
{% endraw %}
{% if victoria.license is defined %}
      - "-license={{ victoria.license }}"
{% endif %}
    healthcheck:
      test: "wget -qO- http://127.0.0.1:8880/-/healthy"
      interval: "30s"
      timeout: "10s"
      retries: 5
  vmauth:
    restart: unless-stopped
{% if victoria.license is defined %}
    image: quay.io/victoriametrics/vmauth:v1.119.0-enterprise
{% else %}
    image: quay.io/victoriametrics/vmauth:v1.119.0
{% endif %}
    user: "{{ shiftmon_user_id.stdout }}:{{ shiftmon_group_id.stdout }}"
    volumes:
      - type: bind
        source: /opt/shift-mon/vmauth
        target: /auth
    command:
      - "-auth.config=/auth/auth-config.yml"
      - "-httpListenAddr=0.0.0.0:8427"
      - "-httpInternalListenAddr=0.0.0.0:9999"
{% if victoria.license is defined %}
      - "-license={{ victoria.license }}"
{% endif %}
    healthcheck:
      test: "wget -qO- http://127.0.0.1:9999/-/healthy"
      interval: "30s"
      timeout: "10s"
      retries: 5
    ports:
     - "127.0.0.1:8427:8427"
{% if vmanomaly_enabled and victoria.license is defined %}
  vmanomaly:
    image: quay.io/victoriametrics/vmanomaly:v1.24.1
    user: "{{ shiftmon_user_id.stdout }}:{{ shiftmon_group_id.stdout }}"
    restart: always
    healthcheck:
      test: ["CMD","curl","http://127.0.0.1:8490/health"]
      interval: "30s"
      timeout: "10s"
      retries: 5
    depends_on:
      victoriametrics:
        condition: service_healthy
    volumes:
      - type: bind
        source: /opt/shift-mon/vmanomaly-config
        target: /config
      - type: bind
        source: /opt/shift-mon/vmanomaly-models
        target: /models
      - type: bind
        source: /opt/shift-mon/vmanomaly-data
        target: /data
    command:
      - "/config/config.yml"
      - "--license={{ victoria.license }}"
      - "--loggerLevel={{ vmanomaly_log_level }}"
    environment:
      VMANOMALY_MODEL_DUMPS_DIR: /models
      VMANOMALY_DATA_DUMPS_DIR: /data
{% endif %}
  valkey:
    image: docker.io/valkey/valkey:8-alpine
    restart: always
    user: "{{ shiftmon_user_id.stdout }}:{{ shiftmon_group_id.stdout }}"
    expose:
      - 6379
    volumes:
      - type: bind
        source: /opt/shift-mon/valkey
        target: /data
    deploy:
      resources:
        limits:
          memory: 500m
          cpus: "0.5"
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      timeout: 5s
      interval: 5s
      retries: 10
  victorialogs:
    user: "{{ shiftmon_user_id.stdout }}:{{ shiftmon_group_id.stdout }}"
    image: quay.io/victoriametrics/victoria-logs:v1.24.0-victorialogs
    restart: unless-stopped
    volumes:
      - type: bind
        source: /opt/shift-mon/victorialogs
        target: /victorialogs
    command:
      - -storageDataPath=/victorialogs
      - -retentionPeriod={{ victorialogs.retention_period }}
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:9428/health"]
      interval: 5s
      timeout: 5s
      retries: 10
  traefik:
    restart: unless-stopped
    image: docker.io/traefik:latest
    user: root
    volumes:
      - type: bind
        source: /opt/shift-mon/traefik
        target: /etc/traefik
    healthcheck:
      test: ["CMD", "traefik", "healthcheck"]
      timeout: 5s
      interval: 5s
      retries: 10
    ports:
     - "80:80"
     - "443:443"
     - "127.0.0.1:8082:8082"
{% if dns.provider is defined and dns.auth_values is defined %}
    environment:
{% for key, value in dns.auth_values.items() %}
      {{key}}: '{{value}}'
{% endfor %}
{% endif %}
    command:
      - "--auth.config=/config/auth-config.yml"
