- name: Reload Systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Restart Docker
  ansible.builtin.systemd:
    name: docker
    state: restarted
    enabled: true
  become: true
