- name: Install Rsyslog
  ansible.builtin.apt:
    name: rsyslog
    state: latest
  become: true
  notify: Restart Syslog

- name: Use victoriametrics_token if metrics_token is not defined
  ansible.builtin.set_fact:
    metrics_token: "{{ victoriametrics_token }}"
  when: metrics_token is not defined

- name: Check if host is running Proxmox Backup Server
  ansible.builtin.stat:
    path: /etc/pve
  register: pve

- name: Check if host is running Proxmox Backup Server
  ansible.builtin.stat:
    path: /etc/proxmox-backup
  register: pbs

- name: Add Syslog forwarding to Shiftmon
  ansible.builtin.template:
    src: 50-shiftmon.conf
    dest: /etc/rsyslog.d/50-shiftmon.conf
    mode: "644"
  become: true
  notify: Restart Syslog

- name: Create /etc/pve/status.cfg
  ansible.builtin.file:
    path: /etc/pve/status.cfg
    state: touch
  become: true
  when:
    - pve.stat.isdir is defined
    - pve.stat.isdir

- name: Add metrics server on Proxmox Virtual Environment
  ansible.builtin.blockinfile:
    path: /etc/pve/status.cfg 
    block: |
      influxdb: {{ metrics_name }}
          port {{ metrics_port }}
          server {{ victoriametrics_url | regex_replace('^https?://', '') }}
          bucket {{ metrics_bucket }}
          influxdbproto  {{ metrics_protocol }}
  notify: Restart pvestatd
  when:
    - pve.stat.isdir is defined
    - pve.stat.isdir
  become: true

- name: Create Token secrets file
  ansible.builtin.file:
    path: "/etc/pve/priv/metricserver/{{ metrics_name}}.pw"
    state: touch
  become: true
  when:
    - metrics_token is defined
    - pve.stat.isdir is defined
    - pve.stat.isdir

- name: Add Token to Proxmox Virtual Environment
  ansible.builtin.template:
    src: metrics.pw
    dest: "/etc/pve/priv/metricserver/{{ metrics_name}}.pw"
    unsafe_writes: true
  become: true
  when:
    - metrics_token is defined
    - pve.stat.isdir is defined
    - pve.stat.isdir

# Metric server doesn't support comments in PBS so we overite the file
- name: Add metric server on Proxmox Backup Server
  ansible.builtin.template:
    src: metricserver.cfg
    dest: /etc/proxmox-backup/metricserver.cfg
  when:
    - pbs.stat.isdir is defined
    - pbs.stat.isdir
