- name: Install Rsyslog
  ansible.builtin.apt:
    name: rsyslog
    state: latest
  become: true
  notify: Restart Syslog

- name: Check if host is running Proxmox Backup Server
  ansible.builtin.stat:
    path: /etc/pve
  register: pve

- name: Check if host is running Proxmox Backup Server
  ansible.builtin.stat:
    path: /etc/proxmox-backup
  register: pbs

- name: Add Syslog forwarding to Shiftmon
  ansible.builtin.template:
    src: 50-shiftmon.conf
    dest: /etc/rsyslog.d/50-shiftmon.conf
    mode: "644"
  become: true
  notify: Restart Syslog

- name: Add metrics server on Proxmox Virtual Environment
  ansible.builtin.blockinfile:
    path: /etc/pve/status.cfg 
    block: |
      influxdb: {{ metrics_name }}
          port {{ metrics_port }}
          server {{ metrics_host }}
          bucket {{ metrics_bucket }}
          influxdbproto  {{ metrics_protocol }}
  notify: Restart pvestatd
  when: pve.stat.isdir is defined and pve.stat.isdir

# Metric server doesn't support comments in PBS so we overrite the file
- name: Add metric server on Proxmox Backup Server
  ansible.builtin.template:
    src: metricserver.cfg
    dest: /etc/proxmox-backup/metricserver.cfg
  when: pbs.stat.isdir is defined and pbs.stat.isdir