{
 "title": "Adguard",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "logs", "query": "loki" },
   { "name": "metrics", "query": "prometheus" },
   {
    "name": "host",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "All Queries",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{host=\"$host\",path=~\".*data/querylog.json\"} | logfmt"
    }
   ]
  },
  {
   "title": "filtered queries",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{host=\"$host\",path=~\".*data/querylog.json\"}  |~ \"Result_IsFiltered\"| logfmt "
    }
   ]
  },
  {
   "title": "Top queried domains",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "topk(20,sum(count_over_time({host=\"$host\",path=~\".*data/querylog.json\"}  | logfmt[$__range])) by (QH))",
     "legendFormat": "{{ QH }}"
    }
   ]
  },
  {
   "title": "Top Queriers",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 6, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "topk(20,sum(count_over_time({host=\"$host\",path=~\".*data/querylog.json\"}  | logfmt[$__range])) by (IP))",
     "legendFormat": "{{ IP }}"
    }
   ]
  },
  {
   "title": "Top filtered domains",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 6, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(20,sum(count_over_time({host=\"$host\",path=~\".*data/querylog.json\"}  |~ \"Result_IsFiltered\"| logfmt[$__range])) by (QH))",
     "legendFormat": "{{ QH }}"
    }
   ]
  },
  {
   "title": "Top Filtered Hosts",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "topk(20,sum(count_over_time({host=\"$host\",path=~\".*data/querylog.json\"}  |~ \"Result_IsFiltered\"| logfmt[$__range])) by (IP))",
     "legendFormat": "{{ IP }}"
    }
   ]
  }
 ]
}