{
 "title": "Alerting Overview",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "alertmanager",
    "query": "camptocamp-prometheus-alertmanager-datasource"
   },
   {
    "name": "metrics",
    "query": "victoriametrics-metrics-datasource"
   },
   {
    "name": "group",
    "query": {
     "query": "label_values(vmalert_alerts_firing,group)"
    }
   },
   { "name": "topk", "query": "5, 10, 20, 30, 50" }
  ]
 },
 "panels": [
  { "title": "vmalert", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Firing state of alerting rules on timeline",
   "type": "state-timeline",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sort_desc(topk_max($topk, sum(vmalert_alerts_firing{group=~\"$group\"}) by (alertname)))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alerting groups",
   "type": "stat",
   "description": "Shows the total number of loaded alerting rules across selected instances and groups.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(count(vmalert_alerting_rules_errors_total{group=~\"$group\"}) by (group))"
    }
   ]
  },
  {
   "title": "Alerting rules",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(vmalert_alerting_rules_errors_total{group=~\"$group\"})"
    }
   ]
  },
  {
   "title": "FIRING over time by group",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "topk_max(100, sum(increases_over_time(vmalert_alerts_firing{group=~\"$group\"}[$__range])) by(group, alertname) > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FIRING over time by rule",
   "type": "table",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "topk_max($topk, sum(increases_over_time(vmalert_alerts_firing{group=~\"$group\"}[$__range])) by (group, alertname) > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "alertmanager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Firing",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Silenced",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Inhibited",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Alerts",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {}
   ]
  }
 ]
}