{
 "title": "Authentik",
 "tags": [ "linux" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "metrics",
    "query": "victoriametrics-metrics-datasource"
   },
   { "name": "logs", "query": "loki" },
   {
    "name": "host",
    "query": {
     "query": "label_values(authentik_flows_execution_stage_time_bucket,host)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Outposts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Outpost Info",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "authentik_outpost_info{host=~\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Task time",
     "type": "heatmap",
     "gridPos": { "h": 11, "w": 15, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "sum by (le) (rate(authentik_system_tasks_time_seconds_bucket{host=~\"$host\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Task status",
     "type": "piechart",
     "gridPos": { "h": 11, "w": 9, "x": 15, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (status) (increase(authentik_system_tasks_status{}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Average Task Duration",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 15, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (task_name) (authentik_system_tasks{host=~\"$host\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Task Count",
     "type": "piechart",
     "gridPos": { "h": 11, "w": 9, "x": 15, "y": 51 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count by (task_name) (authentik_system_tasks{host=~\"$host\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Timings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Flow time",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "sum by (le) (rate(authentik_flows_stage_time_bucket{host=~\"$host\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Plan time",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "sum by (le) (rate(authentik_flows_plan_time_bucket{host=~\"$host\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Main Request Time",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "sum by (le) (rate(authentik_main_request_duration_seconds_bucket{host=~\"$host\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Policy Request Time",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "expr": "sum by (le) (rate(authentik_policies_engine_time_total_seconds_bucket{host=~\"$host\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Policy Request Time",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "sum by (le) (rate(authentik_policies_execution_time_bucket{host=~\"$host\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Property Mapping Request Time",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "targets": [
      {
       "expr": "sum by (le) (rate(authentik_property_mapping_execution_time_bucket{host=~\"$host\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Authentik Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Authentik Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "(tags.host:$host) AND tags.appname:authentik"
    }
   ]
  }
 ]
}