{
 "title": "Blackbox",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "metrics", "query": "prometheus" },
   { "name": "logs", "query": "loki" },
   {
    "name": "host",
    "query": {
     "query": "label_values(x509_cert_enddate,host)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Totals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Healthy Checks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(sum by (server,host) (clamp(http_response_result_code,0,1) == 0)) or vector(0)) + (count(sum by (server,record_type,domain,host) (clamp(dns_query_result_code,0,1) == 0)) or vector(0)) + (count(sum by (url,host) (clamp(ping_result_code,0,1) == 0)) or vector(0)) + (count(sum by (server,record_type,domain,host) (clamp(net_response_result_code,0,1) == 0)) or vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unhealthy Checks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(sum by (server,host) (clamp(http_response_result_code,0,1) == 1)) or vector(0)) + (count(sum by (server,record_type,domain,host) (clamp(dns_query_result_code,0,1) == 1)) or vector(0)) + (count(sum by (url,host) (clamp(ping_result_code,0,1) == 1)) or vector(0)) + (count(sum by (server,record_type,domain,host) (clamp(net_response_result_code,0,1) == 1)) or vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Certs that are about to expire",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count((x509_cert_enddate{} - time()) < 604800)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Checks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(sum by (server,host) (clamp(http_response_result_code,0,1))) or vector(0)) + (count(sum by (server,record_type,domain,host) (clamp(dns_query_result_code,0,1))) or vector(0)) + (count(sum by (url,host) (clamp(ping_result_code,0,1))) or vector(0)) + (count(sum by (server,record_type,domain,host) (clamp(net_response_result_code,0,1))) or vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Healthy HTTP Checks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(sum by (server,host) (clamp(http_response_result_code,0,1) == 0)) or vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unhealthy HTTP Checks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(sum by (server,host) (clamp(http_response_result_code,0,1) == 1)) or vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total HTTP Checks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(sum by (server,host) (clamp(http_response_result_code,0,1))) or vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mean HTTP Response Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(http_response_response_time{result=\"success\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Uptime",
   "type": "table",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - ((sum_over_time(sum by (server,host) (clamp(http_response_result_code,0,1))[$__range])) / (sum_over_time(sum by (server,host) (clamp(http_response_result_code,1,1))[$__range])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (server,host) (clamp(http_response_result_code,0,1))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Healthy HTTP Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (server) (http_response_response_time{result=\"success\"})",
     "legendFormat": "{{server}} {{ name }}"
    }
   ]
  },
  { "title": "DNS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Healthy DNS Checks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(sum by (server,record_type,domain,host) (clamp(dns_query_result_code,0,1) == 0)) or vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unhealthy DNS Checks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(sum by (server,record_type,domain,host) (clamp(dns_query_result_code,0,1) == 1)) or vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total DNS Checks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(sum by (server,record_type,domain,host) (clamp(dns_query_result_code,0,1))) or vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mean DNS Response Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(dns_query_query_time_ms{result=\"success\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DNS Uptime",
   "type": "table",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - ((sum_over_time(sum by (server,record_type,domain,host) (clamp(dns_query_result_code,0,1))[$__range])) / (sum_over_time(sum by (server,record_type,domain,host) (clamp(dns_query_result_code,1,1))[$__range])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (server,record_type,domain,host) (clamp(dns_query_result_code,0,1))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Healthy DNS Query Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (domain, record_type) (dns_query_query_time_ms{rcode=\"NOERROR\"})",
     "legendFormat": "{{ name }} {{domain}} {{ record_type}}"
    }
   ]
  },
  { "title": "Net Response", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Healthy Checks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(sum by (server,record_type,domain,host) (clamp(net_response_result_code,0,1) == 0)) or vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unhealthy Net Response Checks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(sum by (server,record_type,domain,host) (clamp(net_response_result_code,0,1) == 1)) or vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mean Net Response Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(net_response_response_time{result=\"success\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Checks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(sum by (server,record_type,domain,host) (clamp(net_response_result_code,0,1))) or vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Net Response Uptime",
   "type": "table",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - ((sum_over_time(sum by (server,port,host) (clamp(net_response_result_code,0,1))[$__range])) / (sum_over_time(sum by (server,port,host) (clamp(net_response_result_code,1,1))[$__range])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (server,record_type,domain,host) (clamp(net_response_result_code,0,1))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Healthy Net Response Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (server,port) (net_response_response_time{result=\"success\"})",
     "legendFormat": "{{ server }}:{{ port }}"
    }
   ]
  },
  { "title": "Ping", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Healthy Ping Checks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(sum by (url,host) (clamp(ping_result_code,0,1) == 0)) or vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unhealthy Ping Checks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(sum by (url,host) (clamp(ping_result_code,0,1) == 1)) or vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mean Ping Response Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(http_response_response_time{result=\"success\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Checks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count(sum by (url,host) (clamp(ping_result_code,0,1))) or vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ping Uptime",
   "type": "table",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - ((sum_over_time(sum by (url,host) (clamp(ping_result_code,0,1))[$__range])) / (sum_over_time(sum by (url,host) (clamp(ping_result_code,1,1))[$__range])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (url,host) (clamp(ping_result_code,0,1))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Healthy Ping Response Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (url) (ping_average_response_ms{})",
     "legendFormat": "{{url}}"
    }
   ]
  },
  { "title": "TLS Certificates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Cert Leaf Status",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(x509_cert_enddate{type=\"leaf\"} - time())",
     "legendFormat": "{{common_name}}"
    }
   ]
  },
  {
   "title": "Intermediate Cert Status",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(x509_cert_enddate{type=\"intermediate\"} - time())",
     "legendFormat": "{{common_name}}"
    }
   ]
  },
  {
   "title": "Root Cert Status",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(x509_cert_enddate{type=\"root\"} - time())",
     "legendFormat": "{{common_name}}"
    }
   ]
  }
 ]
}