{
 "title": "Blackbox Anomaly Detection",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "metrics",
    "query": "victoriametrics-metrics-datasource"
   },
   {
    "name": "http_endpoint",
    "query": {
     "query": "label_values(anomaly_score{for=\"http_blackbox\"},server)"
    }
   },
   {
    "name": "dns_domain",
    "query": {
     "query": "label_values(dns_query_query_time_ms,domain)"
    }
   },
   {
    "name": "dns_server",
    "query": {
     "query": "label_values(dns_query_query_time_ms{domain=\"$dns_domain\"},server)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Anomaly Scores and Expected Values",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum without(__name__) (anomaly_score{for=~\"http_blackbox|dns_blackbox\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum without (__name__) (yhat{for=~\"http_blackbox|dns_blackbox\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum without (__name__) (yhat_upper{for=~\"http_blackbox|dns_blackbox\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum without (__name__) (yhat_lower{for=~\"http_blackbox|dns_blackbox\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum without (__name__,db) (http_response_response_time{for=~\"http_blackbox|dns_blackbox\"} * 1000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum without (__name__,ip_0,ip_1,ip_2,ip_3,db,record_type) (dns_query_query_time_ms{for=~\"http_blackbox|dns_blackbox\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "HTTP Anomalies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "HTTP Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "http_response_response_time{server=\"$http_endpoint\"} * 1000",
     "legendFormat": "actual"
    },
    {
     "expr": "yhat{server=\"$http_endpoint\"}",
     "legendFormat": "expected"
    },
    {
     "expr": "yhat_upper{server=\"$http_endpoint\"}",
     "legendFormat": "upper"
    },
    {
     "expr": "yhat_lower{server=\"$http_endpoint\"}",
     "legendFormat": "lower"
    }
   ]
  },
  {
   "title": "HTTP Anomaly Score",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "anomaly_score{server=\"$http_endpoint\"}",
     "legendFormat": "anomaly score"
    }
   ]
  },
  { "title": "DNS Anomalies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "DNS Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (server,domain) (dns_query_query_time_ms{server=\"$dns_server\",domain=\"$dns_domain\"})",
     "legendFormat": "actual"
    },
    {
     "expr": "yhat{server=\"$dns_server\"}",
     "legendFormat": "expected"
    },
    {
     "expr": "yhat_upper{server=\"$dns_server\"}",
     "legendFormat": "upper"
    },
    {
     "expr": "yhat_lower{server=\"$dns_server\"}",
     "legendFormat": "lower"
    }
   ]
  },
  {
   "title": "DNS Anomaly Score",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "anomaly_score{server=\"$dns_server\"}",
     "legendFormat": "{{server}}"
    }
   ]
  }
 ]
}