{
 "title": "Blackbox Performance",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "metrics", "query": "prometheus" },
   {
    "name": "http_host",
    "label": "HTTP Host",
    "query": {
     "query": "label_values(http_response_response_time,host)"
    }
   },
   {
    "name": "http_server",
    "label": "HTTP Server",
    "query": {
     "query": "label_values(http_response_response_time{host=\"$http_host\"},server)"
    }
   },
   {
    "name": "dns_host",
    "label": "DNS Host",
    "query": {
     "query": "label_values(dns_query_query_time_ms,host)"
    }
   },
   {
    "name": "dns_server",
    "label": "HTTP Server",
    "query": {
     "query": "label_values(dns_query_query_time_ms{host=\"$dns_host\"},domain)"
    }
   },
   {
    "name": "net_response_host",
    "label": "Net Response Host",
    "query": {
     "query": "label_values(net_response_response_time,host)"
    }
   },
   {
    "name": "net_response_server",
    "label": "Net Response Server",
    "query": {
     "query": "label_values(net_response_response_time{host=\"$net_response_host\"},server)"
    }
   },
   {
    "name": "net_response_port",
    "label": "Net Response Port",
    "query": {
     "query": "label_values(net_response_response_time{host=\"$net_response_host\", server=\"$net_response_server\"},port)"
    }
   },
   {
    "name": "ping_host",
    "label": "Ping Host",
    "query": {
     "query": "label_values(ping_average_response_ms,host)"
    }
   },
   {
    "name": "ping_server",
    "label": "Ping Server",
    "query": {
     "query": "label_values(ping_average_response_ms{host=\"$ping_host\"},url)"
    }
   }
  ]
 },
 "panels": [
  { "title": "HTTP Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP Peformance",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max_over_time(quantile_over_time(.5,http_response_response_time{result=\"success\"}[1h])[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "max_over_time(quantile_over_time(.90,http_response_response_time{result=\"success\"}[1h])[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "max_over_time(quantile_over_time(.99,http_response_response_time{result=\"success\"}[1h])[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP perfomance Over Time",
   "type": "candlestick",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile_over_time(.5,http_response_response_time{host=\"$http_host\",server=\"$http_server\"}[5m])",
     "legendFormat": "p50"
    },
    {
     "expr": "min_over_time(http_response_response_time{host=\"$http_host\",server=\"$http_server\"}[5m])",
     "legendFormat": "min"
    },
    {
     "expr": "max_over_time(http_response_response_time{host=\"$http_host\",server=\"$http_server\"}[5m])",
     "legendFormat": "max"
    },
    {
     "expr": "quantile_over_time(.90,http_response_response_time{host=\"$http_host\",server=\"$http_server\"}[5m])",
     "legendFormat": "p90"
    }
   ]
  },
  { "title": "DNS Query Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "DNS Query Performance",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max_over_time(quantile_over_time(.5,dns_query_query_time_ms{result=\"success\"}[1h])[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "max_over_time(quantile_over_time(.90,dns_query_query_time_ms{result=\"success\"}[1h])[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "max_over_time(quantile_over_time(.99,dns_query_query_time_ms{result=\"success\"}[1h])[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DNS Query Performance Over Time",
   "type": "candlestick",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "quantile_over_time(.5,dns_query_query_time_ms{host=\"$dns_host\",domain=\"$dns_server\"}[5m])",
     "legendFormat": "p50"
    },
    {
     "expr": "min_over_time(dns_query_query_time_ms{host=\"$dns_host\",domain=\"$dns_server\"}[5m])",
     "legendFormat": "min"
    },
    {
     "expr": "max_over_time(dns_query_query_time_ms{host=\"$dns_host\",domain=\"$dns_server\"}[5m])",
     "legendFormat": "max"
    },
    {
     "expr": "quantile_over_time(.90,dns_query_query_time_ms{host=\"$dns_host\",domain=\"$dns_server\"}[5m])",
     "legendFormat": "p90"
    }
   ]
  },
  { "title": "Net Response Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Net Response Time Performance",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max_over_time(quantile_over_time(.5,net_response_response_time{result=\"success\"}[1h])[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "max_over_time(quantile_over_time(.90,net_response_response_time{result=\"success\"}[1h])[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "max_over_time(quantile_over_time(.99,net_response_response_time{result=\"success\"}[1h])[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Net Response Perfomance Over Time",
   "type": "candlestick",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile_over_time(.5,net_response_response_time{host=\"$net_response_host\",server=\"$net_response_server\",port=\"$net_response_port\"}[5m])",
     "legendFormat": "p50"
    },
    {
     "expr": "min_over_time(net_response_response_time{host=\"$net_response_host\",server=\"$net_response_server\",port=\"$net_response_port\"}[5m])",
     "legendFormat": "min"
    },
    {
     "expr": "max_over_time(net_response_response_time{host=\"$net_response_host\",server=\"$net_response_server\",port=\"$net_response_port\"}[5m])",
     "legendFormat": "max"
    },
    {
     "expr": "quantile_over_time(.90,net_response_response_time{host=\"$net_response_host\",server=\"$net_response_server\",port=\"$net_response_port\"}[5m])",
     "legendFormat": "p90"
    }
   ]
  },
  { "title": "Ping Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Ping Performance",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max_over_time(quantile_over_time(.5,ping_average_response_ms{}[1h])[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "max_over_time(quantile_over_time(.90,ping_average_response_ms{}[1h])[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "max_over_time(quantile_over_time(.99,ping_average_response_ms{}[1h])[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ping Performance Over Time",
   "type": "candlestick",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "quantile_over_time(.5,ping_average_response_ms{host=\"$ping_host\",url=\"$ping_server\"}[5m])",
     "legendFormat": "p50"
    },
    {
     "expr": "min_over_time(ping_average_response_ms{host=\"$ping_host\",url=\"$ping_server\"}[5m])",
     "legendFormat": "min"
    },
    {
     "expr": "max_over_time(ping_average_response_ms{host=\"$ping_host\",url=\"$ping_server\"}[5m])",
     "legendFormat": "max"
    },
    {
     "expr": "quantile_over_time(.90,ping_average_response_ms{host=\"$ping_host\",url=\"$ping_server\"}[5m])",
     "legendFormat": "p90"
    }
   ]
  }
 ]
}