{
 "title": "Blocky",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "metrics",
    "query": "victoriametrics-metrics-datasource"
   },
   {
    "name": "logs",
    "query": "victoriametrics-logs-datasource"
   },
   {
    "name": "host",
    "query": {
     "query": "label_values(blocky_build_info,host)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Blocky Overview",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "blocky_build_info{host=~\"$host\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(time() - blocky_last_list_group_refresh_timestamp_seconds{host=~\"$host\"}) by (host)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (host) (blocky_denylist_cache_entries{host=~\"$host\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (host) (blocky_blocking_enabled{host=~\"$host\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (host) (blocky_query_total{host=~\"$host\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (host) (increase(blocky_response_total{response_type=\"BLOCKED\",host=~\"$host\"}[$__range])) / sum by (host) (increase(blocky_query_total{host=~\"$host\"}[$__range])) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "1 - (sum by (host) (blocky_cache_entry_count{host=~\"$host\"}) / sum by (host) (increase(blocky_query_total{host=~\"$host\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "QueryLog",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "tags.appname:blocky AND tags.host:\"$host\" AND fields.msg:=\"query resolved\""
      }
     ]
    },
    {
     "title": "Raw Log",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
     "targets": [
      {
       "expr": "tags.appname:blocky AND tags.host:\"$host\""
      }
     ]
    }
   ]
  },
  {
   "title": "Query Totals",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top Clients",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "tags.appname:blocky AND tags.host:\"$host\" AND fields.response_type:!=\"\"  | stats by (fields.client_ip) count() requests",
       "legendFormat": "{{ fields.client_ip }}"
      }
     ]
    },
    {
     "title": "Top Domains",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "tags.appname:blocky AND tags.host:\"$host\" AND fields.response_type:!=\"\"| stats by (fields.question_name) count() requests"
      }
     ]
    },
    {
     "title": "Most Blocked Clients",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "tags.appname:blocky AND tags.host:\"$host\" AND fields.response_type:=\"BLOCKED\" | stats by (fields.client_ip) count() requests",
       "legendFormat": "{{ fields.client_ip }}"
      }
     ]
    },
    {
     "title": "Most Blocks Domains",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "tags.appname:blocky AND tags.host:\"$host\" AND fields.response_type:!=\"\" | stats by (fields.question_name) count() requests",
       "legendFormat": "{{ fields.question_name }}"
      }
     ]
    },
    {
     "title": "Query by type",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sort_desc(sum by (type) (ceil(increase(blocky_query_total{host=~\"$host\"}[$__range]))))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Query per Client",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(sum by (client) (ceil(increase(blocky_query_total{host=~\"$host\"}[$__range]))))",
       "legendFormat": "{{client}}"
      }
     ]
    },
    {
     "title": "Denylist by group",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(blocky_denylist_cache_entries{host=~\"$host\"}) by (group,host)",
       "legendFormat": "{{ host }} - {{ group }}"
      }
     ]
    },
    {
     "title": "Response Reasons",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(sum by (reason) (ceil(increase(blocky_response_total{host=~\"$host\"}[$__range]))))",
       "legendFormat": "{{reason}}"
      }
     ]
    },
    {
     "title": "Response Type",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sort_desc(sum by (response_type) (ceil(increase(blocky_response_total{host=~\"$host\"}[$__range]))))",
       "legendFormat": "{{response_type}}"
      }
     ]
    },
    {
     "title": "Response status",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(sum by (response_code) (ceil(increase(blocky_response_total{host=~\"$host\"}[$__range]))))",
       "legendFormat": "{{response_code}}"
      }
     ]
    }
   ]
  },
  { "title": "Query Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Response times",
   "type": "timeseries",
   "description": "Average query response time for all query types",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(blocky_request_duration_seconds_bucket{}[$__rate_interval])) by (le,host))",
     "legendFormat": "{{host}} - p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(blocky_request_duration_seconds_bucket{}[$__rate_interval])) by (le,host))",
     "legendFormat": "{{host}} - p50"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (host) (rate(blocky_query_total{host=~\"$host\"}[5m]))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Cache Hit rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(blocky_cache_hits_total{host=~\"$host\"}[$__range])) by (host) / (sum(increase(blocky_cache_hits_total{host=~\"$host\"}[$__range])) by (host) + sum(increase(blocky_cache_misses_total{host=~\"$host\"}[$__range])) by (host))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Cached Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (host) (rate(blocky_cache_hits_total{host=~\"$host\"}[5m]))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Cache Entries Count",
   "type": "timeseries",
   "description": "Number of entries in the cache. Shows the last value",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum by (host) (blocky_cache_entries{host=~\"$host\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Request rate per client",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (client) (rate(blocky_query_total{host=~\"$host\"}[5m]))",
     "legendFormat": "{{client}}"
    }
   ]
  },
  {
   "title": "request duration (upstream)",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum(increase(blocky_request_duration_seconds_bucket{host=~\"$host\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Error count",
   "type": "timeseries",
   "description": "Number of occured errors",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(blocky_error_total{host=~\"$host\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Prefetching",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Prefetch domain count",
     "type": "timeseries",
     "description": "Amount of unique domains in the prefetched cache",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 734 },
     "targets": [
      {
       "expr": "sum by (host) (blocky_prefetch_domain_name_cache_entries{host=~\"$host\"})",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Prefetch Hit ratio",
     "type": "timeseries",
     "description": "How many of cached entries were prefetched automatically",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 734 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (host) (increase(blocky_prefetch_hits_total{host=~\"$host\"}[$__range])) / (sum by (host) (increase(blocky_cache_hits_total{host=~\"$host\"}[$__range])))",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Prefetch count",
     "type": "timeseries",
     "description": "Amount of performed DNS queries to prefetch cached queries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 744 },
     "targets": [
      {
       "expr": "ceil(sum by (host) (increase(blocky_prefetch_hits_total{host=~\"$host\"}[$__range])))",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Prefetch rate per min",
     "type": "timeseries",
     "description": "Amount of prefetch queries per minute",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 744 },
     "targets": [
      {
       "expr": "sum by (host) (rate(blocky_prefetch_hits_total{host=~\"$host\"}[5m])) * 60",
       "legendFormat": "{{host}}"
      }
     ]
    }
   ]
  }
 ]
}