{
 "title": "Caddy",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Metrics", "query": "prometheus" },
   { "name": "Loki", "query": "loki" },
   {
    "name": "path",
    "query": {}
   },
   {
    "name": "host",
    "query": {
     "query": "label_values(prometheus_caddy_reverse_proxy_upstreams_healthy,host)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count_over_time({host=\"$host\"}[1m])",
     "legendFormat": "All {{ path }}"
    },
    {
     "expr": "count_over_time({host=\"$host\"} |~ `status=\"4\\d\\d\"|status=\"5\\d\\d\"` [1m])",
     "legendFormat": "Error {{ path }}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({path=\"$path\"} |~ `status=\"4\\d\\d\"|status=\"5\\d\\d\"` [$__range]) / count_over_time({path=~\"$path\"}[$__range])"
    }
   ]
  },
  {
   "title": "Reqeusts by Status Code",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{path=~\"$path\"}"
    }
   ]
  },
  {
   "title": "reqeusts by status code",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{path=~\"$path\"}"
    }
   ]
  },
  {
   "title": "Reqeusts by HTTP Version",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{path=~\"$path\"}"
    }
   ]
  },
  {
   "title": "Top IP",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{path=~\"$path\"}"
    }
   ]
  },
  {
   "title": "GeoIP",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{path=~\"$path\"}"
    }
   ]
  },
  { "title": "Origin Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Health Checks",
   "type": "status-history",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "prometheus_caddy_reverse_proxy_upstreams_healthy{host=\"$host\"}",
     "legendFormat": "{{upstream}}"
    }
   ]
  },
  {
   "title": "Health Checks",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "prometheus_caddy_reverse_proxy_upstreams_healthy{host=\"$host\"}",
     "legendFormat": "{{upstream}}"
    }
   ]
  },
  { "title": "Geoip", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "GeoIP",
   "type": "geomap",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{path=~\"$path\"}"
    }
   ]
  }
 ]
}