{
 "title": "Crowdsec",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "label_values({path=\"/var/log/crowdsec.log\"},host)"
   },
   { "name": "logs", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "Attack World Map",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 0 },
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(count_over_time({path=~`.*crowdsec.log`} | logfmt | ban_length=\"4h\" [$__interval])) by (country_code)",
     "legendFormat": "{{country_code}}"
    }
   ]
  },
  {
   "title": "Behaviors",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({path=~`.*crowdsec.log`} | logfmt | ban_length=\"4h\" [$__interval])) by (behavior)",
     "legendFormat": "{{behavior}}"
    }
   ]
  },
  {
   "title": "Top ISPs",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({path=~`.*crowdsec.log`} | logfmt | ban_length=\"4h\" [$__interval])) by (asn) > 5",
     "legendFormat": "{{asn}}"
    }
   ]
  },
  {
   "title": "Ban Log",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{path=~`.*crowdsec.log`} | logfmt | ban_length=\"4h\""
    }
   ]
  }
 ]
}