{
 "title": "Docker",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "metrics", "query": "prometheus" },
   { "name": "logs", "query": "loki" },
   {
    "name": "host",
    "query": {
     "query": "label_values(docker_n_containers{},host)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Percent",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - cpu_usage_idle{host=\"$host\",db=\"linux\"}"
    }
   ]
  },
  {
   "title": "Percent Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mem_used_percent{db=\"linux\",host=\"$host\"}"
    }
   ]
  },
  {
   "title": "diskio",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "(diskio_read_bytes{host=\"$host\",db=\"linux\"} + diskio_read_bytes{host=\"$host\",db=\"linux\"})/ 1000000",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "container CPU usage",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "docker_container_cpu_usage_percent{host=\"$host\"}",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "container memory usage",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "docker_container_mem_usage_percent{host=\"$host\"}",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "DiskIO in Megabytes",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "docker_container_blkio_io_service_bytes_recursive_total{host=\"$host\"} / 1000000",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "container CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "docker_container_cpu_usage_percent{host=\"$host\"}",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "single container memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "docker_container_mem_usage_percent{host=\"$host\"}",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Container DiskIO in Megabytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "deriv(docker_container_blkio_io_service_bytes_recursive_total{host=\"$host\"}) / 1000000",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Mbit received",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "docker_container_net_rx_bytes{host=\"$host\"}/125000",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Mbit Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "deriv(docker_container_net_tx_bytes{host=\"$host\"}/125000)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Mbit sent",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "docker_container_net_tx_bytes{host=\"$host\"}/125000",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Mbit Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "deriv(docker_container_net_rx_bytes{host=\"$host\"}/125000)",
     "legendFormat": "{{container_name}}"
    }
   ]
  }
 ]
}