{
 "title": "Shiftmon FreeIPA",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "logs",
    "query": "victoriametrics-logs-datasource"
   },
   {
    "name": "metrics",
    "query": "victoriametrics-metrics-datasource"
   },
   {
    "name": "host",
    "query": {
     "query": "tags.path:~\"/var/log/dirsrv/slapd-.*/access\""
    }
   }
  ]
 },
 "panels": [
  { "title": "Healthchecks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Healthy Checks",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 3 }
   ]
  },
  {
   "title": "Unhealthy Checks",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    { "panelId": 4 }
   ]
  },
  {
   "title": "IPA Healthchecks",
   "type": "table",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 1 },
   "targets": [
    { "panelId": 3 }
   ]
  },
  {
   "title": "IPA Healthchecks Verbose",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "(tags.host:$host) AND name:=\"freeipa_healthcheck\""
    }
   ]
  },
  {
   "title": "Unhealthy Check Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "(tags.host:$host) AND name:=\"freeipa_healthcheck\" AND fields.result:!=\"SUCCESS\""
    }
   ]
  },
  { "title": "KDC Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "KDC logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "tags.path:=\"/var/log/krb5kdc.log\" AND (tag.host:$host)"
    }
   ]
  },
  { "title": "Slapd", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "SlapD Access Log",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "tags.path:~\"/var/log/dirsrv/slapd-.*/access\" AND (tags.host:$host)"
    }
   ]
  },
  {
   "title": "Slapd Error Log",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "tags.path:~\"/var/log/dirsrv/slapd-.*/access\" AND (tags.host:$host)"
    }
   ]
  }
 ]
}