{
 "title": "Internal Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "logs", "query": "loki" },
   { "name": "metrics", "query": "prometheus" },
   {
    "name": "host",
    "query": {
     "query": "label_values(loki_ingester_checkpoint_logged_bytes_total_counter{},host)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cardinality",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Highest Cardinality Series",
     "type": "table",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "topk(10, count by (__name__) ({__name__=~\".*\"}))"
      }
     ]
    },
    {
     "title": "Highest Cardinality Hosts",
     "type": "table",
     "gridPos": { "h": 12, "w": 6, "x": 8, "y": 1 },
     "targets": [
      {
       "expr": "topk(10, count by (host) ({host=~\".*\"}))",
       "legendFormat": "{{host}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Victoriametrics Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Victoriametrics Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vm_app_version_value{host=\"$host\"}"
    }
   ]
  },
  {
   "title": "Max Active Metrics Series",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "vm_cache_entries_value{host=\"$host\",type=\"storage/hour_metric_ids\"}"
    }
   ]
  },
  {
   "title": "Average Ingestion Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "samples/sec" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "panelId": 39 }
   ]
  },
  {
   "title": "Victoriametrics Disk usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vm_data_size_bytes_value{host=\"$host\"})"
    }
   ]
  },
  {
   "title": "Free Disk Space",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vm_free_disk_space_bytes_value{host=\"$host\"} - vm_free_disk_space_limit_bytes_value{host=\"$host\"}"
    }
   ]
  },
  {
   "title": "Slow Inserts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 16, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(vm_slow_row_inserts_total_value{host=\"$host\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Slow Queries",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(vm_slow_queries_total_value{host=\"$host\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Victoriametric Total Datapoints",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vm_rows_value{host=\"$host\",type!=\"indexdb\"})"
    }
   ]
  },
  {
   "title": "Metric Query Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "max(vm_request_duration_seconds_value{host=\"$host\"}) by (path, quantile) > 0",
     "legendFormat": "{{quantile}} ({{path}})"
    }
   ]
  },
  {
   "title": "Metric Ingestion Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "samples/sec" } },
   "targets": [
    {
     "expr": "rate(vm_rows_inserted_total_value{host=\"$host\"}) > 0",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "New Series Creation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 7 },
   "targets": [
    {
     "expr": "increase(vm_new_timeseries_created_total_value{host=\"$host\"}[$__interval])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "VictoriaMetrics Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "{appname=\"victoria-metrics-prod\",host=\"$host\"} | logfmt"
    }
   ]
  },
  {
   "title": "Loki Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Loki Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "loki_build_info_gauge{host=\"$host\"}"
    }
   ]
  },
  {
   "title": "Mean Discarded Log Streams",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "panelId": 18 }
   ]
  },
  {
   "title": "Mean active Log streams",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "panelId": 17 }
   ]
  },
  {
   "title": "max log ingest rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "rate(loki_distributor_bytes_received_total_counter{host=\"$host\"}[$__range])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Logs Ingested Since restart",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "loki_distributor_bytes_received_total_counter{host=\"$host\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Logs Stored Since Restart",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "loki_chunk_store_stored_chunk_bytes_total_counter{host=\"$host\"}"
    }
   ]
  },
  {
   "title": "log ingest latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "loki_ingester_checkpoint_duration_seconds_0.99{host=\"$host\"}",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "loki_ingester_checkpoint_duration_seconds_0.5{host=\"$host\"}",
     "legendFormat": "50th percentile"
    }
   ]
  },
  {
   "title": "Log Ingestion Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "Active Log streams",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "loki_store_series_total_counter{host=\"$host\",status=\"matched\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Discarded Log Streams",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 36 },
   "targets": [
    {
     "expr": "increase(loki_discarded_samples_total_counter{host=\"$host\"})"
    }
   ]
  },
  {
   "title": "Loki Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "{appname=\"loki-linux-amd64\",host=\"$host\"}",
     "maxLines": 200
    }
   ]
  }
 ]
}