{
 "title": "Kea DHCPv4",
 "tags": [
  "kea",
  "stork",
  "dhcp4"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "metrics",
    "query": "victoriametrics-metrics-datasource"
   },
   {
    "name": "logs",
    "query": "victoriametrics-logs-datasource"
   },
   {
    "name": "host",
    "label": "host",
    "query": {
     "query": "label_values(storkagent_promkeaexporter_uptime_seconds,host)"
    }
   },
   {
    "name": "subnet",
    "label": "Subnet",
    "query": {
     "query": "label_values(kea_dhcp4_addresses_assigned_total{host=~\"$host\"},subnet)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Number of dropped Received packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(kea_dhcp4_packets_received_total{operation=\"drop\", host=~\"$host\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Actual number of DORA packets",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "kea_dhcp4_packets_received_total{host=~\"$host\"} > 0",
     "legendFormat": "{{ host }} - {{operation }}"
    }
   ]
  },
  {
   "title": "Total number of addresses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kea_dhcp4_addresses_total{host=~\"$host\", subnet=~\"$subnet\"}",
     "legendFormat": "subnet \"{{subnet}}\" on {{instance}}"
    }
   ]
  },
  {
   "title": "Number of addresses assigned",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kea_dhcp4_addresses_assigned_total{host=~\"$host\", subnet=~\"$subnet\"}",
     "legendFormat": "subnet \"{{subnet}}\" on {{instance}}"
    }
   ]
  },
  {
   "title": "Number of addresses declined",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(kea_dhcp4_addresses_declined_total{host=~\"$host\", subnet=~\"$subnet\"})",
     "legendFormat": "{{host}} - {{subnet}}"
    }
   ]
  },
  {
   "title": "Number of addresses reclaimed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(kea_dhcp4_addresses_reclaimed_total{host=~\"$host\", subnet=~\"$subnet\"}[10m])",
     "legendFormat": "subnet \"{{subnet}}\" on {{instance}}"
    }
   ]
  },
  {
   "title": "Number of sent NAKs ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(kea_dhcp4_packets_sent_total{operation=\"nak\", host=~\"$host\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Number of addresses declined-reclaimed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(kea_dhcp4_addresses_declined_reclaimed_total{host=~\"$host\",subnet=~\"$subnet\"})",
     "legendFormat": "{{host}} - {{ subnet }}"
    }
   ]
  },
  {
   "title": "DHCP server Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "tags.appname:kea-dhcp4 OR tags.appname:kea-dhcp6 AND (tags.host:$host)"
    }
   ]
  },
  {
   "title": "Stork Agent Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "tags.appname:stork-agent AND (tags.host:$host)"
    }
   ]
  },
  {
   "title": "Kea Agent Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "tags.appname:kea-ctrl-agent (tags.host:$host)"
    }
   ]
  }
 ]
}