{
 "title": "Libvirt",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "metrics", "query": "prometheus" },
   { "name": "logs", "query": "loki" },
   {
    "name": "hypervisor",
    "label": "hypervisor",
    "query": {
     "query": "label_values(libvirt_cpu_system{},host)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_n_cpus{host=\"$hypervisor\"}"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mem_total{host=\"$hypervisor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(100 - mem_used_percent{host=\"$hypervisor\"}) * mem_total{host=\"$hypervisor\"} / 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Guests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(libvirt_vcpu_total_current{host=\"$hypervisor\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "uptime in days",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(system_uptime{host=\"$hypervisor\"}) / 86400"
    }
   ]
  },
  {
   "title": "Host Memory Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mem_used_percent{host=\"$hypervisor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hypervisor CPU %",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 - cpu_usage_idle{host=\"$hypervisor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Size",
   "type": "stat",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "disk_total{host=\"$hypervisor\"}",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Disk Available",
   "type": "stat",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "disk_free{host=\"$hypervisor\"}",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Host Diskio",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(diskio_read_bytes{host=\"$hypervisor\"} + diskio_write_bytes{host=\"$hypervisor\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Host Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "deriv(net_bytes_sent{host=\"$hypervisor\"} + net_bytes_recv{host=\"$hypervisor\",interface!~\"macvtap.*|vnet.*|podman.*|veth.*\"})",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  { "title": "Guest Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": " Guest Bandwidth Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "deriv(libvirt_net_tx_bytes{host=\"$hypervisor\"} + libvirt_net_rx_bytes{host=\"$hypervisor\"})",
     "legendFormat": "{{domain_name}}"
    }
   ]
  },
  {
   "title": " Guest CPU time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "deriv(libvirt_vcpu_time{host=\"$hypervisor\"})",
     "legendFormat": "{{domain_name}}"
    }
   ]
  },
  {
   "title": "Guest Resource Usage",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "libvirt_balloon_current{host=\"$hypervisor\"} * 1024",
     "legendFormat": "__auto"
    },
    {
     "expr": "libvirt_block_capacity{host=\"$hypervisor\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "libvirt_state_state{host=\"$hypervisor\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "libvirt_vcpu_total_current{host=\"$hypervisor\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}