{
 "title": "Linux Metrics",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "metrics", "query": "prometheus" },
   { "name": "logs", "query": "loki" },
   {
    "name": "host",
    "query": {
     "query": "label_values(cpu_usage_idle{db=\"linux\"},host)"
    }
   },
   {
    "name": "smart_device",
    "label": "SMART Device",
    "query": {
     "query": "label_values(smart_attribute_raw_value{host=\"$host\"},device)"
    }
   },
   {
    "name": "systemd_unit",
    "label": "Systemd Unit",
    "query": {
     "query": "label_values(systemd_units_active_code{host=\"$host\"},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Mean CPU %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 - cpu_usage_idle{host=\"$host\",db=\"linux\"}"
    }
   ]
  },
  {
   "title": "Mean Memory %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mem_used_percent{db=\"linux\",host=\"$host\"}"
    }
   ]
  },
  {
   "title": "CPU Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_n_cpus{host=\"$host\",db=\"linux\"}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mem_total{host=\"$host\",db=\"linux\"}"
    }
   ]
  },
  {
   "title": "uptime in days",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(system_uptime{host=\"$host\",db=\"linux\"}) / 86400"
    }
   ]
  },
  {
   "title": "Mean IOwait",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_usage_iowait{host=\"$host\",db=\"linux\"}"
    }
   ]
  },
  {
   "title": "OS Version",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "{__name=\"exec_os_release\",host=\"$host\"} | logfmt | pattern `NAME=<OS>` | pattern `Version=<Version>`",
     "resolution": 1
    }
   ]
  },
  {
   "title": "Failed Services",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "expr": "systemd_units_active_code{db=\"linux\",host=\"$host\",active=\"failed\"}"
    }
   ]
  },
  {
   "title": "CPU Percent",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "100 - cpu_usage_idle{host=\"$host\",db=\"linux\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Memory Percent",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 5 },
   "targets": [
    {
     "expr": "mem_used_percent{db=\"linux\",host=\"$host\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Disk Used %",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(disk_used_percent{host=\"$host\",db=\"linux\"})",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Mbytes/sec received",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "deriv(net_bytes_recv{host=\"$host\",db=\"linux\"})",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "mbytes/sec sent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "deriv(net_bytes_sent{host=\"$host\",db=\"linux\"})",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "DiskIO",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(diskio_read_bytes{host=\"$host\",db=\"linux\"}) + rate(diskio_write_bytes{host=\"$host\",db=\"linux\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "SMART",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Device Overview",
     "type": "table",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 39 },
     "targets": [
      {
       "expr": "smart_device_health_ok{host=\"$host\"}"
      },
      {
       "expr": "smart_device_temp_c{host=\"$host\"}"
      }
     ]
    },
    {
     "title": "Smart Attributes",
     "type": "table",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 39 },
     "repeat": "smart_device",
     "targets": [
      {
       "expr": "smart_attribute_raw_value{host=\"$host\", device=\"$smart_device\"}"
      },
      {
       "expr": "smart_attribute_threshold{host=\"$host\", device=\"$smart_device\"}"
      }
     ]
    },
    {
     "title": "Drive Temp",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "smart_device_temp_c{host=\"$host\"}",
       "legendFormat": "{{device}} {{power}}"
      }
     ]
    },
    {
     "title": "Read Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "smart_device_read_error_rate{host=\"$host\"}",
       "legendFormat": "{{device}} {{power}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk Size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Size",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 7, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort(disk_total{host=\"$host\",db=\"linux\"})",
       "legendFormat": "{{path}}"
      }
     ]
    },
    {
     "title": "Disk Available",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 7, "x": 7, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort(disk_free{host=\"$host\",db=\"linux\"})",
       "legendFormat": "{{path}}"
      }
     ]
    },
    {
     "title": "Disk Available Over Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 10, "x": 14, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "disk_free{host=\"$host\",db=\"linux\"}",
       "legendFormat": "{{path}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Diskio",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Reads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
     "targets": [
      {
       "expr": "increase(diskio_reads{host=\"$host\", db=\"linux\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Disk Writes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
     "targets": [
      {
       "expr": "increase(diskio_writes{host=\"$host\", db=\"linux\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Disk Read Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "increase(diskio_read_bytes{host=\"$host\", db=\"linux\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Disk Write Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "increase(diskio_write_bytes{host=\"$host\", db=\"linux\"})",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Advanced CPU Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU IO Wait",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "cpu_usage_iowait{host=\"$host\",db=\"linux\"}",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "CPU User",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "cpu_usage_user{host=\"$host\",db=\"linux\"}",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "IRQ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "cpu_usage_irq{host=\"$host\",db=\"linux\"}",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Usage Nice",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "cpu_usage_nice{host=\"$host\",db=\"linux\"}",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Usage SoftIRQ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "cpu_usage_softirq{host=\"$host\",db=\"linux\"}",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Usage Steal",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "cpu_usage_steal{host=\"$host\",db=\"linux\"}",
       "legendFormat": "{{host}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Advanced Network Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Error Packets In",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "deriv(net_err_in{host=\"$host\",db=\"linux\"})",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "Error Packets In",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "deriv(net_err_in{host=\"$host\",db=\"linux\"})",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "Dropped Packets in",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "deriv(net_drop_in{host=\"$host\",db=\"linux\"})",
       "legendFormat": "{{interface}}"
      }
     ]
    },
    {
     "title": "Dropped Packets Out",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "deriv(net_drop_out{host=\"$host\",db=\"linux\"})",
       "legendFormat": "{{interface}}"
      }
     ]
    }
   ]
  },
  { "title": "Syslog and Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Service Events",
   "type": "table",
   "gridPos": { "h": 12, "w": 14, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "{appname=\"systemd\",host=\"$host\"} | pattern `<_>message=\"<service_name>: <event> <status>.\" <_>` | service_name=~\".*service|.*timer|.*mount|.*socket\""
    }
   ]
  },
  {
   "title": "Services",
   "type": "table",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 28 },
   "targets": [
    {
     "expr": "systemd_units_active_code{db=\"linux\",host=\"$host\"}"
    }
   ]
  },
  {
   "title": "Systemd Unit Logs",
   "type": "logs",
   "gridPos": { "h": 14, "w": 17, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "{appname=\"systemd\",host=\"$host\"} |~ \"$systemd_unit\" | logfmt"
    }
   ]
  },
  {
   "title": "Unit Status Over Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 40 },
   "targets": [
    {
     "expr": "systemd_units_active_code{host=\"$host\", name=\"$systemd_unit\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Status code mapping",
   "type": "text",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 47 },
   "options": {
    "content": "0 - Active\n\n1 - Reloading\n\n2 - Inactive\n\n3 - Failed\n\n4 - Activating\n\n5 - Deactivating\n"
   }
  },
  {
   "title": "syslog warning and higher",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "{severity=~\"crit|err|warning\",host=\"$host\"}"
    }
   ]
  }
 ]
}