{
 "title": "Netflow",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "metrics", "query": "prometheus" },
   { "name": "logs", "query": "loki" },
   {
    "name": "host",
    "label": "host",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Data Storage from netflow",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bytes_over_time({__name=\"netflow\",host=~\"$host\"}[$__range])"
    }
   ]
  },
  {
   "title": "Total Bandwidth",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(rate({__name=\"netflow\",host=~\"$host\"} | logfmt | unwrap bytes(in_bytes)[1s])) + sum(rate({__name=\"netflow\",host=~\"$host\"} | logfmt | unwrap bytes(out_bytes)[1s]))"
    }
   ]
  },
  {
   "title": "Number of Packets",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(rate({__name=\"netflow\",host=~\"$host\"} | logfmt | unwrap bytes(in_packets)[1s])) + sum(rate({__name=\"netflow\",host=~\"$host\"} | logfmt | unwrap bytes(out_packets)[1s]))"
    }
   ]
  },
  {
   "title": "L4 Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (protocol) (rate({__name=\"netflow\",host=~\"$host\"} | logfmt | unwrap bytes(in_bytes)[1s])) + sum by (protocol) (rate({__name=\"netflow\",host=~\"$host\"} | logfmt | unwrap bytes(out_bytes)[1s]))",
     "legendFormat": "{{ protocol }}"
    }
   ]
  },
  {
   "title": "L4 Totals",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 10 }
   ]
  },
  {
   "title": "Bandwidth Per Host",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (dst) (rate({__name=\"netflow\",host=~\"$host\"} | logfmt | unwrap bytes(in_bytes)[1s]))",
     "legendFormat": "{{ protocol }}"
    }
   ]
  },
  {
   "title": "Host Totals",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 11 }
   ]
  },
  {
   "title": "Bandwidth by Dest Port",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (dst_port) (rate({__name=\"netflow\",host=~\"$host\"} | logfmt | dst_port < 10000 | unwrap bytes(in_bytes)[1s]))",
     "legendFormat": "{{ dst_port }}"
    }
   ]
  },
  {
   "title": "Dest Port Totals",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 6 }
   ]
  },
  {
   "title": "Dest IP and Port pairings",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (dst,dst_port) (rate({__name=\"netflow\",host=~\"$host\"} | logfmt | dst_port < 10000 | unwrap bytes(in_bytes)[1s]))",
     "legendFormat": "{{ dst }}:{{ dst_port }}"
    }
   ]
  },
  {
   "title": "Dest Port Totals",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "panelId": 14 }
   ]
  }
 ]
}