{
 "title": "Nginx/Apache/HTTPD",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Metrics", "query": "prometheus" },
   { "name": "Logs", "query": "loki" },
   {
    "name": "host",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Request by Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({host=\"$host\",__name=\"tail_http_log\"} | logfmt[1m])) by (resp_code)",
     "legendFormat": "{{ resp_code }}"
    }
   ]
  },
  {
   "title": "Top IPs",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "{host=\"$host\",__name=\"tail_http_log\"} | logfmt"
    }
   ]
  },
  {
   "title": "Errors over time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(count_over_time({host=\"$host\",__name=\"tail_http_error_log\"} | logfmt[1m])) by (errorcode)",
     "legendFormat": "{{ resp_code }}"
    }
   ]
  },
  {
   "title": "Status Codes",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{host=\"$host\",__name=\"tail_http_log\"} | logfmt | resp_code >= 100"
    }
   ]
  },
  {
   "title": "Request Log",
   "type": "table",
   "gridPos": { "h": 12, "w": 19, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "{path=~\"/var/log/nginx/access.*|/var/log/httpd/access.*\",host=\"$host\"} | logfmt"
    }
   ]
  },
  {
   "title": "Top User Agents",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "{host=\"$host\",path=~\"/var/log/nginx/.*|/var/log/httpd.*\"} | logfmt"
    }
   ]
  },
  {
   "title": "top 10 endpoints",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "{host=\"$host\",path=~\"/var/log/nginx/.*|/var/log/httpd.*\"} | logfmt"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "table",
   "gridPos": { "h": 10, "w": 19, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "{path=~\"/var/log/nginx/error.*|/var/log/httpd/error.*\",host=\"$host\"} | logfmt"
    }
   ]
  },
  {
   "title": "4XX and 5XX Requests",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "{host=\"$host\",__name=\"tail_http_log\"} | logfmt | resp_code >= 400"
    }
   ]
  }
 ]
}