{
 "title": "NtopNG",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "metrics", "query": "prometheus" },
   { "name": "logs", "query": "loki" },
   {
    "name": "host",
    "query": {
     "query": "label_values(host:ndpi_bytes_rcvd{db=\"$db\"},host)"
    }
   },
   {
    "name": "db",
    "query": {
     "query": "label_values(iface:ndpi_bytes,db)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Categories by Bandwith",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (protocol) (rate(iface:ndpi_bytes{db=\"$db\"}))",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Categories by Bandwith",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (protocol) (increase(iface:ndpi_bytes{db=\"$db\"}[$__range]))",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Host Bandwidth Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (host) (rate(host:ndpi_bytes_rcvd{db=\"$db\"}) + rate(host:ndpi_bytes_sent{db=\"$db\"}))",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Host Bandwidth Usage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (host) (increase(host:ndpi_bytes_rcvd{db=\"$db\"}) + increase(host:ndpi_bytes_sent{db=\"$db\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Host App Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (protocol) (rate(host:ndpi_bytes_rcvd{host=\"$host\",db=\"$db\"}) + rate(host:ndpi_bytes_sent{host=\"$host\",db=\"$db\"}))",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Host App Usage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (protocol) (increase(host:ndpi_bytes_rcvd{host=\"$host\",db=\"$db\"}) + increase(host:ndpi_bytes_sent{host=\"$host\",db=\"$db\"}))",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "L4 Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (l4proto) (increase(iface:l4protos_bytes{db=\"$db\"}))",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "L4 bandwidth usage",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (l4proto) (increase(iface:l4protos_bytes{db=\"$db\"}))",
     "legendFormat": "{{iface}}"
    }
   ]
  }
 ]
}