{
 "title": "NUT/UPSD",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "metrics",
    "query": "victoriametrics-metrics-datasource"
   },
   {
    "name": "logs",
    "query": "victoriametrics-logs-datasource"
   },
   {
    "name": "host",
    "query": {
     "query": "label_values(upsd_load_percent,host)"
    }
   },
   {
    "name": "ups",
    "query": {
     "query": "label_values(upsd_load_percent{host=~\"$host\"},ups_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "UPS Overview",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (host,ups_name,ups_status) (upsd_load_percent{host=~\"$host\",ups_name=~\"$ups\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (host,ups_name,ups_status) (upsd_time_left_ns{host=~\"$host\",ups_name=~\"$ups\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (host,ups_name,ups_status) (upsd_ups_power_nominal{host=~\"$host\",ups_name=~\"$ups\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (host,ups_name,ups_status) (upsd_battery_charge_percent{host=~\"$host\",ups_name=~\"$ups\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (host,ups_name,ups_status) (upsd_input_frequency{host=~\"$host\",ups_name=~\"$ups\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (host,ups_name,ups_status) (upsd_input_voltage{host=~\"$host\",ups_name=~\"$ups\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "UPS Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Utilization Percent Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "upsd_load_percent{}",
     "legendFormat": "{{host}} {{ups_name}} {{model}}"
    }
   ]
  },
  {
   "title": "Battery Charged Percent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "upsd_battery_charge_percent{host=~\"$host\",ups_name=~\"$ups\"}",
     "legendFormat": "{{host}} {{ups_name}} {{model}}"
    }
   ]
  },
  {
   "title": "Battery Time Available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "upsd_time_left_ns{host=~\"$host\",ups_name=~\"$ups\"}",
     "legendFormat": "{{host}} {{ups_name}} {{model}}"
    }
   ]
  },
  {
   "title": "Input Power Frequency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "upsd_input_frequency{host=~\"$host\",ups_name=~\"$ups\"}",
     "legendFormat": "{{host}} {{ups_name}} {{model}}"
    }
   ]
  },
  {
   "title": "Input Voltage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "upsd_input_voltage{host=~\"$host\",ups_name=~\"$ups\"}",
     "legendFormat": "{{host}} {{ups_name}} {{model}}"
    }
   ]
  },
  {
   "title": "Output Voltage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "upsd_output_voltage{host=~\"$host\",ups_name=~\"$ups\"}",
     "legendFormat": "{{host}} {{ups_name}} {{model}}"
    }
   ]
  },
  { "title": "Specs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "UPS Details",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "targets": [
    {
     "expr": "last_over_time(upsd_ups_power_nominal{host=~\"$host\",ups_name=~\"$ups\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UPS Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "UPSD/NUT Logs",
     "type": "logs",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "(tags.host:$host) AND (tags.appname:~\"ups.*|nut.*\")"
      }
     ]
    }
   ]
  }
 ]
}