{
 "title": "OPNSense Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": {
     "query": "label_values(cpu_usage_idle{db=\"opnsense\"},host)"
    }
   },
   { "name": "metrics", "query": "prometheus" },
   { "name": "logs", "query": "loki" },
   {
    "name": "interface",
    "query": {
     "query": "label_values(net_bytes_sent{db=\"opnsense\",host=\"$host\"},interface)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Mean CPU %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - cpu_usage_idle{host=\"$host\",db=\"opnsense\",cpu=\"cpu-total\"}"
    }
   ]
  },
  {
   "title": "Percent Memory",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mem_used_percent{db=\"opnsense\",host=\"$host\"}"
    }
   ]
  },
  {
   "title": "CPU Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_n_cpus{host=\"$host\",db=\"opnsense\"}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mem_total{host=\"$host\",db=\"opnsense\"}"
    }
   ]
  },
  {
   "title": "uptime in days",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(system_uptime{host=\"$host\",db=\"opnsense\"}) / 86400"
    }
   ]
  },
  {
   "title": "OS Version",
   "type": "table",
   "gridPos": { "h": 6, "w": 3, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "{host=\"$host\",__name=\"exec\"} |~ \"OPNsense\""
    }
   ]
  },
  {
   "title": "States Limited",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pf_state_limit{host=\"$host\",db=\"opnsense\"}"
    }
   ]
  },
  {
   "title": "CPU Percent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "100 - cpu_usage_idle{host=\"$host\",db=\"opnsense\",cpu=\"cpu-total\"}",
     "legendFormat": "{{hsot}}"
    }
   ]
  },
  {
   "title": "Percent Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "mem_used_percent{db=\"opnsense\",host=\"$host\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "disk usage",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 7, "x": 13, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "disk_used_percent{host=\"$host\",db=\"opnsense\",fstype!=\"devfs\",path!~`/var/.*|/usr/.*|/zroot|/tmp`}",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Disk Available",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "disk_free{host=\"$host\",db=\"opnsense\",fstype!=\"devfs\",path!~`/var/.*|/usr/.*|/zroot|/tmp`}",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Inbound Traffic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "deriv(net_bytes_recv{host=\"$host\",db=\"opnsense\"})",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Outbound Traffic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "deriv(net_bytes_sent{host=\"$host\",db=\"opnsense\"})",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Current PF States",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 13, "y": 13 },
   "targets": [
    { "expr": "pf_entries{}", "legendFormat": "states" }
   ]
  },
  {
   "title": "Disk Size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "disk_total{host=\"$host\",db=\"opnsense\",fstype!=\"devfs\",path!~`/var/.*|/usr/.*|/zroot|/tmp`}",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "top outbound talkers",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "topk(20,sum(count_over_time({__name=\"syslog\",hostname=\"$host\",appname=\"filterlog\"} |~ \".*$interface.*out.*\" | pattern `<_>,,,<rule_id>,<interface>,<reason>,<action>,<direction>,<version>,<tos>,,<ttl>,<id>,<offset>,<ipflags>,<protonum>,<protocol>,<length>,<source_ip>,<dest_ip>,`[1m])) by (source_ip))",
     "legendFormat": "{{ source_ip }}"
    }
   ]
  },
  {
   "title": "inbound talkers",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "topk(5,sum(count_over_time({__name=\"syslog\",hostname=\"$host\",appname=\"filterlog\"} |~ \".*$interface.*in.*\" | pattern `<_>,,,<rule_id>,<interface>,<reason>,<action>,<direction>,<version>,<tos>,,<ttl>,<id>,<offset>,<ipflags>,<protonum>,<protocol>,<length>,<source_ip>,<dest_ip>,`[1m])) by (source_ip))",
     "legendFormat": "{{ source_ip }}"
    }
   ]
  },
  {
   "title": "Dest ports",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "topk(15,sum(count_over_time({__name=\"syslog\",hostname=\"$host\",appname=\"filterlog\"} |~ \".*$interface.*out.*\" | pattern `<_>,,,<rule_id>,<interface>,<reason>,<action>,<direction>,<version>,<tos>,,<ttl>,<id>,<offset>,<ipflags>,<protonum>,<protocol>,<length>,<source_ip>,<dest_ip>,<source_port>,<dest_port>,`[1m])) by (dest_port))",
     "legendFormat": "{{ dest_port }}"
    }
   ]
  },
  {
   "title": "Suricata alerts",
   "type": "logs",
   "gridPos": { "h": 10, "w": 21, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "{__name=\"suricata\",host=\"$host\"}| logfmt"
    }
   ]
  },
  {
   "title": "Suricata alerts",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 21, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate({__name=\"suricata\", host=\"$host\"} [$__range]))"
    }
   ]
  },
  {
   "title": "Queried Domains",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name=\"resolver\",host=\"$host\"} | logfmt"
    }
   ]
  },
  {
   "title": "Querying IPs",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 5, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name=\"resolver\",host=\"$host\"} | logfmt"
    }
   ]
  },
  {
   "title": "unbound logs",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "{__name=\"resolver\",host=\"$host\"} | logfmt"
    }
   ]
  }
 ]
}