{
 "title": "Proxmox Backup Server",
 "tags": [ "proxmox" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "metrics",
    "query": "victoriametrics-metrics-datasource"
   },
   {
    "name": "logs",
    "query": "victoriametrics-logs-datasource"
   },
   {
    "name": "host",
    "query": {
     "query": "label_values(blockstat_write_ios,host)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Host Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Host Metrics",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "targets": [
    {
     "expr": "system_uptime{host=~\"$host\"}",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "cpustat_cpu{host=~\"$host\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "memory_memused{host=~\"$host\"} / memory_memtotal{host=~\"$host\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "memory_memtotal{host=~\"$host\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "cpustat_cpu_count{host=~\"$host\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(blockstat_read_bytes{host=~\"$host\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(blockstat_write_bytes{host=~\"$host\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Storage Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Node Storage",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "blockstat_used{host=~\"$host\"} "
    },
    {
     "expr": "blockstat_total{host=~\"$host\"}"
    },
    {
     "expr": "blockstat_used{host=~\"$host\"} / blockstat_total{host=~\"$host\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "blockstat_total{host=~\"$host\"} - blockstat_used{host=~\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "iowait",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cpustat_iowait_percent{host=~\"$host\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(nics_receive{host=~\"$host\"})",
     "legendFormat": "{{host}} - {{ instance }} - receive"
    },
    {
     "expr": "rate(nics_send{host=~\"$host\"})",
     "legendFormat": "{{host}} - {{ instance }} - send"
    }
   ]
  },
  {
   "title": "Diskio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(blockstat_read_bytes{host=~\"$host\"})",
     "legendFormat": "{{host}} - read"
    },
    {
     "expr": "rate(blockstat_write_bytes{host=~\"$host\"})",
     "legendFormat": "{{host}} - write"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "PBS Logs",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "tags.appname:\"pbs\" AND tags.hostname:~\"$host\""
    }
   ]
  },
  {
   "title": "Other Syslog",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "direction": "backward",
     "expr": "tags.hostname:~\"$host\""
    }
   ]
  }
 ]
}