{
 "title": "Proxmox",
 "tags": [ "proxmox" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "metrics",
    "query": "victoriametrics-metrics-datasource"
   },
   {
    "name": "logs",
    "query": "victoriametrics-logs-datasource"
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(cpustat_idle{object=\"nodes\"},host)"
    }
   },
   {
    "name": "guest",
    "query": {
     "query": "label_values(system_cpu{object=~\"lxc|qemu\", nodename=~\"$node\"},host)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "targets": [
    {
     "expr": "system_uptime{object=~\"nodes\",host=~\"$node\"}",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "cpustat_cpu{object=\"nodes\",host=~\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "memory_memused{object=\"nodes\",host=~\"$node\"} / memory_memtotal{object=\"nodes\",host=~\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "memory_memtotal{object=\"nodes\",host=~\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "cpustat_cpus{object=\"nodes\",host=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Storage",
   "type": "table",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "system_used{object=\"storages\",nodename=~\"$node\"} "
    },
    {
     "expr": "system_total{object=\"storages\",nodename=~\"$node\"}"
    },
    {
     "expr": "system_used{object=\"storages\",nodename=~\"$node\"} / system_total{object=\"storages\",nodename=~\"$node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "system_total{object=\"storages\",nodename=~\"$node\"} - system_used{object=\"storages\",nodename=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Guest Resources",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "system_disk{object=~\"qemu|lxc\",nodename=~\"$node.*\"}"
    },
    {
     "expr": "system_maxmem{object=~\"lxc|qemu\",nodename=~\"$node.*\"}"
    },
    {
     "expr": "system_cpus{nodename=~\"$node.*\"}"
    },
    {
     "expr": "system_mem{object=~\"lxc|qemu\",nodename=~\"$node.*\"}"
    },
    {
     "expr": "system_cpu{nodename=~\"$node.*\",object=~\"lxc|qemu\"}"
    },
    {
     "expr": "system_mem{object=~\"lxc|qemu\",nodename=~\"$node.*\"} / system_maxmem{object=~\"lxc|qemu\",nodename=~\"$node.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Guest network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "rate(system_netin{object=~\"lxc|qemu\",nodename=~\"$node\",host=~\"$guest\"}[$__rate_interval])",
     "legendFormat": "{{host}}_in"
    },
    {
     "expr": "rate(system_netout{object=~\"lxc|qemu\",nodename=~\"$node\",host=~\"$guest\"}[$__rate_interval])",
     "legendFormat": "{{host}}_out"
    }
   ]
  },
  {
   "title": "iowait",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 16 },
   "targets": [
    {
     "expr": "cpustat_wait{host=~\"$node\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Guest Diskio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(system_diskread{nodename=~\"$node\",host=~\"$guest\"})",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "irate(system_diskwrite{nodename=~\"$node\",host=~\"$guest\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "PVE Log",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "tags.appname:\"pve-tasks\" AND tags.hostname:\"$node\""
    }
   ]
  }
 ]
}