{
 "title": "SNMP",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Datasource",
    "query": "victoriametrics-metrics-datasource"
   },
   { "name": "device", "query": { "query": "label_values(agent_host)" } }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Device Overview",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "snmp_sysUptime{agent_host=~\"$device\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(sum_over_time(rate(ifTable_ifInOctets{agent_host=~\"$device\"})[$__range])) by (agent_host) + sum(sum_over_time(rate(ifTable_ifOutOctets{agent_host=~\"$device\"})[$__range])) by (agent_host)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Interface Status: $device",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "repeat": "device",
   "collapsed": true,
   "panels": [
    {
     "title": "Interface Overview",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "rate(ifTable_ifInErrors{agent_host=~\"$device\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum (ifTable_ifSpeed{agent_host=~\"$device\"}) without (name)",
       "legendFormat": "__auto"
      },
      {
       "expr": "rate(ifTable_ifInOctets{agent_host=~\"$device\"}) + rate(ifTable_ifOutOctets{agent_host=~\"$device\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum_over_time(rate(ifTable_ifInOctets{agent_host=~\"$device\"})[$__range]) + sum_over_time(rate(ifTable_ifOutOctets{agent_host=~\"$device\"})[$__range])",
       "legendFormat": "__auto"
      },
      {
       "expr": "label_del(ifTable_ifOperStatus{agent_host=~\"$device\"},\"__name__\")",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Bandwidth Per Interface",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(ifTable_ifOutOctets{agent_host=~\"$device\"}[5m]) != 0",
       "legendFormat": "{{ifDescr}} - OUT"
      },
      {
       "expr": "rate(ifTable_ifInOctets{agent_host=~\"$device\"}[5m]) * -1 != 0",
       "legendFormat": "{{ifDescr}} - IN"
      }
     ]
    },
    {
     "title": "Unicast Packets Per second",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(ifTable_ifOutUcastPkts{agent_host=~\"$device\"}[5m]) != 0",
       "legendFormat": "{{ifDescr}} - OUT"
      },
      {
       "expr": "(rate(ifTable_ifInUcastPkts{agent_host=~\"$device\"}[5m]) * -1) != 0",
       "legendFormat": "{{ifDescr}} - IN"
      }
     ]
    }
   ]
  }
 ]
}