{
 "title": "Suricata",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "metrics",
    "query": "victoriametrics-metrics-datasource"
   },
   {
    "name": "logs",
    "query": "victoriametrics-logs-datasource"
   },
   { "name": "host", "query": { "query": "tags.appname:suricata" } },
   {
    "name": "fields",
    "query": "fields.app_proto,fields.proto,fields.src_ip,fields.src_port,fields.dest_ip,fields.dest_port"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Overview",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "tags.host:~\"$host\" AND tags.appname:suricata | stats by (tags.host) sum(fields.flow_bytes_toserver) as \"Bytes to Server\""
    },
    {
     "expr": "tags.host:~\"$host\" AND tags.appname:suricata | stats by (tags.host) sum(fields.flow_bytes_toclient) as \"Bytes to Client\""
    },
    {
     "expr": "tags.host:~\"$host\" AND tags.appname:suricata | stats by (tags.host) sum(fields.flow_pkts_toserver) as \"Packets to Server\""
    },
    {
     "expr": "tags.host:~\"$host\" AND tags.appname:suricata | stats by (tags.host) sum(fields.flow_pkts_toclient) as \"Packets to to Client\""
    },
    {
     "expr": "tags.host:~\"$host\" AND tags.appname:suricata | stats by (tags.host) count_uniq(fields.flow_id) as \"Flows\""
    }
   ]
  },
  {
   "title": "bandwidth by $fields",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "repeat": "fields",
   "collapsed": true,
   "panels": [
    {
     "title": "Bytes to Client",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 16, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "tags.host:~\"$host\" AND tags.appname:suricata AND $fields:!=\"\" | stats by (tags.host,$fields) rate_sum(fields.flow_bytes_toclient)",
       "legendFormat": "{{ $fields }}"
      }
     ]
    },
    {
     "title": "Bytes to Client",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tags.host:~\"$host\" AND tags.appname:suricata AND $fields:!=\"\" | stats by (tags.host,$fields) sum(fields.flow_bytes_toclient)",
       "legendFormat": "{{ $fields  }}"
      }
     ]
    },
    {
     "title": "Packets to Client",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 16, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "tags.host:~\"$host\" AND tags.appname:suricata AND $fields:!=\"\" | stats by (tags.host,$fields) rate_sum(fields.flow_pkts_toclient)",
       "legendFormat": "{{ $fields }}"
      }
     ]
    },
    {
     "title": "Packets to Client",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tags.host:~\"$host\" AND tags.appname:suricata AND $fields:!=\"\" | stats by (tags.host,$fields) sum(fields.flow_pkts_toclient)",
       "legendFormat": "{{ $fields  }}"
      }
     ]
    },
    {
     "title": "Bytes to Server",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 16, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "tags.host:~\"$host\" AND tags.appname:suricata AND $fields:!=\"\" | stats by (tags.host,$fields) rate_sum(fields.flow_bytes_toserver)",
       "legendFormat": "{{ $fields }}"
      }
     ]
    },
    {
     "title": "Bytes to Server",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tags.host:~\"$host\" AND tags.appname:suricata AND $fields:!=\"\" | stats by (tags.host,$fields) sum(fields.flow_bytes_toserver)",
       "legendFormat": "{{ $fields  }}"
      }
     ]
    },
    {
     "title": "Packets to Client",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 16, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "tags.host:~\"$host\" AND tags.appname:suricata AND $fields:!=\"\" | stats by (tags.host,$fields) rate_sum(fields.flow_pkts_toserver)",
       "legendFormat": "{{ $fields }}"
      }
     ]
    },
    {
     "title": "Packets to Client",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tags.host:~\"$host\" AND tags.appname:suricata AND $fields:!=\"\" | stats by (tags.host,$fields) sum(fields.flow_pkts_toserver)",
       "legendFormat": "{{ $fields  }}"
      }
     ]
    }
   ]
  }
 ]
}