{
 "title": "Sysmon",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "logs",
    "query": "victoriametrics-logs-datasource"
   },
   {
    "name": "host",
    "query": {
     "query": "tags.Channel:Microsoft-Windows-Sysmon/Operational"
    }
   }
  ]
 },
 "panels": [
  { "title": "All Sysmon Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Events by Type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "(tags.host:$host) AND tags.Channel:Microsoft-Windows-Sysmon/Operational | stats by (fields.TaskText) count() events"
    }
   ]
  },
  {
   "title": "Sysmon Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 1 },
   "targets": [
    {
     "expr": "(tags.host:$host) AND tags.Channel:Microsoft-Windows-Sysmon/Operational | stats by (fields.TaskText,_time:1m) count() \" \"",
     "legendFormat": "{{fields.TaskText}}"
    }
   ]
  },
  {
   "title": "All Sysmon Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "(tags.host:$host) AND tags.Channel:Microsoft-Windows-Sysmon/Operational"
    }
   ]
  },
  {
   "title": "Registry Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Registry Events",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "(tags.host:$host) AND tags.Channel:Microsoft-Windows-Sysmon/Operational AND fields.Task:13"
      }
     ]
    },
    {
     "title": "Regeistry Events by Type",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 207 },
     "targets": [
      {
       "expr": "(tags.host:$host) AND tags.Channel:Microsoft-Windows-Sysmon/Operational AND fields.Task:\"13\"| stats by (fields.TaskText,_time:1m) count() \" \"",
       "legendFormat": "{{fields.TaskText}}"
      }
     ]
    },
    {
     "title": "Registry Events Per User",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 216 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "(tags.host:$host) AND tags.Channel:Microsoft-Windows-Sysmon/Operational AND fields.Task:\"13\"| stats by (fields.Data_User) count() \" \"",
       "legendFormat": "{{fields.Data_User}}"
      }
     ]
    },
    {
     "title": "Registry Events per Image",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 216 },
     "targets": [
      {
       "expr": "(tags.host:$host) AND tags.Channel:Microsoft-Windows-Sysmon/Operational AND fields.Task:\"13\"| stats by (fields.Data_User,_time:1m) count() \" \"",
       "legendFormat": "{{fields.Data_User}}"
      }
     ]
    },
    {
     "title": "Registry Events Per Image",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 225 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "(tags.host:$host) AND tags.Channel:Microsoft-Windows-Sysmon/Operational AND fields.Task:\"13\"| stats by (fields.Data_Image) count() \" \"",
       "legendFormat": "{{fields.Data_Image}}"
      }
     ]
    },
    {
     "title": "Registry Events per Image",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 225 },
     "targets": [
      {
       "expr": "(tags.host:$host) AND tags.Channel:Microsoft-Windows-Sysmon/Operational AND fields.Task:\"13\"| stats by (fields.Data_Image,_time:1m) count() \" \""
      }
     ]
    }
   ]
  },
  {
   "title": "File Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "File Events",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "(tags.host:$host) AND tags.Channel:Microsoft-Windows-Sysmon/Operational AND fields.Task:in(11,2,15,23,26)"
      }
     ]
    },
    {
     "title": "File Events",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 140 },
     "targets": [
      {
       "expr": "(tags.host:$host) AND tags.Channel:Microsoft-Windows-Sysmon/Operational AND fields.Task:in(11,2,15,23,26) | stats by (fields.TaskText,_time:1m) count() \" \""
      }
     ]
    },
    {
     "title": "Registry Events Per Image",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 149 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "(tags.host:$host) AND tags.Channel:Microsoft-Windows-Sysmon/Operational AND fields.Task:in(11,2,15,23,26)| stats by (fields.Data_Image) count() \" \""
      }
     ]
    },
    {
     "title": "Registry Events Per Image",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 149 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "(tags.host:$host) AND tags.Channel:Microsoft-Windows-Sysmon/Operational AND fields.Task:in(11,2,15,23,26)| stats by (fields.TaskText) count() \" \""
      }
     ]
    },
    {
     "title": "Registry Events Per Image",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 149 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "(tags.host:$host) AND tags.Channel:Microsoft-Windows-Sysmon/Operational AND fields.Task:in(11,2,15,23,26)| stats by (fields.Data_User) count() \" \""
      }
     ]
    },
    {
     "title": "Registry Events per Image",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 158 },
     "targets": [
      {
       "expr": "(tags.host:$host) AND tags.Channel:Microsoft-Windows-Sysmon/Operational AND fields.Task:in(11,2,15,23,26)| stats by (fields.Data_Image,_time:1m) count() \" \"",
       "legendFormat": "{{fields.Data_Image}}"
      }
     ]
    },
    {
     "title": "Registry Events per Image",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 158 },
     "targets": [
      {
       "expr": "(tags.host:$host) AND tags.Channel:Microsoft-Windows-Sysmon/Operational AND fields.Task:in(11,2,15,23,26)| stats by (fields.Data_User,_time:1m) count() \" \""
      }
     ]
    }
   ]
  },
  {
   "title": "Process Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process Events",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "(tags.host:$host) AND tags.Channel:Microsoft-Windows-Sysmon/Operational AND fields.Task:in(1,5)"
      }
     ]
    },
    {
     "title": "Process Events",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 97 },
     "targets": [
      {
       "expr": "(tags.host:$host) AND tags.Channel:Microsoft-Windows-Sysmon/Operational AND fields.Task:in(1,5) | stats by (fields.TaskText,_time:1m) count() \" \"",
       "legendFormat": "{{fields.TaskText}}"
      }
     ]
    },
    {
     "title": "Process Events Per User",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "(tags.host:$host) AND tags.Channel:Microsoft-Windows-Sysmon/Operational AND fields.Task:in(1,5)| stats by (fields.Data_User) count() \" \""
      }
     ]
    },
    {
     "title": "Process Events Per User",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 106 },
     "targets": [
      {
       "expr": "(tags.host:$host) AND tags.Channel:Microsoft-Windows-Sysmon/Operational AND fields.Task:in(1,5) | stats by (fields.Data_User,_time:1m) count() \" \"",
       "legendFormat": "{{fields.Data_User}}"
      }
     ]
    },
    {
     "title": "Process Events Per Image",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "(tags.host:$host) AND tags.Channel:Microsoft-Windows-Sysmon/Operational AND fields.Task:in(1,5)| stats by (fields.Data_Image) count() \" \""
      }
     ]
    },
    {
     "title": "Process Events Per Image",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 115 },
     "targets": [
      {
       "expr": "(tags.host:$host) AND tags.Channel:Microsoft-Windows-Sysmon/Operational AND fields.Task:in(1,5) | stats by (fields.Data_Image,_time:1m) count() \" \"",
       "legendFormat": "{{fields.Data_Image}}"
      }
     ]
    },
    {
     "title": "Process Events Per Starting Folder",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 124 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "(tags.host:$host) AND tags.Channel:Microsoft-Windows-Sysmon/Operational AND fields.Task:in(1,5)| stats by (fields.Data_CurrentDirectory) count() \" \""
      }
     ]
    },
    {
     "title": "Process Events Per Starting Folder",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 124 },
     "targets": [
      {
       "expr": "(tags.host:$host) AND tags.Channel:Microsoft-Windows-Sysmon/Operational AND fields.Task:in(1,5) | stats by (fields.Data_CurrentDirectory,_time:1m) count() \" \"",
       "legendFormat": "{{fields.Data_CurrentDirectory}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "File Events",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "(tags.host:$host) AND tags.Channel:Microsoft-Windows-Sysmon/Operational AND fields.Task:in(3)"
      }
     ]
    },
    {
     "title": "Network Conntections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 65 },
     "targets": [
      {
       "expr": "(tags.host:$host) AND tags.Channel:Microsoft-Windows-Sysmon/Operational AND fields.Task:3 | stats by (tags.host,fields.TaskText,_time:1m) count() \" \"",
       "legendFormat": "{{tags.host}} - {{fields.TaskText}}"
      }
     ]
    },
    {
     "title": "Network Conntections Per Process",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 73 },
     "targets": [
      {
       "expr": "(tags.host:$host) AND tags.Channel:Microsoft-Windows-Sysmon/Operational AND fields.Task:3 | stats by (tags.host,fields.Data_Image,_time:1m) count() \" \""
      }
     ]
    },
    {
     "title": "Connections by User",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "(tags.host:$host) AND tags.Channel:Microsoft-Windows-Sysmon/Operational AND fields.Task:3 | stats by (fields.Data_User) count() events"
      }
     ]
    },
    {
     "title": "Connections by Destination Port",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "(tags.host:$host) AND tags.Channel:Microsoft-Windows-Sysmon/Operational AND fields.Task:3 | stats by (fields.Data_DestinationPort) count() events"
      }
     ]
    },
    {
     "title": "Connections Per Process",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "(tags.host:$host) AND tags.Channel:Microsoft-Windows-Sysmon/Operational AND fields.Task:3 | stats by (fields.Data_Image) count() events"
      }
     ]
    }
   ]
  },
  { "title": "DNS Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "File Events",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "(tags.host:$host) AND tags.Channel:Microsoft-Windows-Sysmon/Operational AND fields.Task:in(22)"
    }
   ]
  },
  {
   "title": "Dns Lookups per Domain",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "(tags.host:$host) AND tags.Channel:Microsoft-Windows-Sysmon/Operational AND fields.Task:in(22) | stats by (_time:1m,tags.host) count() \"Queries\"",
     "legendFormat": "{{tags.host}}"
    }
   ]
  },
  {
   "title": "Dns Lookups per Domain",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "(tags.host:$host) AND tags.Channel:Microsoft-Windows-Sysmon/Operational AND fields.Task:in(22) | stats by (fields.Data_QueryName,_time:1m) count() \" \"",
     "legendFormat": "{{fields.Data_QueryName}}"
    }
   ]
  },
  {
   "title": "Registry Events Per Image",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "(tags.host:$host) AND tags.Channel:Microsoft-Windows-Sysmon/Operational AND fields.Task:22| stats by (fields.Data_QueryName) count() \" \""
    }
   ]
  },
  {
   "title": "Dns Lookups per Domain",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "(tags.host:$host) AND tags.Channel:Microsoft-Windows-Sysmon/Operational AND fields.Task:22 | stats by (fields.Data_Image,_time:1m) count() \" \""
    }
   ]
  },
  {
   "title": "DNS Queries Per Image",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "(tags.host:$host) AND tags.Channel:Microsoft-Windows-Sysmon/Operational AND fields.Task:22| stats by (fields.Data_Image) count() \" \"",
     "legendFormat": "{{fields.Data_Image}}"
    }
   ]
  }
 ]
}