{
 "title": "Tailscale",
 "tags": [
  "tailscale",
  "networking"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "DS",
    "label": "Datasource",
    "query": "victoriametrics-metrics-datasource"
   },
   {
    "name": "path",
    "query": {
     "query": "label_values(tailscaled_inbound_packets_total,path)"
    }
   },
   {
    "name": "host",
    "query": {
     "query": "label_values(tailscaled_inbound_packets_total,host)"
    }
   },
   {
    "name": "Logs",
    "query": "victoriametrics-logs-datasource"
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum (tailscaled_advertised_routes{host=~\"$host\"}) by (host)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(tailscaled_approved_routes{host=~\"$host\"}) by (host)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(tailscaled_inbound_bytes_total{host=~\"$host\"})) by (host)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(tailscaled_outbound_bytes_total{host=~\"$host\"})) by (host)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(tailscaled_health_messages{type=\"warning\"}) by (host)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Packets by Path",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(tailscaled_inbound_packets_total{path=~\"$path\"})",
     "legendFormat": "{{host}} - inbound - {{path}}"
    },
    {
     "expr": "rate(tailscaled_outbound_packets_total{path=~\"$path\"})",
     "legendFormat": "{{host}} - inbound - {{path}}"
    }
   ]
  },
  {
   "title": "Tailscale Logs",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "tags.appname:tailscaled AND (tags.host:$host)"
    }
   ]
  }
 ]
}