{
 "title": "Tetragon",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "metrics",
    "query": "victoriametrics-metrics-datasource"
   },
   {
    "name": "logs",
    "query": "victoriametrics-logs-datasource"
   },
   { "name": "host", "query": { "query": "tags.path:tetragon" } }
  ]
 },
 "panels": [
  { "title": "Events Per Host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Events by Host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "tags.path:tetragon AND tags.host:\"$host\" | stats by (_time:5m,tags.host) count()",
     "legendFormat": "{{tags.host}}"
    }
   ]
  },
  {
   "title": "Events by Host",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tags.path:tetragon AND tags.host:\"$host\" | stats by (tags.host) count()",
     "legendFormat": "{{tags.host}}"
    }
   ]
  },
  { "title": "Events by Type", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Events by Host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "tags.path:tetragon AND tags.host:\"$host\" | stats by (_time:5m,fields.event_type) count()",
     "legendFormat": "{{fields.event_type}}"
    }
   ]
  },
  {
   "title": "Events by Host",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tags.path:tetragon AND tags.host:\"$host\" | stats by (fields.event_type) count()",
     "legendFormat": "{{fields.event_type}}"
    }
   ]
  },
  { "title": "Executs By Auid (User ID)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Events by AUID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "tags.path:tetragon AND tags.host:\"$host\" AND fields.process_auid:!\"\"| stats by (fields.process_auid) count()",
     "legendFormat": "{{fields.process_auid}}"
    }
   ]
  },
  {
   "title": "Executions by Executable",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tags.path:tetragon AND tags.host:\"$host\" AND fields.process_auid:!\"\"| stats by (fields.process_auid) count()",
     "legendFormat": "{{fields.process_auid}}"
    }
   ]
  },
  { "title": "Events By Executable", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Executions by by Executable",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "tags.path:tetragon AND tags.host:\"$host\" AND (fields.process_binary:!=\"\" OR fields.process_binary:!=\"\") | stats by (_time:5m,fields.process_binary) count()",
     "legendFormat": "{{fields.process_binary}}"
    }
   ]
  },
  {
   "title": "Executions by Executable",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tags.path:tetragon AND tags.host:\"$host\" AND fields.process_binary:!=\"\"| stats by (fields.process_binary) count()",
     "legendFormat": "{{fields.process_binary}}"
    }
   ]
  },
  {
   "title": "Tetragon logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "New panel",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
     "targets": [
      {
       "expr": "tags.path:tetragon AND tags.host:\"$host\""
      }
     ]
    }
   ]
  }
 ]
}