{
 "title": "Traefik",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "metrics", "query": "prometheus" },
   { "name": "logs", "query": "loki" },
   {
    "name": "host",
    "query": "label_values({path=~`.*access.json`},host)"
   }
  ]
 },
 "panels": [
  {
   "title": "Request Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({path=~`.*access.json`,host=\"$host\"}[$__range])"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({path=~`.*access.json`,host=\"$host\"}[1m])"
    }
   ]
  },
  {
   "title": "Errored Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({path=~`.*access.json`,host=\"$host\"} | logfmt | DownstreamStatus >= 400[$__range]))"
    }
   ]
  },
  {
   "title": "Top 20 Endpoints",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "topk(20,sum(count_over_time({path=~`.*access.json`,host=\"$host\"} | logfmt [1m])) by (RequestPath))",
     "legendFormat": "{{  RequestPath }}"
    }
   ]
  },
  {
   "title": "Top 20 Clients",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "topk(20,sum(count_over_time({path=~`.*access.json`,host=\"$host\"} | logfmt [1m])) by (ClientHost))",
     "legendFormat": "{{  RequestPath }}"
    }
   ]
  },
  {
   "title": "Status Codes",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "topk(20,sum(count_over_time({path=~`.*access.json`,host=\"$host\"} | logfmt [1m])) by (OriginStatus))",
     "legendFormat": "{{  RequestPath }}"
    }
   ]
  },
  {
   "title": "Request by Host",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(count_over_time({path=~`.*access.json`,host=\"$host\"} | logfmt [1m])) by (RequestHost)",
     "legendFormat": "{{RequestHost}}"
    }
   ]
  },
  {
   "title": "Request by Status Code",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum(count_over_time({path=~`.*access.json`,host=\"$host\"} | logfmt [1m])) by (OriginStatus)",
     "legendFormat": "{{RequestHost}}"
    }
   ]
  },
  {
   "title": "All logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "{path=~`.*access.json`,host=\"$host\"} | logfmt"
    }
   ]
  },
  {
   "title": "Error logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "{path=~`.*access.json`,host=\"$host\"} | logfmt | DownstreamStatus >= 400"
    }
   ]
  }
 ]
}