{
 "title": "Traefik - InfluxDB",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "metrics", "query": "prometheus" },
   { "name": "logs", "query": "loki" },
   {
    "name": "host",
    "query": {
     "query": "label_values(traefik.router.requests.bytes.total_count,host)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (service,host) (rate(traefik.router.requests.total_count{host=~\"$host\"}[1m]))",
     "legendFormat": "{{service}} - {{host}}"
    }
   ]
  },
  {
   "title": "Errored Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (service,host) (rate(traefik.router.requests.total_count{host=~\"$host\",code=~\"4.*|5.*\"}[1m]))",
     "legendFormat": "{{service}} - {{host}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by (service,host) (increase(traefik.router.requests.total_count{host=~\"$host\", code=~\"4.*|5.*\"}))) / (sum by (service,host) (increase(traefik.router.requests.total_count{host=~\"$host\"})))",
     "legendFormat": "{{service}} - {{host}}"
    }
   ]
  },
  {
   "title": "Origin Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Origin Health",
     "type": "status-history",
     "gridPos": { "h": 10, "w": 19, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "traefik.service.server.up_value{host=~\"$host\"}",
       "legendFormat": "{{service}}"
      }
     ]
    },
    {
     "title": "Origin Health",
     "type": "stat",
     "gridPos": { "h": 10, "w": 5, "x": 19, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "traefik.service.server.up_value{host=~\"$host\"}",
       "legendFormat": "{{service}}"
      }
     ]
    }
   ]
  },
  { "title": "Client Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Top 20 Endpoints",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "topk(20,sum(count_over_time({path=~`.*access.json.*`,host=~\"$host.*\"} | logfmt [$__range])) by (RequestPath))",
     "legendFormat": "{{  RequestPath }}"
    }
   ]
  },
  {
   "title": "Top 20 Clients",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "topk(20,sum(count_over_time({path=~`.*access.json.*`,host=~\"$host.*\"} | logfmt [1m])) by (ClientHost))",
     "legendFormat": "{{  RequestPath }}"
    }
   ]
  },
  {
   "title": "Status Codes",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (code) (traefik.router.requests.total_count{host=~\"$host\"})",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Request by Host",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate({path=~`.*access.json.*`,host=~\"$host.*\"} | logfmt [1m])) by (RequestHost)",
     "legendFormat": "{{RequestHost}}"
    }
   ]
  },
  {
   "title": "Request by Status Code",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(traefik.router.requests.total_count{host=~\"$host\"})) by (service,code)",
     "legendFormat": "{{service}} - {{code}}"
    }
   ]
  },
  {
   "title": "All logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "{path=~`.*access.json.*`,host=~\"$host\"} | logfmt"
    }
   ]
  },
  {
   "title": "Error logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "{path=~`.*access.json.*`,host=~\"$host\"} | logfmt | DownstreamStatus =~ `4.*|5.*`"
    }
   ]
  }
 ]
}