{
 "title": "Traefik",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "metrics", "query": "prometheus" },
   { "name": "logs", "query": "loki" },
   {
    "name": "host",
    "query": {
     "query": "label_values(traefik.router.requests.total_count,host)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Request Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(traefik.router.requests.total_count{host=\"$host\"})"
    }
   ]
  },
  {
   "title": "Errored Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(traefik.router.requests.total_count{host=\"$host\",code=~\"4.*|5.*\"})"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(traefik.router.requests.total_count{host=\"$host\", code=~\"4.*|5.*\"}) / sum(traefik.router.requests.total_count{host=\"$host\"})"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "requests/min" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(traefik.router.requests.total_count{host=\"$host\"}[1m]))"
    }
   ]
  },
  {
   "title": "Errored Request Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "requests/min" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(traefik.router.requests.total_count{host=\"$host\",code=~\"4.*|5.*\"}[1m]))"
    }
   ]
  },
  { "title": "Origin Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Origin Health",
   "type": "status-history",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "traefik.service.server.up_value{host=\"$host\"}",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "Top 20 Endpoints",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "topk(20,sum(count_over_time({path=~`.*access.json`,host=~\"$host.*\"} | logfmt [$__range])) by (RequestPath))",
     "legendFormat": "{{  RequestPath }}"
    }
   ]
  },
  {
   "title": "Top 20 Clients",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "topk(20,sum(count_over_time({path=~`.*access.json`,host=~\"$host.*\"} | logfmt [1m])) by (ClientHost))",
     "legendFormat": "{{  RequestPath }}"
    }
   ]
  },
  {
   "title": "Status Codes",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (code) (traefik.router.requests.total_count{host=\"$host\"})",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Request by Host",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum(count_over_time({path=~`.*access.json`,host=~\"$host.*\"} | logfmt [1m])) by (RequestHost)",
     "legendFormat": "{{RequestHost}}"
    }
   ]
  },
  {
   "title": "Request by Status Code",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "sum by (code) (traefik.router.requests.total_count{host=\"$host\"})",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "All logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "{path=~`.*access.json`,host=~\"$host.*\"} | logfmt"
    }
   ]
  },
  {
   "title": "Error logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "{path=~`.*access.json`,host=~\"$host.*\"} | logfmt | DownstreamStatus >= 400"
    }
   ]
  }
 ]
}