{
 "title": "Uptime Kuma",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "metrics", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "{__name__=\"prometheus_monitor_status\"}",
     "legendFormat": "{{monitor_name}}"
    }
   ]
  },
  {
   "title": "Days Left On Cert",
   "type": "stat",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=\"prometheus_monitor_cert_days_remaining\"}",
     "legendFormat": "{{monitor_name}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "{__name__=\"prometheus_monitor_response_time\"} > 0",
     "legendFormat": "{{monitor_name}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "targets": [
    { "panelId": 2 }
   ]
  }
 ]
}