{
 "title": "Victoria Logs Usage",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "logs",
    "query": "victoriametrics-logs-datasource"
   },
   { "name": "metrics", "query": "prometheus" },
   { "name": "host", "query": { "query": "" } },
   {
    "name": "path",
    "query": {
     "query": "tags.path:!\"\""
    }
   },
   { "name": "appname", "query": { "query": "" } }
  ]
 },
 "panels": [
  { "title": "Stream", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "log rate by stream",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tags.host:$host AND (tags.appname:$appname OR tags.path:$path) | stats by (_time:1m,_stream) count() as messages",
     "legendFormat": "{{ _stream }}"
    }
   ]
  },
  {
   "title": "log count by stream",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "tags.host:$host AND (tags.appname:$appname OR tags.path:$path) | stats by (_time:1m,_stream) count() as messages | limit 25",
     "legendFormat": "{{ _stream }}"
    }
   ]
  },
  { "title": "Host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "log rate by host",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tags.host:$host AND (tags.appname:$appname OR tags.path:$path) | stats by (_time:1m,tags.hostname) count() as messages",
     "legendFormat": "{{tags.hostname}}"
    }
   ]
  },
  {
   "title": "log count by host",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "tags.host:$host AND (tags.appname:$appname OR tags.path:$path) | stats by (_time:1m,tags.hostname) count() as messages | limit 25",
     "legendFormat": "{{ appname }}"
    }
   ]
  },
  { "title": "File", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "log rate by path",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tags.path:$path AND tags.host:$host | stats by (_time:1m,tags.path) count() as messages",
     "legendFormat": "{{tags.path}}"
    }
   ]
  },
  {
   "title": "log count by path",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "tags.path:$path AND tags.host:$host | stats by (tags.path) count() as messages | limit 25",
     "legendFormat": "{{ tags.path }}"
    }
   ]
  },
  { "title": "Syslog", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "log rate by appname",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "name:syslog AND tags.appname:$appname AND tags.host:$host | stats by (_time:1m,tags.appname) count() as messages",
     "legendFormat": "{{tags.appname}}"
    }
   ]
  },
  {
   "title": "log count by appname",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "name:syslog AND tags.appname:$appname AND tags.hostname:$host | stats by (tags.appname) count() as messages | limit 25",
     "legendFormat": "{{ appname }}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "tags.host:$host AND (tags.path OR tags.appname:$appname)"
    }
   ]
  }
 ]
}