{
 "title": "VictoriaMetrics - vmanomaly - self-monitoring",
 "description": "Self-monitoring for VictoriaMetrics Anomaly Detection (vmanomaly) v1.18.4 or higher",
 "tags": [ "vmanomaly" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "off",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(vmanomaly_start_time_seconds, job)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(vmanomaly_start_time_seconds{job=~\"$job\"},instance)"
    }
   },
   {
    "name": "preset",
    "label": "Preset",
    "query": {
     "query": "label_values(vmanomaly_model_runs_skipped_total{job=~\"$job\", instance=~\"$instance\"},preset)"
    }
   },
   {
    "name": "scheduler_alias",
    "label": "Scheduler",
    "query": {
     "query": "label_values(vmanomaly_model_runs_skipped_total{job=~\"$job\", instance=~\"$instance\", preset=~\"$preset\"},scheduler_alias)"
    }
   },
   {
    "name": "query_key",
    "label": "Query key",
    "query": {
     "query": "label_values(vmanomaly_model_runs_skipped_total{job=~\"$job\", instance=~\"$instance\", preset=~\"$preset\", scheduler_alias=~\"$scheduler_alias\"},query_key)"
    }
   },
   {
    "name": "model_alias",
    "label": "Model Alias",
    "query": {
     "query": "label_values(vmanomaly_model_runs_skipped_total{job=~\"$job\", instance=~\"$instance\", preset=~\"$preset\", scheduler_alias=~\"$scheduler_alias\", query_key=~\"$query_key\"},model_alias)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Instance Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "description": "This table offer aggregated insights across all *selected* instances of [VictoriaMetrics Anomaly Detection](https://victoriametrics.com/products/enterprise/anomaly-detection/). <br>Only time range control the data displayed in this table.\n<br>Column description:\n- **instance**: particular `vmanomaly` instance name\n- **job**: job name that exported `vmanomaly` instance metrics (default=`vmanomaly`)\n- **version**: particular `vmanomaly` instance service [version](https://docs.victoriametrics.com/anomaly-detection/changelog/)\n- **uptime** - particular `vmanomaly` instance uptime (since its recent relaunch)\n- **RAM** - used RAM by `vmanomaly` instance process\n- **CPU** - used CPU% by `vmanomaly` instance\n- **license:exp.in** - time left to license expiration\n- **m:active**: # of active models for `vmanomaly` instance\n- **r:skipped**: # of skipped runs (`fit`, `infer`, `fit_infer`)\n- **r:errors** - # of error in runs (`fit`, `infer`, `fit_infer`)\n- **r:success** - # of successful runs (`fit`, `infer`, `fit_infer`)\n- **i/o:reads** - % of successful read requests\n- **i/o:writes** - % of successful write requests\n- **i/o:total** - % of successful I/O requests \n- **r:acc.rate** - data acceptance rate (`fit_infer`, `infer` stages), points produced/accepted\n- **conf:shard** # of [sub-configurations](https://docs.victoriametrics.com/anomaly-detection/scaling-vmanomaly/#sub-configuration) attached to that shard (if sharded mode is enabled). Replication factor > 1 can increase this number\n- **conf:total** # of total [sub-configurations](https://docs.victoriametrics.com/anomaly-detection/scaling-vmanomaly/#sub-configuration) available for sharding after [global config](https://docs.victoriametrics.com/anomaly-detection/scaling-vmanomaly/#global-configuration) split (if sharded mode is enabled)\n- **conf:%** percentage of [sub-configurations](https://docs.victoriametrics.com/anomaly-detection/scaling-vmanomaly/#sub-configuration) attached to that shard (if sharded mode is enabled, otherwise 100%). Replication factor > 1 can increase this number",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "This table provides aggregated insights across all *selected* instances of [VictoriaMetrics Anomaly Detection](https://victoriametrics.com/products/enterprise/anomaly-detection/). <br> Only the time range, `job` and `instance` filters applies to the displayed data. Hover over the (i) icon for column descriptions.\n"
   }
  },
  {
   "title": "Overview",
   "type": "table",
   "description": "This table offer aggregated insights across all *selected* instances of [VictoriaMetrics Anomaly Detection](https://victoriametrics.com/products/enterprise/anomaly-detection/). <br>Only time range control the data displayed in this table.\n<br>Column description:\n- **instance**: particular `vmanomaly` instance name\n- **job**: job name that exported `vmanomaly` instance metrics (default=`vmanomaly`)\n- **version**: particular `vmanomaly` instance service [version](https://docs.victoriametrics.com/anomaly-detection/changelog/)\n- **uptime** - particular `vmanomaly` instance uptime (since its recent relaunch)\n- **RAM** - used RAM by `vmanomaly` instance process\n- **CPU** - used CPU% by `vmanomaly` instance\n- **license:exp.in** - time left to license expiration\n- **m:active**: # of active models for `vmanomaly` instance\n- **r:skipped**: # of skipped runs (`fit`, `infer`, `fit_infer`)\n- **r:errors** - # of error in runs (`fit`, `infer`, `fit_infer`)\n- **r:success** - # of successful runs (`fit`, `infer`, `fit_infer`)\n- **i/o:reads** - % of successful read requests\n- **i/o:writes** - % of successful write requests\n- **i/o:total** - % of successful I/O requests \n- **r:acc.rate** - data acceptance rate (`fit_infer`, `infer` stages), points produced/accepted\n- **conf:shard** # of [sub-configurations](https://docs.victoriametrics.com/anomaly-detection/scaling-vmanomaly/#sub-configuration) attached to that shard (if sharded mode is enabled). Replication factor > 1 can increase this number\n- **conf:total** # of total [sub-configurations](https://docs.victoriametrics.com/anomaly-detection/scaling-vmanomaly/#sub-configuration) available for sharding after [global config](https://docs.victoriametrics.com/anomaly-detection/scaling-vmanomaly/#global-configuration) split (if sharded mode is enabled)\n- **conf:%** percentage of [sub-configurations](https://docs.victoriametrics.com/anomaly-detection/scaling-vmanomaly/#sub-configuration) attached to that shard (if sharded mode is enabled, otherwise 100%). Replication factor > 1 can increase this number",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "group by (job,instance,version) (vmanomaly_version_info{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (job,instance) (increase(vmanomaly_model_runs_skipped_total{job=~\"$job\",instance=~\"$instance\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (job,instance) (increase(vmanomaly_model_run_errors_total{job=~\"$job\",instance=~\"$instance\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (job,instance) (increase(vmanomaly_model_runs_total{job=~\"$job\",instance=~\"$instance\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "time() - (sum by (job,instance) (vmanomaly_start_time_seconds{job=~\"$job\",instance=~\"$instance\"}))",
     "legendFormat": "__auto"
    },
    {
     "expr": "vm_license_expires_at{job=~\"$job\",instance=~\"$instance\"} - time()",
     "legendFormat": "__auto"
    },
    {
     "expr": "with (\n  valid = {__name__=\"vmanomaly_reader_responses_total\", instance=~\"$instance\", job=~\"$job\", code=~\"2..\"},\n  all = {__name__=\"vmanomaly_reader_responses_total\", instance=~\"$instance\", job=~\"$job\"}\n)\n(sum(increase(valid[$__range])) by (job, instance)) / (sum(increase(all[$__range])) by (job, instance))",
     "legendFormat": "__auto"
    },
    {
     "expr": "with (\n  valid = {__name__=\"vmanomaly_writer_responses_total\", instance=~\"$instance\", job=~\"$job\", code=~\"2..\"},\n  all = {__name__=\"vmanomaly_writer_responses_total\", instance=~\"$instance\", job=~\"$job\"}\n)\n(sum(increase(valid[$__range])) by (job, instance)) / (sum(increase(all[$__range])) by (job, instance))",
     "legendFormat": "__auto"
    },
    {
     "expr": "with (\n  valid = {__name__=~'vmanomaly_(writer|reader)_responses_total', instance=~\"$instance\", job=~\"$job\", code=~\"2..\"},\n  all = {__name__=~'vmanomaly_(writer|reader)_responses_total', instance=~\"$instance\", job=~\"$job\"}\n)\n(sum(increase(valid[$__range])) by (job, instance)) / (sum(increase(all[$__range])) by (job, instance))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(vmanomaly_models_active{job=~\"$job\", instance=~\"$instance\"}) by (job, instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "with (\n  acc = {__name__=~'vmanomaly_model_datapoints_accepted_total', instance=~\"$instance\", job=~\"$job\", stage=~\".*infer\"},\n  prod = {__name__=~'vmanomaly_model_datapoints_produced_total', instance=~\"$instance\", job=~\"$job\", stage=~\".*infer\"}\n)\n(sum(increase({acc}[$__range])) by (job, instance)) / (sum(increase({prod}[$__range])) by (job, instance))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(job,instance) (process_resident_memory_bytes{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (job,instance) (rate(process_cpu_seconds_total{job=~\"$job\",instance=~\"$instance\"})) / sum by (job,instance) (vmanomaly_cpu_cores_available{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(job,instance) (process_resident_memory_bytes{job=~\"$job\",instance=~\"$instance\"}) / sum by(job,instance) (vmanomaly_available_memory_bytes{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (job, instance) (vmanomaly_config_entities{job=~\"$job\", instance=~\"$instance\", scope=\"shard\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (job, instance) (vmanomaly_config_entities{job=~\"$job\", instance=~\"$instance\", scope=\"total\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (job, instance) (vmanomaly_config_entities{job=~\"$job\", instance=~\"$instance\", scope=\"shard\"}) / sum by (job, instance) (vmanomaly_config_entities{job=~\"$job\", instance=~\"$instance\", scope=\"total\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Global Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "type": "text",
   "description": "These panels offer **aggregated** insights across all *selected* instances of [VictoriaMetrics Anomaly Detection](https://victoriametrics.com/products/enterprise/anomaly-detection/). <br>Dashboard filters and time range control the data displayed in these panels. Refer to the links section for metrics and log descriptions.",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 13 },
   "options": {
    "content": "These panels offer aggregated insights across all *selected* instances of [VictoriaMetrics Anomaly Detection](https://victoriametrics.com/products/enterprise/anomaly-detection/). <br>Dashboard filters and time range control the data displayed in these panels. Refer to the links section for metrics and log descriptions."
   }
  },
  {
   "type": "text",
   "description": "Model runs statistics",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 15 },
   "options": {
    "content": "#### Model Runs Statistics\n\nHover over visualization's (i) icon for the descriptions. Note: [Rolling models](https://docs.victoriametrics.com/anomaly-detection/components/models/#rolling-models) make combined `fit_infer` call, [non-rolling](https://docs.victoriametrics.com/anomaly-detection/components/models/#non-rolling-models) models make separate `fit` and `infer` calls."
   }
  },
  {
   "title": "# Unique entities",
   "type": "stat",
   "description": "Number of unique entities being currently active for model instances of class `model_alias` currently available for inference for the `query_key` query, within the specified scheduler `scheduler_alias`, in the vmanomaly service running in `preset` mode.\n</br>Too many entities may slow down the system.",
   "gridPos": { "h": 12, "w": 3, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vmanomaly_models_active{instance=~\"$instance\", job=~\"$job\", preset=~\"$preset\", scheduler_alias=~\"$scheduler_alias\", query_key=~\"$query_key\",model_alias=~\"$model_alias\"})",
     "legendFormat": "active models"
    },
    {
     "expr": "with (\n  uniq_q_cnt = {__name__=~\"vmanomaly_model_runs_total\", job=~\"$job\",instance=~\"$instance\",preset=~\"$preset\",scheduler_alias=~\"$scheduler_alias\",model_alias=~\"$model_alias\",query_key=~\"$query_key\"}\n)\n\ncount(count by (query_key) ({uniq_q_cnt}))\n",
     "legendFormat": "queries"
    },
    {
     "expr": "with (\n  uniq_q_cnt = {__name__=~\"vmanomaly_model_runs_total\", job=~\"$job\",instance=~\"$instance\",preset=~\"$preset\",scheduler_alias=~\"$scheduler_alias\",model_alias=~\"$model_alias\",query_key=~\"$query_key\"}\n)\n\ncount(count by (instance) ({uniq_q_cnt}))\n",
     "legendFormat": "instances"
    },
    {
     "expr": "with (\n  uniq_q_cnt = {__name__=~\"vmanomaly_model_runs_total\", job=~\"$job\",instance=~\"$instance\",preset=~\"$preset\",scheduler_alias=~\"$scheduler_alias\",model_alias=~\"$model_alias\",query_key=~\"$query_key\"}\n)\n\ncount(count by (job) ({uniq_q_cnt}))",
     "legendFormat": "jobs"
    }
   ]
  },
  {
   "title": "Runs: Successful",
   "type": "stat",
   "description": "How many successful `stage` (`fit`, `infer`, `fit_infer`) runs occurred for models of class `model_alias` based on results from the `query_key` query, within the specified scheduler `scheduler_alias`, in the `vmanomaly` service running in `preset` mode.",
   "gridPos": { "h": 4, "w": 5, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "with (\n  f = {__name__=\"vmanomaly_model_runs_total\", job=~\"$job\",instance=~\"$instance\",preset=~\"$preset\", scheduler_alias=~\"$scheduler_alias\", model_alias=~\"$model_alias\",query_key=~\"$query_key\"}\n)\nsum(increase(f[$__range])) by (stage)",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "Runs: Errors",
   "type": "stat",
   "description": "The number of times model runs (of class `model_alias`) failed due to internal service errors during the `stage` (`fit`, `infer`, `fit_infer`), based on results from the `query_key` query, within the specified scheduler `scheduler_alias`, in the `vmanomaly` service running in `preset` mode.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (stage) (increase(vmanomaly_model_run_errors_total{job=~\"$job\",instance=~\"$instance\",preset=~\"$preset\",scheduler_alias=~\"$scheduler_alias\",model_alias=~\"$model_alias\",query_key=~\"$query_key\"}[$__range]))",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "Runs: Skipped",
   "type": "stat",
   "description": "The number of times model runs (of class `model_alias`) were skipped in expected situations (e.g., no data for fitting/inference, or no new data to infer on) during the `stage` (`fit`, `infer`, `fit_infer`), based on results from the `query_key` query, within the specified scheduler `scheduler_alias`, in the `vmanomaly` service running in `preset` mode.",
   "gridPos": { "h": 4, "w": 5, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (stage) (increase(vmanomaly_model_runs_skipped_total{job=~\"$job\",instance=~\"$instance\",preset=~\"$preset\",scheduler_alias=~\"$scheduler_alias\",model_alias=~\"$model_alias\",query_key=~\"$query_key\"}[$__range]))",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "Runs: Problematic %",
   "type": "stat",
   "description": "Percentage of skipped/errors in total model runs",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "with (\n  err = {__name__=~\"vmanomaly_model_run(s_skipped_total|_errors_total)\", job=~\"$job\",instance=~\"$instance\",preset=~\"$preset\",scheduler_alias=~\"$scheduler_alias\",model_alias=~\"$model_alias\",query_key=~\"$query_key\"},\n  tot = {__name__=~\"vmanomaly_model_run(s_total|s_skipped_total|_errors_total)\", job=~\"$job\",instance=~\"$instance\",preset=~\"$preset\",scheduler_alias=~\"$scheduler_alias\",model_alias=~\"$model_alias\",query_key=~\"$query_key\"}\n)\n\n(sum(increase({err}[$__range])) by (stage) ) / (sum (increase({tot}[$__range])) by (stage) )",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "Avg. Run Time, by Stage",
   "type": "stat",
   "description": "Average (weighted) CPU time required to complete particular stage (`fit`, `infer`, `fit_infer`) given applied filters. Simply put, this shows the time spent processing each *individual model instance* (noting that usually more than 1 instance of each model type may be active concurrently).",
   "gridPos": { "h": 4, "w": 6, "x": 3, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "WITH (f = {job=~\"$job\", instance=~\"$instance\", preset=~\"$preset\", scheduler_alias=~\"$scheduler_alias\", query_key=~\"$query_key\", model_alias=~\"$model_alias\"})\n(sum(vmanomaly_model_run_duration_seconds_sum{f}) by (stage) ) / (sum(vmanomaly_model_run_duration_seconds_count{f}) by (stage))",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "Avg. Run Time, by Stage (99% percentile)",
   "type": "stat",
   "description": "99% percentile of CPU time required to complete particular stage (`fit`, `infer`, `fit_infer`) given applied filters. Simply put, this shows the time spent processing each *individual model instance* (noting that usually more than 1 instance of each model type may be active concurrently).",
   "gridPos": { "h": 4, "w": 7, "x": 9, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(vmanomaly_model_run_duration_seconds_bucket{job=~\"$job\", instance=~\"$instance\", preset=~\"$preset\", scheduler_alias=~\"$scheduler_alias\", query_alias=~\"$query_key\", model_alias=~\"$model_alias\"}[$__range])) by (stage, le))",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "Avg. Total Run Time, by Stage",
   "type": "stat",
   "description": "Avg. **Total** time taken to complete each specified stage (`fit`, `infer`, `fit_infer`) across all selected model instances. For instance, if the average `fit` time is 1s per instance and there are 2 instances, the total time will be 2 * 1s = 2s.\n\nAdditionally, on multicore systems, the cumulative CPU time (e.g., 20s for the `infer` stage) can exceed the `infer_every` interval (e.g., 10s).",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "WITH (f = {job=~\"$job\", instance=~\"$instance\", preset=~\"$preset\", scheduler_alias=~\"$scheduler_alias\", query_key=~\"$query_key\", model_alias=~\"$model_alias\"})\nsum by (stage) (\n  sum by (job, instance, preset, scheduler_alias, query_key, model_alias, stage) (\n    vmanomaly_model_run_duration_seconds_sum{f} / vmanomaly_model_run_duration_seconds_count{f}\n  ) * on (job, instance, preset, scheduler_alias, query_key, model_alias)\n  group_right(stage) vmanomaly_models_active{f}\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data Acceptance, Inference (%)",
   "type": "stat",
   "description": "The ratio of datapoints produced to datapoints accepted during inference (`infer`, `fit_infer` stages). Ideally, this should approach 100%, signifying no erroneous data is received from the input data source.",
   "gridPos": { "h": 4, "w": 9, "x": 3, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "WITH(f={job=~\"$job\",instance=~\"$instance\",preset=~\"$preset\",scheduler_alias=~\"$scheduler_alias\", model_alias=~\"$model_alias\",query_key=~\"$query_key\", stage=~\".*infer\"})\nsum by (stage) (increase(vmanomaly_model_datapoints_produced_total{f}[$__range])) / sum by (stage) (increase(vmanomaly_model_datapoints_accepted_total{f}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "description": "I/O Statistics",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 29 },
   "options": {
    "content": "#### I/O Statistics\n\nHow many datapoints, timeseries and bytes were sent/received given the filters. Overall success rate for I/O."
   }
  },
  {
   "title": "Last available value",
   "type": "table",
   "description": "Last successful run timestamp, read/write. If several models, queries and schedulers exists, get **oldest** timestamp to track for outdated values",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "targets": [
    {
     "expr": "min(timestamp(last_over_time(vmanomaly_reader_responses_total{job=~\"$job\", instance=~\"$instance\",preset=~\"$preset\", scheduler_alias=~\"$scheduler_alias\", query_key=~\"$query_key\", code=~\"2..\"}[$__range]))) by () * 1000",
     "legendFormat": "read"
    },
    {
     "expr": "min(timestamp(last_over_time(vmanomaly_writer_responses_total{job=~\"$job\", instance=~\"$instance\",preset=~\"$preset\", scheduler_alias=~\"$scheduler_alias\", query_key=~\"$query_key\", code=~\"2..\"}[$__range]))) by () * 1000",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "I/O success, %",
   "type": "stat",
   "description": "Percentage of successful reads, writes and total I/O with respect to the filters applied",
   "gridPos": { "h": 4, "w": 16, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "with (\n  valid = {__name__='vmanomaly_reader_responses_total', instance=~\"$instance\", job=~\"$job\", preset=~\"$preset\", scheduler_alias=~\"$scheduler_alias\", query_key=~\"$query_key\", code=~\"2..\"},\n  all = {__name__='vmanomaly_reader_responses_total', instance=~\"$instance\", job=~\"$job\", preset=~\"$preset\", scheduler_alias=~\"$scheduler_alias\", query_key=~\"$query_key\"}\n)\n(sum(increase(valid[$__range])) by ()) / (sum(increase(all[$__range])) by ())",
     "legendFormat": "Reads"
    },
    {
     "expr": "with (\n  valid = {__name__='vmanomaly_writer_responses_total', instance=~\"$instance\", job=~\"$job\", preset=~\"$preset\", scheduler_alias=~\"$scheduler_alias\", query_key=~\"$query_key\", code=~\"2..\"},\n  all = {__name__='vmanomaly_writer_responses_total', instance=~\"$instance\", job=~\"$job\", preset=~\"$preset\", scheduler_alias=~\"$scheduler_alias\", query_key=~\"$query_key\"}\n)\n(sum(increase(valid[$__range])) by ()) / (sum(increase(all[$__range])) by ())",
     "legendFormat": "Writes"
    },
    {
     "expr": "with (\n  valid = {__name__=~'vmanomaly_(writer|reader)_responses_total', instance=~\"$instance\", job=~\"$job\", preset=~\"$preset\", scheduler_alias=~\"$scheduler_alias\", query_key=~\"$query_key\", code=~\"2..\"},\n  all = {__name__=~'vmanomaly_(writer|reader)_responses_total', instance=~\"$instance\", job=~\"$job\", preset=~\"$preset\", scheduler_alias=~\"$scheduler_alias\", query_key=~\"$query_key\"}\n)\n(sum(increase(valid[$__range])) by ()) / (sum(increase(all[$__range])) by ())",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Timeseries I/O",
   "type": "timeseries",
   "description": "Total timeseries (metrics) received/sent by models, across stages",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(vmanomaly_reader_timeseries_received_total{job=~\"$job\",instance=~\"$instance\",preset=~\"$preset\",scheduler_alias=~\"$scheduler_alias\",query_key=~\"$query_key\"}[$__range])) by ()",
     "legendFormat": "In"
    },
    {
     "expr": "sum(increase(vmanomaly_writer_timeseries_sent_total{job=~\"$job\",instance=~\"$instance\",preset=~\"$preset\",scheduler_alias=~\"$scheduler_alias\",query_key=~\"$query_key\"}[$__range])) by ()",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Datapoints I/O",
   "type": "timeseries",
   "description": "Total data points (rows) received/sent by models, across stages",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(vmanomaly_reader_datapoints_received_total{job=~\"$job\",instance=~\"$instance\",preset=~\"$preset\",scheduler_alias=~\"$scheduler_alias\",query_key=~\"$query_key\"}[$__range])) by ()",
     "legendFormat": "In"
    },
    {
     "expr": "sum(increase(vmanomaly_writer_datapoints_sent_total{job=~\"$job\",instance=~\"$instance\",preset=~\"$preset\",scheduler_alias=~\"$scheduler_alias\",query_key=~\"$query_key\"}[$__range])) by ()",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Bytes I/O",
   "type": "timeseries",
   "description": "Total bytes received/sent with respect to applied filters.",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(increase(vmanomaly_reader_received_bytes_total{job=~\"$job\",instance=~\"$instance\",preset=~\"$preset\", scheduler_alias=~\"$scheduler_alias\", query_key=~\"$query_key\"}[$__range])) by ()",
     "legendFormat": "In"
    },
    {
     "expr": "sum(increase(vmanomaly_writer_sent_bytes_total{job=~\"$job\",instance=~\"$instance\",preset=~\"$preset\", scheduler_alias=~\"$scheduler_alias\", query_key=~\"$query_key\"}[$__interval])) by ()",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Datapoints per TimeSeries",
   "type": "timeseries",
   "description": "Avg. # of datapoints (rows) per timeseries received/sent",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(vmanomaly_reader_datapoints_received_total{job=~\"$job\",instance=~\"$instance\",preset=~\"$preset\",scheduler_alias=~\"$scheduler_alias\",query_key=~\"$query_key\"}[$__range])) by () / sum(increase(vmanomaly_reader_timeseries_received_total{job=~\"$job\",instance=~\"$instance\",preset=~\"$preset\",scheduler_alias=~\"$scheduler_alias\",query_key=~\"$query_key\"}[$__range])) by ()",
     "legendFormat": "In"
    },
    {
     "expr": "sum(increase(vmanomaly_writer_datapoints_sent_total{job=~\"$job\",instance=~\"$instance\",preset=~\"$preset\",scheduler_alias=~\"$scheduler_alias\",query_key=~\"$query_key\"}[$__range])) by () / sum(increase(vmanomaly_writer_timeseries_sent_total{job=~\"$job\",instance=~\"$instance\",preset=~\"$preset\",scheduler_alias=~\"$scheduler_alias\",query_key=~\"$query_key\"}[$__range])) by ()",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "type": "text",
   "description": "Time taken for read, write, and input data processing stages.",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 49 },
   "options": {
    "content": "#### Latency Statistics\n\nTime taken for read, write, and model processing stages."
   }
  },
  {
   "title": "Read latency (weighted avg.)",
   "type": "timeseries",
   "description": "Avg. time (s) spent by vmanomaly on getting input data from datasource",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "WITH(f = {job=~\"$job\", instance=~\"$instance\", preset=~\"$preset\", scheduler_alias=~\"$scheduler_alias\", query_key=~\"$query_key\"})\nsum (increase(vmanomaly_reader_request_duration_seconds_sum{f}[$__range])) / sum(increase(vmanomaly_reader_request_duration_seconds_count{f}[$__range]))",
     "legendFormat": "Read Latency"
    }
   ]
  },
  {
   "title": "Read latencies distribution",
   "type": "histogram",
   "description": "How long vmanomaly waited for read requests to data source",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "WITH(f = {job=~\"$job\", instance=~\"$instance\", preset=~\"$preset\", scheduler_alias=~\"$scheduler_alias\", query_key=~\"$query_key\"})\nsum (increase(vmanomaly_reader_request_duration_seconds_sum{f}[$__range])) / sum(increase(vmanomaly_reader_request_duration_seconds_count{f}[$__range])) * 1000",
     "legendFormat": "Read latency"
    }
   ]
  },
  {
   "title": "Response processing latency (weighted avg.)",
   "type": "timeseries",
   "description": "Avg. time (s) spent by vmanomaly on processing input response data before it enters the models (by `step`)",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "WITH(f = {job=~\"$job\", instance=~\"$instance\", preset=~\"$preset\", scheduler_alias=~\"$scheduler_alias\", query_key=~\"$query_key\"})\nsum (increase(vmanomaly_reader_response_parsing_seconds_sum{f}[$__range])) by (step) / sum(increase(vmanomaly_reader_response_parsing_seconds_count{f}[$__range])) by (step)",
     "legendFormat": "Data processing, {{step}}"
    }
   ]
  },
  {
   "title": "Processing time, json",
   "type": "histogram",
   "description": "Avg. time (s) spent by vmanomaly on processing input response data before it enters the models (`json`)",
   "gridPos": { "h": 7, "w": 6, "x": 11, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "WITH(f = {job=~\"$job\", instance=~\"$instance\", preset=~\"$preset\", scheduler_alias=~\"$scheduler_alias\", query_key=~\"$query_key\", step=\"json\"})\nsum (increase(vmanomaly_reader_response_parsing_seconds_sum{f}[$__range])) by (step)  / sum(increase(vmanomaly_reader_response_parsing_seconds_count{f}[$__range]))  by (step) * 1000",
     "legendFormat": "Response processing, {{step}}"
    }
   ]
  },
  {
   "title": "Processing time, dataframe",
   "type": "histogram",
   "description": "Avg. time (s) spent by vmanomaly on processing input response data before it enters the models (`df`)",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "WITH(f = {job=~\"$job\", instance=~\"$instance\", preset=~\"$preset\", scheduler_alias=~\"$scheduler_alias\", query_key=~\"$query_key\", step=\"df\"})\nsum (increase(vmanomaly_reader_response_parsing_seconds_sum{f}[$__range])) by (step)  / sum(increase(vmanomaly_reader_response_parsing_seconds_count{f}[$__range]))  by (step) * 1000",
     "legendFormat": "Response processing, {{step}}"
    }
   ]
  },
  {
   "title": "Write latency (weighted avg.)",
   "type": "timeseries",
   "description": "Duration of time vmanomaly spent on avg. write request with output data",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "WITH(f = {job=~\"$job\", instance=~\"$instance\", preset=~\"$preset\", scheduler_alias=~\"$scheduler_alias\", query_key=~\"$query_key\"})\nsum (increase(vmanomaly_writer_request_duration_seconds_sum{f}[$__range])) / sum(increase(vmanomaly_writer_request_duration_seconds_count{f}[$__range]))",
     "legendFormat": "Write Latency"
    }
   ]
  },
  {
   "title": "Write latencies distribution",
   "type": "histogram",
   "description": "How much time vmanomaly spent for write requests to write its anomaly estimates to the destination",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "WITH(f = {job=~\"$job\", instance=~\"$instance\", preset=~\"$preset\", scheduler_alias=~\"$scheduler_alias\", query_key=~\"$query_key\"})\nsum (increase(vmanomaly_writer_request_duration_seconds_sum{f}[$__range])) / sum(increase(vmanomaly_writer_request_duration_seconds_count{f}[$__range])) * 1000",
     "legendFormat": "Write Latency"
    }
   ]
  },
  {
   "type": "text",
   "description": "Overall resource utilization: CPU (avg.), RAM (total) and FD (total) for filtered instances & jobs.",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 68 },
   "options": {
    "content": "#### Resource Statistics\n\nOverall resource utilization: CPU (avg.), RAM (total) and FD (total) for filtered instances & jobs."
   }
  },
  {
   "title": "RAM usage",
   "type": "timeseries",
   "description": "Based on process' resident memory size in bytes. Total for selected jobs/instances",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by() (process_resident_memory_bytes{job=~\"$job\",instance=~\"$instance\"}[$__range])",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "Total user and system CPU time spent in seconds. Avg. for selected jobs/instances",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by () (rate(process_cpu_seconds_total{job=~\"$job\",instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Averaged"
    }
   ]
  },
  {
   "title": "FD usage",
   "type": "timeseries",
   "description": "Number of open file descriptors (by `vmanomaly` process). Total for selected jobs/instances",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (process_open_fds{job=~\"$job\",instance=~\"$instance\"}[$__range])",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Resource Usage per instance: $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "repeat": "instance"
  },
  {
   "title": "RAM usage",
   "type": "timeseries",
   "description": "Based on process' resident memory size in bytes.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(job,instance) (process_resident_memory_bytes{job=~\"$job\",instance=~\"$instance\"}[$__range])",
     "legendFormat": "job={{job}} "
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "Total user and system CPU time spent in seconds.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (job,instance) (rate(process_cpu_seconds_total{job=~\"$job\",instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "job={{job}} "
    }
   ]
  },
  {
   "title": "FD usage",
   "type": "timeseries",
   "description": "Number of open file descriptors (by `vmanomaly` process)",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job,instance) (process_open_fds{job=~\"$job\",instance=~\"$instance\"}[$__range])",
     "legendFormat": "job={{job}} "
    }
   ]
  },
  {
   "title": "Model Alias Overview: $model_alias",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 },
   "repeat": "model_alias"
  },
  {
   "title": "Uses",
   "type": "stat",
   "description": "Displays, for each `model_alias`, the number of unique queries it processes, the number of schedulers it is linked to, the number of instances utilizing this model and the number of active model instances of `model_alias` type",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (vmanomaly_models_active{model_alias=~\"$model_alias\"}) by (model_alias)\n",
     "legendFormat": "Models"
    },
    {
     "expr": "count (count (vmanomaly_models_active{model_alias=~\"$model_alias\"}) by (model_alias, query_key)) by (model_alias)\n",
     "legendFormat": "Queries"
    },
    {
     "expr": "count (count (vmanomaly_models_active{model_alias=~\"$model_alias\"}) by (model_alias, scheduler_alias)) by (model_alias)\n",
     "legendFormat": "Schedulers"
    },
    {
     "expr": "count (count (vmanomaly_models_active{model_alias=~\"$model_alias\"}) by (model_alias, instance)) by (model_alias)\n",
     "legendFormat": "Instances"
    }
   ]
  },
  {
   "title": "Runs: Success",
   "type": "stat",
   "description": "How many times vmanomaly ran during selected time range, total for all models of this class",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (stage) (increase(vmanomaly_model_runs_total{job=~\"$job\",instance=~\"$instance\",preset=~\"$preset\",scheduler_alias=~\"$scheduler_alias\",model_alias=~\"$model_alias\",query_key=~\"$query_key\"}[$__range]))",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "Runs: Skipped",
   "type": "stat",
   "description": "Models skipped running due to expected reasons (like no data to run stage on). Check vmanomaly logs for the details",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (stage) (vmanomaly_model_runs_skipped_total{job=~\"$job\",instance=~\"$instance\",preset=~\"$preset\",scheduler_alias=~\"$scheduler_alias\",model_alias=~\"$model_alias\",query_key=~\"$query_key\"}[$__range])",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "Runs: Errors",
   "type": "stat",
   "description": "Models skipped running due to data/model errors. Check vmanomaly logs for the details",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (stage) (vmanomaly_model_run_errors_total{job=~\"$job\",instance=~\"$instance\",preset=~\"$preset\",scheduler_alias=~\"$scheduler_alias\",model_alias=~\"$model_alias\",query_key=~\"$query_key\"}[$__range])",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "Datapoints processed, by stage",
   "type": "timeseries",
   "description": "How many datapoints models are processing during fit/infer stages, sum for all models of that `model_alias` type.\n<br>Note: for rolling models, which have combined `fit_infer` stage, volumes for fit and infer will be the same for consistency with other model types",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "WITH(f={job=~\"$job\",instance=~\"$instance\",preset=~\"$preset\",scheduler_alias=~\"$scheduler_alias\",query_key=~\"$query_key\",model_alias=\"$model_alias\", stage=~\"fit.*\"})\nsum by () (increase(vmanomaly_model_datapoints_accepted_total{f}[$__range]))",
     "legendFormat": "Fit"
    },
    {
     "expr": "WITH(f={job=~\"$job\",instance=~\"$instance\",preset=~\"$preset\",scheduler_alias=~\"$scheduler_alias\",query_key=~\"$query_key\",model_alias=\"$model_alias\", stage=~\".*infer\"})\nsum by () (increase(vmanomaly_model_datapoints_accepted_total{f}[$__range]))",
     "legendFormat": "Infer"
    }
   ]
  },
  {
   "title": "Datapoints IO Inference",
   "type": "stat",
   "description": "How many datapoints models are receiving (in) vs. producing (out), sum for models.",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "WITH(f={job=~\"$job\",instance=~\"$instance\",preset=~\"$preset\",scheduler_alias=~\"$scheduler_alias\",model_alias=~\"$model_alias\", stage=~\".*infer\",query_key=~\"$query_key\"})\nsum by (stage) (increase(vmanomaly_model_datapoints_accepted_total{f}[$__range]))",
     "legendFormat": "in"
    },
    {
     "expr": "WITH(f={job=~\"$job\",instance=~\"$instance\",preset=~\"$preset\",scheduler_alias=~\"$scheduler_alias\",model_alias=~\"$model_alias\", stage=~\".*infer\",query_key=~\"$query_key\"})\nsum by (stage) (increase(vmanomaly_model_datapoints_produced_total{f}[$__range]))",
     "legendFormat": "out"
    }
   ]
  },
  {
   "title": "Datapoints accepted",
   "type": "stat",
   "description": "Total rows accepted by models, by stage, within selected time range",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (stage) (increase(vmanomaly_model_datapoints_accepted_total{job=~\"$job\",instance=~\"$instance\",preset=~\"$preset\",scheduler_alias=~\"$scheduler_alias\",model_alias=~\"$model_alias\",query_key=~\"$query_key\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg. model run time",
   "type": "stat",
   "description": "How long average model run took , in seconds",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "WITH (f = {job=~\"$job\",instance=~\"$instance\",preset=~\"$preset\",scheduler_alias=~\"$scheduler_alias\",model_alias=~\"$model_alias\",query_key=~\"$query_key\"})\navg by (stage) (1000 * ( \n    increase(vmanomaly_model_run_duration_seconds_sum{f}[$__range]) / \n    increase(vmanomaly_model_run_duration_seconds_count{f}[$__range])\n))",
     "legendFormat": "{{stage}}"
    }
   ]
  }
 ]
}