{
 "title": "VSphere Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "metrics", "query": "prometheus" },
   { "name": "logs", "query": "loki" },
   {
    "name": "vcenter",
    "query": {
     "query": "label_values(vsphere_cluster_cpu_totalmhz_average,vcenter)"
    }
   },
   {
    "name": "esxi_host",
    "query": {
     "query": "label_values(vsphere_host_sys_uptime_latest{vcenter=~\"$vcenter.*\"},esxhostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Host Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vsphere_host_sys_uptime_latest{vcenter=~\"$vcenter.*\"}",
     "legendFormat": "{{esxhostname}}"
    }
   ]
  },
  {
   "title": "Guests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(vsphere_vm_sys_osUptime_latest{vcenter=~\"$vcenter.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hosts",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(vsphere_host_mem_consumed_average{vcenter=~\"$vcenter.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum by(esxhostname) (vsphere_host_cpu_coreUtilization_average{vcenter=~\"$vcenter.*\"}) / count by(esxhostname) (vsphere_host_cpu_coreUtilization_average{vcenter=~\"$vcenter.*\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mem usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "Datastore Capacity",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vsphere_datastore_disk_used_latest{vcenter=~\"$vcenter.*\"} / vsphere_datastore_disk_capacity_latest{vcenter=~\"$vcenter.*\"}",
     "legendFormat": "{{dsname}} "
    }
   ]
  },
  {
   "title": "ESXI CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by(esxhostname) (vsphere_host_cpu_coreUtilization_average{vcenter=~\"$vcenter.*\"}) / count by(esxhostname) (vsphere_host_cpu_coreUtilization_average{vcenter=~\"$vcenter.*\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(sum by(esxhostname) (vsphere_host_cpu_coreUtilization_average{vcenter=~\"$vcenter.*\"}) / count by(esxhostname) (vsphere_host_cpu_coreUtilization_average{vcenter=~\"$vcenter.*\"}))",
     "legendFormat": "overall"
    }
   ]
  },
  {
   "title": "Cluster Percent Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "vsphere_cluster_mem_usage_average{vcenter=~\"$vcenter.*\"}",
     "legendFormat": "{{vcenter}}"
    }
   ]
  },
  {
   "title": "Data store Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "panelId": 12 }
   ]
  },
  {
   "title": "Datastore Capacity",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vsphere_datastore_disk_capacity_latest{vcenter=~\"$vcenter.*\"}",
     "legendFormat": "{{dsname}} "
    }
   ]
  },
  {
   "title": "Datastore Usage",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vsphere_datastore_disk_used_latest{vcenter=~\"$vcenter.*\"}",
     "legendFormat": "{{dsname}} "
    }
   ]
  },
  {
   "title": "Vsphere Operations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 10, "y": 15 },
   "targets": [
    {
     "expr": "increase(vsphere_cluster_vmop_numCreate_latest{vcenter=~\"$vcenter.*\"})",
     "legendFormat": "created VMs"
    },
    {
     "expr": "increase(vsphere_cluster_vmop_numClone_latest{vcenter=~\"$vcenter.*\"})",
     "legendFormat": "Cloned VMs"
    },
    {
     "expr": "increase(vsphere_cluster_vmop_numChangeDS_latest{vcenter=~\"$vcenter.*\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "vsphere_cluster_vmop_numDeploy_latest{vecnter=~\"$vcenter.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Datastore IOPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 15 },
   "targets": [
    {
     "expr": "vsphere_datastore_datastore_numberWriteAveraged_average{vcenter=~\"$vcenter.*\"} + vsphere_datastore_datastore_numberWriteAveraged_average{vcenter=~\"$vcenter.*\"}",
     "legendFormat": "{{ source }}"
    }
   ]
  },
  {
   "title": "Vsphere Logs Warning and higher",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{hostname=~\"$vcenter.*\", severity=~\"warning|err|notice\"} |= ``"
    }
   ]
  },
  {
   "title": "ESXI Logs Warning and higher",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "{hostname=~\"$esxi_host\", severity=~\"warning|err|notice\"} |= ``"
    }
   ]
  }
 ]
}