{
 "title": "Windows Host",
 "tags": [ "windows" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "metrics",
    "query": "victoriametrics-metrics-datasource"
   },
   {
    "name": "logs",
    "query": "victoriametrics-logs-datasource"
   },
   {
    "name": "host",
    "query": {
     "query": "label_values(cpu_usage_idle{db=\"windows\"},host)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Host Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Host Summary",
   "type": "table",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg by (host) (100 - cpu_usage_idle{host=~\"$host\",db=\"windows\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by (host) (mem_used_percent{db=\"windows\",host=~\"$host\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by (host) (cpu_usage_iowait{host=~\"$host\",db=\"windows\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (host) (system_uptime{host=~\"$host\",db=\"windows\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (host) (system_n_cpus{host=~\"$host\",db=\"windows\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (host) (mem_total{host=~\"$host\",db=\"windows\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Version",
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
   "targets": [
    {
     "expr": "tags.host:$host AND name:=\"win_ver_Win32_OperatingSystem\""
    }
   ]
  },
  {
   "title": "Failed Services",
   "type": "table",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 7 },
   "targets": [
    {
     "expr": "win_services_state{db=\"windows\",host=\"$host\"} == 3"
    }
   ]
  },
  {
   "title": "CPU Percent",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "100 - cpu_usage_idle{host=~\"$host\",db=\"windows\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Memory Percent",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 10, "y": 8 },
   "targets": [
    {
     "expr": "mem_used_percent{db=\"windows\",host=~\"$host\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Disk Used %",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(disk_used_percent{host=~\"$host\",db=\"windows\"})",
     "legendFormat": "{{host}} - {{path}}"
    }
   ]
  },
  {
   "title": "Mbytes/sec received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "rate(net_bytes_recv{host=~\"$host\",db=\"windows\",interface!~\"veth.*\"}[$__rate_interval]) * 8",
     "legendFormat": "{{host}} - {{interface}}"
    }
   ]
  },
  {
   "title": "Mbytes/sec received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "rate(net_bytes_recv{host=~\"$host\",db=\"windows\",interface!~\"veth.*\"}[$__rate_interval]) * 8",
     "legendFormat": "{{host}} - {{interface}}"
    }
   ]
  },
  {
   "title": "DiskIO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(diskio_read_bytes{host=~\"$host\",db=\"windows\"}) + rate(diskio_write_bytes{host=~\"$host\",db=\"windows\"}[$__rate_interval])",
     "legendFormat": "{{host}} - {{name}}"
    }
   ]
  },
  {
   "title": "Disk Status",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "win_wmi_MSStorageDriver_FailurePredictStatus_Reason{host=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Mbytes/sec received",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "rate(net_bytes_recv{host=~\"$host\",db=\"windows\"}[$__rate_interval]) * 8",
     "legendFormat": "{{host}} - {{interface}}"
    }
   ]
  },
  {
   "title": "mbytes/sec sent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "rate(net_bytes_sent{host=~\"$host\",db=\"windows\"}[$__rate_interval]) * 8",
     "legendFormat": "{{host}} - {{interface}}"
    }
   ]
  },
  {
   "title": "DiskIO",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(diskio_read_bytes{host=~\"$host\",db=\"windows\"} + diskio_write_bytes{host=~\"$host\",db=\"windows\"}[$__rate_interval])",
     "legendFormat": "{{host}} - {{name}}"
    }
   ]
  },
  { "title": "Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Service Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "win_services_state{db=\"windows\",host=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Service Startup State",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "win_services_startup_mode{db=\"windows\",host=~\"$host\"}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Sysmon Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "direction": "backward",
     "expr": "tags.Channel:=\"Microsoft-Windows-Sysmon/Operational\" AND tags.host:\"$host\""
    }
   ]
  },
  {
   "title": "Defender Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "direction": "backward",
     "expr": "tags.Channel:\"Microsoft-Windows-Windows Defender.*\" AND tags.host:\"$host\""
    }
   ]
  },
  {
   "title": "Disk Size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Size",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 7, "x": 0, "y": 216 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort(disk_total{host=~\"$host\",db=\"windows\"})",
       "legendFormat": "{{host}} - {{path}}"
      }
     ]
    },
    {
     "title": "Disk Available",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 7, "x": 7, "y": 216 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort(disk_free{host=~\"$host\",db=\"windows\"})",
       "legendFormat": "{{host}} - {{path}}"
      }
     ]
    },
    {
     "title": "Disk Available Over Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 10, "x": 14, "y": 216 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "disk_free{host=~\"$host\",db=\"windows\"}",
       "legendFormat": "{{host}} - {{path}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Diskio",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Reads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 217 },
     "targets": [
      {
       "expr": "increase(diskio_reads{host=~\"$host\", db=\"windows\"})",
       "legendFormat": "{{host}} - {{name}}"
      }
     ]
    },
    {
     "title": "Disk Writes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 217 },
     "targets": [
      {
       "expr": "increase(diskio_writes{host=~\"$host\", db=\"windows\"})",
       "legendFormat": "{{host}} - {{name}}"
      }
     ]
    },
    {
     "title": "Disk Read Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 233 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "increase(diskio_read_bytes{host=~\"$host\", db=\"windows\"})",
       "legendFormat": "{{host}} - {{name}}"
      }
     ]
    },
    {
     "title": "Disk Write Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 233 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "increase(diskio_write_bytes{host=~\"$host\", db=\"windows\"})",
       "legendFormat": "{{host}} - {{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Overview",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 61 },
     "targets": [
      {
       "expr": "avg(win_gpu_usage_value{host=~\"$host\"}) without (name)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(win_gpu_mem_Dedicated_Usage{host=~\"$host\"}) by (host)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(win_gpu_mem_Shared_Usage{host=~\"$host\"}) by (host)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(win_gpu_mem_Total_Committed{host=~\"$host\"}) by (host)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by (host,name) (amd_rocm_smi_power_draw{host=~\"$host\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GPU  Memory Used (Bytes)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "win_gpu_mem_Dedicated_Usage{host=~\"$host\"} > 0",
       "legendFormat": "{{host}} - {{instance}}"
      }
     ]
    },
    {
     "title": "GPU  Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "win_gpu_usage_value{host=~\"$host\"}",
       "legendFormat": "{{host}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Advanced CPU Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU IO Wait",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 218 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "cpu_usage_iowait{host=~\"$host\",db=\"windows\"}",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "CPU User",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 218 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "cpu_usage_user{host=~\"$host\",db=\"windows\"}",
       "legendFormat": "{{host}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Advanced Network Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "collapsed": true,
   "panels": [
    {
     "title": "Error Packets In",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(net_err_in{host=~\"$host\",db=\"windows\"}[$__rate_interval])",
       "legendFormat": "{{host}} - {{interface}}"
      }
     ]
    },
    {
     "title": "Error Packets In",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(net_err_in{host=~\"$host\",db=\"windows\"}[$__rate_interval])",
       "legendFormat": "{{host}} - {{interface}}"
      }
     ]
    },
    {
     "title": "Dropped Packets in",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(net_drop_in{host=~\"$host\",db=\"windows\"}[$__rate_interval])",
       "legendFormat": "{{host}} - {{interface}}"
      }
     ]
    },
    {
     "title": "Dropped Packets Out",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(net_drop_out{host=~\"$host\",db=\"windows\"}[$__rate_interval]) * 8",
       "legendFormat": "{{host}} - {{interface}}"
      }
     ]
    }
   ]
  }
 ]
}