{
 "title": "ZFS",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "metrics", "query": "prometheus" },
   { "name": "logs", "query": "loki" },
   {
    "name": "host",
    "query": {
     "query": "label_values(zpool_stats_size,host)"
    }
   },
   {
    "name": "zpool",
    "query": {
     "query": "label_values(zpool_stats_size{host=\"$host\"},name)"
    }
   },
   {
    "name": "vdev",
    "query": {
     "query": "label_values(zpool_stats_size{host=\"$host\"},vdev)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pool % Used",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1-zpool_stats_free{host=\"$host\",name=\"$zpool\",vdev=\"$vdev\"}/zpool_stats_size{host=\"$host\",name=\"$zpool\",vdev=\"$vdev\"})*100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total Allicated",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zpool_stats_alloc{host=\"$host\",name=\"$zpool\",vdev=\"$vdev\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Space Free",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zpool_stats_free{host=\"$host\",name=\"$zpool\",vdev=\"$vdev\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ZPool Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "zpool_stats_free{host=\"$host\",name=\"$zpool\",vdev=\"$vdev\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zpool_stats_read_errors{host=\"$host\",name=\"$zpool\",vdev=\"$vdev\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zpool_stats_write_errors{host=\"$host\",name=\"$zpool\",vdev=\"$vdev\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CheckSum Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zpool_stats_checksum_errors{host=\"$host\",name=\"$zpool\",vdev=\"$vdev\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fragmentation",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zpool_stats_fragmentation{host=\"$host\",name=\"$zpool\",vdev=\"$vdev\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pool Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "zpool_stats_free{host=\"$host\",name=\"$zpool\",vdev=\"root\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "zpool_stats_alloc{host=\"$host\",name=\"$zpool\",vdev=\"root\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Read/Write Operations a minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 9, "y": 6 },
   "targets": [
    {
     "expr": "rate(zpool_stats_read_ops{host=\"$host\",name=\"$zpool\",vdev=\"$vdev\"}[1m])",
     "legendFormat": "Reads"
    },
    {
     "expr": "rate(zpool_stats_write_ops{host=\"$host\",name=\"$zpool\",vdev=\"$vdev\"}[1m])",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Read/Write Bytes per minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(zpool_stats_read_bytes{host=\"$host\",name=\"$zpool\",vdev=\"$vdev\"}[1m])",
     "legendFormat": "Reads"
    },
    {
     "expr": "rate(zpool_stats_write_bytes{host=\"$host\",name=\"$zpool\",vdev=\"$vdev\"}[1m])",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Scrub Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scan Errors",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "zpool_scan_stats_errors{host=\"$host\",name=\"$zpool\",vdev=\"$vdev\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Examined",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 3, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "zpool_scan_stats_examined{host=\"$host\",name=\"$zpool\",vdev=\"$vdev\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rate",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 6, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "zpool_scan_stats_rate{host=\"$host\",name=\"$zpool\",vdev=\"$vdev\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Start TS",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 9, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "zpool_scan_stats_start_ts{host=\"$host\",name=\"$zpool\",vdev=\"$vdev\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "End TS",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 12, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "zpool_scan_stats_end_ts{host=\"$host\",name=\"$zpool\",vdev=\"$vdev\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Pause TS",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "zpool_scan_stats_pause_ts{host=\"$host\",name=\"$zpool\",vdev=\"$vdev\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Paused Time",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 3, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "zpool_scan_stats_paused_t{host=\"$host\",name=\"$zpool\",vdev=\"$vdev\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Estimated Remaining",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 6, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "zpool_scan_stats_remaining_t{host=\"$host\",name=\"$zpool\",vdev=\"$vdev\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Latency and Queue Depth", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "ZFS Queues",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "zpool_vdev_stats_sync_r_active_queue",
     "legendFormat": "Sync Read Queue"
    },
    {
     "expr": "zpool_vdev_stats_sync_w_active_queue",
     "legendFormat": "Sync Write Queue"
    },
    {
     "expr": "zpool_vdev_stats_async_r_active_queue",
     "legendFormat": "Asynchronous Read Queue"
    },
    {
     "expr": "zpool_vdev_stats_async_w_active_queue",
     "legendFormat": "Asynchronous Write Queue"
    },
    {
     "expr": "zpool_vdev_stats_async_scrub_active_queue",
     "legendFormat": "Asynchronous Scrub Queue"
    },
    {
     "expr": "zpool_vdev_stats_sync_r_pend_queue",
     "legendFormat": "Synchronous Read Pending Queue"
    },
    {
     "expr": "zpool_vdev_stats_sync_w_pend_queue",
     "legendFormat": "Synchronous Write Pending Queue"
    },
    {
     "expr": "zpool_vdev_stats_async_r_pend_queue",
     "legendFormat": "Asynchronous Read Pending Queue"
    },
    {
     "expr": "zpool_vdev_stats_async_w_pend_queue",
     "legendFormat": "Asynchronous Write Pending Queue"
    },
    {
     "expr": "zpool_vdev_stats_async_scrub_pend_queue",
     "legendFormat": "Asynchronous Scrub Pending Queue"
    }
   ]
  },
  {
   "title": "IO Size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sync Read Size",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "zpool_io_size_sync_read_ind{host=\"$host\",name=\"$zpool\",vdev=\"$vdev\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Sync Write Size",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 30 },
     "targets": [
      {
       "expr": "zpool_io_size_sync_write_ind{host=\"$host\",name=\"$zpool\",vdev=\"$vdev\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Sync Write Size",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 30 },
     "targets": [
      {
       "expr": "zpool_io_size_sync_write_ind{host=\"$host\",name=\"$zpool\",vdev=\"$vdev\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Async Write Size",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 30 },
     "targets": [
      {
       "expr": "zpool_io_size_async_write_ind{host=\"$host\",name=\"$zpool\",vdev=\"$vdev\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Scrub IO Size",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "zpool_io_size_scrub_read_ind{host=\"$host\",name=\"$zpool\",vdev=\"$vdev\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Trim IO Size",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "targets": [
      {
       "expr": "zpool_io_size_trim_write_ind{host=\"$host\",name=\"$zpool\",vdev=\"$vdev\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "ZFS Total Read Latency",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "zpool_latency_total_read{host=\"$host\",name=\"$zpool\",vdev=\"$vdev\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "ZFS Total Write Latency",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 19 },
     "targets": [
      {
       "expr": "zpool_latency_total_write{host=\"$host\",name=\"$zpool\",vdev=\"$vdev\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "ZFS Disk Read Latency",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 19 },
     "targets": [
      {
       "expr": "zpool_latency_disk_read{host=\"$host\",name=\"$zpool\",vdev=\"$vdev\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "ZFS Disk Read Latency",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 19 },
     "targets": [
      {
       "expr": "zpool_latency_disk_read{host=\"$host\",name=\"$zpool\",vdev=\"$vdev\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "ZFS Sync Read Latency",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "zpool_latency_sync_read{host=\"$host\",name=\"$zpool\",vdev=\"$vdev\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "ZFS Sync Write Latency",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 27 },
     "targets": [
      {
       "expr": "zpool_latency_sync_read{host=\"$host\",name=\"$zpool\",vdev=\"$vdev\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "ZFS Async Read Latency",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 27 },
     "targets": [
      {
       "expr": "zpool_latency_async_read{host=\"$host\",name=\"$zpool\",vdev=\"$vdev\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "ZFS Async Write Latency",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 27 },
     "targets": [
      {
       "expr": "zpool_latency_async_write{host=\"$host\",name=\"$zpool\",vdev=\"$vdev\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "ZFS Trim Latency",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "zpool_latency_trim{host=\"$host\",name=\"$zpool\",vdev=\"$vdev\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "ZFS Scrub Latency",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "targets": [
      {
       "expr": "zpool_latency_scrub{host=\"$host\",name=\"$zpool\",vdev=\"$vdev\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}