- name: Install packages on RHEL based Systems
  dnf:
    name: '{{ redhat_packages }}'
    state: latest
  become: true
  when: ansible_facts['os_family'] == 'RedHat'

- name: Install packages on debian based systems
  apt:
    name: '{{ debian_packages }}'
    state: latest
  become: true
  when: ansible_facts['os_family'] == 'Debian'

- name: install podman compose on debian based systems
  pip:
    name: podman-compose
    state: latest
  become: true
  when: ansible_facts['os_family'] == 'Debian'

- name: start and enable podman
  systemd:
    name: podman
    state: started
    enabled: true
  become: true
  when: ansible_facts['os_family'] == 'Redhat'

- name: generate compose file
  template:
    src: docker-compose.yml
    dest: /opt/shift-mon/docker-compose.yml

- name: Copy startup and shutdown scripts
  copy:
    src: "{{ item }}"
    dest: "/opt/shift-mon/{{ item }}"
  become: true
  with_items:
  - startup.bash
  - shutdown.bash

- name: Create Systemd unit file
  copy:
    src: shift-mon.service
    dest: /etc/systemd/system/shift-mon.service
  become: true

- name: reload systemd units
  systemd:
    daemon-reload: true
  become: true

- name: restart and enable shift-mon.service
  systemd:
    name: shift-mon.service
    enabled: true
    state: restarted
  become: true