- name: Install packages on RHEL based Systems
  ansible.builtin.dnf:
    name: '{{ redhat_packages }}'
    state: latest
  become: true
  when: ansible_facts['os_family'] == 'RedHat'

- name: Install packages on Debian based systems
  ansible.builtin.apt:
    name: '{{ debian_packages }}'
    state: latest
  become: true
  when: ansible_facts['os_family'] == 'Debian'

- name: Install podman compose on Debian based systems
  ansible.builtin.pip:
    name: podman-compose
    state: latest
  become: true
  when: ansible_facts['os_family'] == 'Debian'

- name: Start and enable Podman
  ansible.builtin.systemd:
    name: podman
    state: started
    enabled: true
  become: true
  when: ansible_facts['os_family'] == 'Redhat'

- name: Generate compose file
  ansible.builtin.template:
    src: docker-compose.yml
    dest: /opt/shift-mon/docker-compose.yml

- name: Copy startup and shutdown scripts
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/opt/shift-mon/{{ item }}"
    mode: "770"
  become: true
  with_items:
    - startup.bash
    - shutdown.bash

- name: Create Systemd unit file
  ansible.builtin.copy:
    src: shift-mon.service
    dest: /etc/systemd/system/shift-mon.service
  become: true

- name: Reload Systemd units
  ansible.builtin.systemd:
    daemon-reload: true
  become: true

- name: Restart and enable shift-mon.service
  ansible.builtin.systemd:
    name: shift-mon.service
    enabled: true
    state: restarted
  become: true
