- name: create mimir user
  user:
    name: mimir
    state: present
    shell: /usr/sbin/nologin
  become: true

- name: create mimir folder
  file:
   path: /opt/mimir
   state: directory
   owner: mimir
   group: mimir
  become: true

- name: create mimir storage folder
  file:
   path: /opt/mimir-storage
   state: directory
   owner: mimir
   group: mimir
  become: true

- name: download victoriametrics
  get_url: 
    url: 'https://github.com/grafana/mimir/releases/download/mimir-{{ version }}/mimir-linux-amd64'
    dest: '/opt/mimir/mimir'
    user: mimir
    group: mimir
  become: true

- name: generate vm-auth config
  template:
    src: auth-config.yml
    dest: /opt/victoriametrics/auth-config.yml
  become: true

- name: create service files
  template:
    src: '{{ item}}.service'
    dest: /etc/systemd/system/{{ item}}.service
  become: true
  with_items: '{{ services }}'

- name: Reload systemd units
  systemd:
    daemon-reload: true
  become: true

- name: start and enable services
  systemd:
    name: '{{ item }}'
    enabled: true
    state: restarted
  become: true
  with_items: '{{ services }}'