- name: Create uptime-kuma directory
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    mode: '770'
    setype: container_file_t
  become: true
  with_items:
    - /opt/shift-mon/
    - /opt/shift-mon/uptime-kuma
