shiftmon_alerts_deadman_enabled: false
shiftmon_alerts_infra_enabled: false
shiftmon_alerts_blackbox_enabled: false
shiftmon_alerts_proxmox_enabled: false
shiftmon_alerts_freeipa_enabled: false
shiftmon_alerts_victorialogs_enabled: false
shiftmon_alerts_vmauth_enabled: false
shiftmon_alerts_alertmanager_enabled: false
shiftmon_alerts_victoriametrics_enabled: false
shiftmon_alerts_adguardhome_enabled: false
shiftmon_alerts_log_rules: false
shiftmon_alerts_watchtower_enabled: false
shiftmon_alerts_empty_rule_rules: false
telegraf_victoriametrics_config: true
alertmanager_from_email: "{{ alertmanager_smtp_username }}"
alertmanger_smtp_auth_identity: "{{ alertmanager_smtp_username }}"
vmanomaly_enabled: false
victorialogs_tokens: []
victoriametrics_tokens: []
