shiftmon_alerts_deadman_enabled: true
shiftmon_alerts_infra_enabled: true
shiftmon_alerts_blackbox_enabled: true
shiftmon_alerts_proxmox_enabled: true
shiftmon_alerts_freeipa_enabled: true
shiftmon_alerts_victorialogs_enabled: true
shiftmon_alerts_vmauth_enabled: true
shiftmon_alerts_alertmanager_enabled: true
shiftmon_alerts_victoriametrics_enabled: true
telegraf_victoriametrics_config: true
vmanomaly_enabled: false
alertmanager_config:
  global:
  route:
    group_by:
      - 'alertname'
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 1h
    receiver: 'webhook'
  receivers:
    - name: "{{ alertmanager.webhook_name }}"
      webhook_configs:
        - url: "{{ alertmanager.webhook_url }}"
          send_resolved: true
#      email_configs:
#        - to: '{{ alertmanager.to_email }}'
#          from: '{{ alertmanager.from_email }}'
#          smarthost: '{{ alertmanager.smarthost }}'
#          auth_username: '{{ alertmanager. }}'
#          auth_identity: '{{ alertmanager.smtp_username }}'
#          auth_password: '{{ alertmanager.smtp_password }}'
