- name: create loki folders
  file:
    path: "{{ item }}"
    state: directory
    mode: '777'
    setype: container_file_t
  become: true
  with_items:
    - /opt/shift-mon/
    - /opt/shift-mon/loki
    - /opt/shift-mon/loki-config
    - /opt/shift-mon/loki/rules-temp

- name: copy loki configs
  template:
    src: loki-config.yml
    dest: /opt/shift-mon/loki-config/loki-config.yml
  become: true

- name: add  loki config to telegraf
  copy:
    src: loki-docker.conf
    dest: /etc/telegraf/telegraf.d/loki-docker.conf
  become: true

- name: restart telegraf
  systemd:
    name: telegraf
    state: restarted
    enabled: true
  become: true