- name: create loki folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '770'
    setype: container_file_t
  become: true
  with_items:
    - /opt/shift-mon/

- name: create loki folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '770'
    owner: '10001'
    group: '10001'
    setype: container_file_t
  become: true
  with_items:
    - /opt/shift-mon/loki
    - /opt/shift-mon/loki-config
    - /opt/shift-mon/loki/rules-temp

- name: copy loki configs
  ansible.builtin.template:
    src: loki-config.yml
    dest: /opt/shift-mon/loki-config/loki-config.yml
  become: true

- name: add  loki config to telegraf
  ansible.builtin.copy:
    src: loki-docker.conf
    dest: /etc/telegraf/telegraf.d/loki-docker.conf
  become: true
  notify: restart telegraf
