- name: create loki folders
  file:
    path: "{{ item }}"
    state: directory
    mode: '777'
    setype: container_var_lib_t
  become: true
  with_items:
    - /opt/shift-mon/
    - /opt/shift-mon/loki
    - /opt/shift-mon/loki-config
    - /opt/shift-mon/loki/rules-temp

- name: copy loki configs
  template:
    src: loki-config.yml
    dest: /opt/shift-mon/loki-config/loki-config.yml
  become: true