- name: Create Shift-mon folder
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: shiftmon
    group: shiftmon
    mode: '770'
    setype: container_file_t
  become: true
  with_items:
    - /opt/shift-mon

- name: Create Loki folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '770'
    owner: shiftmon
    group: shiftmon
    setype: container_file_t
  become: true
  with_items:
    - /opt/shift-mon/loki
    - /opt/shift-mon/loki-config
    - /opt/shift-mon/loki/rules-temp/fake
    - /opt/shift-mon/loki/rules/fake
    - /opt/shift-mon/loki/ruler-wal/fake

- name: Copy loki configs
  ansible.builtin.template:
    src: loki-config.yml
    dest: /opt/shift-mon/loki-config/loki-config.yml
    owner: shiftmon
    group: shiftmon
  become: true

- name: Copy Shiftmon Recording Rules
  ansible.builtin.template:
    src: shiftmon-rules.yaml
    dest: /opt/shift-mon/loki/rules/fake/shiftmon-rules.yaml
    owner: shiftmon
    group: shiftmon
  become: true
