- name: Restart otel collector
  ansible.builtin.systemd:
    name: otelcol-contrib.service
    state: restarted
    enabled: true
  become: true

- name: Restart Syslog
  ansible.builtin.systemd:
    name: rsyslog
    state: restarted
    enabled: true
  become: true
