- name: Install dependencies for Meshcentral
  apt:
    name: "{{ packages }}"
    state: present
  become: true

- name: Create Meshcentral group
  group:
    name: meshcentral
    state: present
  become: true

- name: Create Meshcentral user
  user:
    name: meshcentral
    group: meshcentral
    shell: /sbin/nologin
    state: present
  become: true

- name: Create Meshcentral directory
  file:
    name: /opt/meshcentral
    state: directory
    owner: meshcentral
    group: meshcentral
  become: true

- name: Create Meshcentral data directory
  file:
    name: /opt/meshcentral/meshcentral-data
    state: directory
    owner: meshcentral
    group: meshcentral
  become: true

- name: Create Meshcentral Images directory
  file:
    name: /opt/meshcentral/meshcentral-data/images/
    state: directory
    owner: meshcentral
    group: meshcentral
  become: true

- name: Install Meshcentral via npm
  npm:
    name: meshcentral
    path: /opt/meshcentral
  become: true

- name: Add Title Image
  copy:
    src: title.png
    dest: /opt/meshcentral/meshcentral-data/images/title.png
    owner: meshcentral
    group: meshcentral
  become: true

- name: Add Welcome Image
  copy:
    src: welcome.png
    dest: /opt/meshcentral/meshcentral-data/images/welcome.png
    owner: meshcentral
    group: meshcentral
  become: true

- name: Copy in meshcentral config file
  template:
    src: mesh-config.j2
    dest: /opt/meshcentral/meshcentral-data/config.json
  become: true

- name: Add in service file for Meshcentral
  copy:
    src: meshcentral.service
    dest: /etc/systemd/system/meshcentral.service
  become: true



- name: start and enable services required for Meshcentral
  systemd:
    name: "{{ item }}"
    state: restarted
    enabled: true
    daemon-reload: true
  become: true
  with_items: "{{ services }}"


