groups:
  - name: AdGuardHome Rules
    limit: 100
    interval: 5m
    rules:
      - record: adguardhome_cache_rate5m
        expr: |
          (count by (host) (rate({path=~".*querylog.json"} | logfmt | Cached = `true` [5m]))) / (count by(host) (rate({path=~".*querylog.json"} | logfmt[5m])))
        labels:
          user: "shiftmon"
      - record: adguardhome_block_rate5m
        expr: |
         (count by (host) (rate({path=~".*data/querylog.json"} | logfmt | Result_IsFiltered="true"[5m]))) / (count by(host) (rate({path=~".*data/querylog.json"} | logfmt[5m])))
        labels:
          user: "shiftmon"
      - record: adguardhome_request_rate5m
        expr: |
          (count by (host) (rate({path=~".*querylog.json"} | logfmt[5m])))
        labels:
          user: "shiftmon"
