services:
  grafana:
    image: docker.io/grafana/grafana-oss:latest
    restart: unless-stopped
    volumes:
      - type: bind
        source: /opt/shift-mon/grafana-config
        target: /etc/grafana
      - type: bind
        source: /opt/shift-mon/grafana
        target: /var/lib/grafana
    labels:
      - "io.containers.autoupdate=registry"
  loki:
    image: docker.io/grafana/loki:latest
    restart: unless-stopped
    volumes:
      - type: bind
        source: /opt/shift-mon/loki
        target: /loki
      - type: bind
        source: /opt/shift-mon/loki-config
        target: /etc/loki/
    labels:
      - "io.containers.autoupdate=registry"
    command:
      - "-config.file=/etc/loki/loki-config.yml"
  victoriametrics:
    restart: unless-stopped
    image: docker.io/victoriametrics/victoria-metrics:latest
    volumes:
      - type: bind
        source: /opt/shift-mon/victoriametrics-storage
        target: /victoriametrics-storage
    labels:
      - "io.containers.autoupdate=registry"
    command:
      - "--retentionPeriod=90d"
      - "--storageDataPath=/victoriametrics-storage"
      - "--httpListenAddr=:8428"
  traefik:
    restart: unless-stopped
    image: docker.io/traefik:latest
    volumes:
      - type: bind
        source: /opt/shift-mon/traefik
        target: /etc/traefik
    ports:
     - 80:80
     - 443:443
    labels:
      - "io.containers.autoupdate=registry"
  crowdsec:
   image: crowdsecurity/crowdsec:vlatest
   restart: always
   environment:
     #this is the list of collections we want to install    
     #https://hub.crowdsec.net/author/crowdsecurity/collections/nginx
     COLLECTIONS: "crowdsecurity/traefik"
     GID: "${GID-1000}"
   depends_on:
     - 'reverse-proxy'
   volumes:
     - /opt/shift-mon/crowdsec/acquis.yaml:/etc/crowdsec/acquis.yaml
     - /opt/shift-mon/crowdsec/crowdsec-db:/var/lib/crowdsec/data/
     - /opt/shift-mon/crowdsec-config:/etc/crowdsec/
     - type: bind
       source: /opt/shift-mon/traefik
       target: /etc/traefik
{% if dns.provider is defined and dns.auth_values is defined %}
    environment:
{% for key, value in dns.auth_values.items() %}
      {{key}}: '{{value}}'
{% endfor %}
{% endif %}
    command:
      - "--auth.config=/config/auth-config.yml"