- name: Install Docker
  ansible.builtin.include_role:
    name: ansible-role-docker
    public: true
    apply:
      become: true

- name: get shiftmon userid
  ansible.builtin.command: id -u shiftmon
  register: shiftmon_user_id
  become: true

- name: get shiftmon userid
  ansible.builtin.command: id -g shiftmon
  register: shiftmon_group_id
  become: true

- name: Generate compose File
  ansible.builtin.template:
    src: 'docker-compose.yml'
    dest: /opt/shift-mon/docker-compose.yml
    mode: '770'
    owner: shiftmon
    group: shiftmon
    setype: container_file_t
  become: true

- name: Remove Legacy Scripts
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/opt/shift-mon/{{ item }}"
    mode: "770"
  become: true
  with_items:
    - startup.bash
    - shutdown.bash

- name: Reload Systemd Units
  ansible.builtin.systemd:
    daemon-reload: true
  become: true

- name: Disable legacy Shiftmon service
  ansible.builtin.systemd:
    name: shift-mon.service
    enabled: false
    masked: true
    state: stopped
  become: true
  notify:
    - Stop Containers
    - Ensure permissions on shiftmon files

- name: Trigger Migration handlers
  ansible.builtin.debug:
    msg: "Trigger migration handlers"
  changed_when: true
  notify:
    - Stop Containers
    - Ensure permissions on shiftmon files

- name: Flush Handlers
  meta: flush_handlers

- name: Ensure Containers are Running and Updated
  community.docker.docker_compose_v2:
    project_src: /opt/shift-mon
    recreate: always
    pull: always
    state: present
  become: true
