- name: Create Victoriametrics directory
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    mode: '770'
    setype: container_file_t
  become: true
  with_items:
    - /opt/shift-mon/
    - /opt/shift-mon/victoriametrics
    - /opt/shift-mon/victoriametrics-storage

- name: Add Victoriametrics config to telegraf
  ansible.builtin.copy:
    src: victoriametrics-docker.conf
    dest: /etc/telegraf/telegraf.d/victoriametrics-docker.conf
  become: true
  notify: Restart Telegraf
