- name: Create Shift-mon folder
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: telegraf
    mode: '770'
    setype: container_file_t
  become: true
  with_items:
    - /opt/shift-mon

- name: Create Victoriametrics directory
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    mode: '770'
    setype: container_file_t
  become: true
  with_items:
    - /opt/shift-mon/victoriametrics
    - /opt/shift-mon/victoriametrics-storage
    - /opt/shift-mon/vmalert/rules
    - /opt/shift-mon/vmalert/templates
    - /opt/shift-mon/vmauth
    - /opt/shift-mon/alertmanager/data
    - /opt/shift-mon/alertmanager/config/templates

- name: Upload Scrape Config
  ansible.builtin.template:
    src: scrape-config.yml
    dest: /opt/shift-mon/victoriametrics/scrape-config.yml
    mode: '770'
    setype: container_file_t
  become: true

- name: Add VMAuth Template
  ansible.builtin.template:
    src: auth-config.yml
    dest: /opt/shift-mon/vmauth/auth-config.yml
    mode: '770'
    setype: container_file_t
  become: true

- name: Upload Shiftmon rules
  ansible.builtin.template:
    src: "shiftmon-alerts.yml"
    dest: "/opt/shift-mon/vmalert/rules/shiftmon.yml"
  become: true

- name: Upload user provisioned rules
  ansible.builtin.copy:
    src: "{{ item.value }}"
    dest: "/opt/shift-mon/vmalert/rules"
  become: true
  when: victoria.rule_files is defined
  with_items: "{{victoria.rule_files | dict2items }}"

- name: Upload alertmanager config
  ansible.builtin.template:
    src: "alertmanager.yml"
    dest: "/opt/shift-mon/alertmanager/config/alertmanager.yml"
    mode: '770'
    setype: container_file_t
    force: true
  become: true
