- name: download victoriametrics
  get_url: 
    url: 'https://github.com/VictoriaMetrics/VictoriaMetrics/releases/download/v{{ version }}/victoria-metrics-amd64-v{{ version }}.tar.gz'
    dest: '/tmp/victoriametrics-{{ version }}.tar.gz'
  become: true

- name: create victoriametrics user
  user:
    name: victoriametrics
    state: present
    shell: /usr/sbin/nologin
  become: true

- name: create victoriametrics folder
  file:
   path: /opt/victoriametrics
   state: directory
   owner: victoriametrics
   group: victoriametrics
  become: true

- name: create victoriametrics storage folder
  file:
   path: /opt/victoriametrics-storage
   state: directory
   owner: victoriametrics
   group: victoriametrics
  become: true

- name: extract victoriametrics archive
  unarchive:
    src: '/tmp/victoriametrics-{{ version }}.tar.gz'
    dest: /opt/victoriametrics
    remote_src: true
  become: true

- name: create the service
  template:
    src: victoriametrics.service
    dest: /etc/systemd/system/victoriametrics.service
  become: true

- name: Reload systemd units
  systemd:
    daemon-reload: true
  become: true

- name: start and enable the service
  systemd:
    name: victoriametrics
    enabled: true
    state: restarted
  become: true