- name: Create victoriametrics directory
  file:
    path: '{{ item }}'
    state: directory
    mode: '770'
    setype: container_file_t
  become: true
  with_items:
    - /opt/shift-mon/
    - /opt/shift-mon/victoriametrics
    - /opt/shift-mon/victoriametrics-storage

- name: add  victoriametrics config to telegraf
  copy:
    src: victoriametrics-docker.conf
    dest: /etc/telegraf/telegraf.d/victoriametrics-docker.conf
  become: true

- name: restart telegraf
  systemd:
    name: telegraf
    state: restarted
    enabled: true
  become: true
