- name: download victoriametrics
  get_url: 
    url: 'https://github.com/VictoriaMetrics/VictoriaMetrics/releases/download/v{{ version }}/victoria-metrics-amd64-v{{ version }}.tar.gz'
    dest: '/tmp/victoriametrics-{{ version }}.tar.gz'
  become: true

- name: download vm-auth
  get_url:
    url: 'https://github.com/VictoriaMetrics/VictoriaMetrics/releases/download/v{{ version }}/vmutils-amd64-v{{ version }}.tar.gz'
    dest: '/tmp/vm-utils-{{ version }}.tar.gz'
- name: create victoriametrics user
  user:
    name: victoriametrics
    state: present
    shell: /usr/sbin/nologin
  become: true

- name: create victoriametrics folder
  file:
   path: /opt/victoriametrics
   state: directory
   owner: victoriametrics
   group: victoriametrics
  become: true

- name: create victoriametrics storage folder
  file:
   path: /opt/victoriametrics-storage
   state: directory
   owner: victoriametrics
   group: victoriametrics
  become: true

- name: extract victoriametrics archive
  unarchive:
    src: '/tmp/victoriametrics-{{ version }}.tar.gz'
    dest: /opt/victoriametrics
    remote_src: true
  become: true

- name: extract vm-utils
  unarchive: 
    src: '/tmp/vm-utils-{{ version }}.tar.gz'
    dest: /opt/victoriametrics
    remote_src: true
  become: true

- name: generate vm-auth config
  template:
    src: auth-config.yml
    dest: /opt/victoriametrics/auth-config.yml
  become: true

- name: create service files
  template:
    src: '{{ item}}.service'
    dest: /etc/systemd/system/{{ item}}.service
  become: true
  with_items: '{{ services }}'

- name: Reload systemd units
  systemd:
    daemon-reload: true
  become: true

- name: start and enable services
  systemd:
    name: '{{ item }}'
    enabled: true
    state: restarted
  become: true
  with_items: '{{ services }}'