- name: Create victoriametrics directory
  file:
    path: '{{ item }}'
    state: directory
    mode: '777'
    setype: container_var_lib_t
  become: true
  with_items:
    - /opt/shift-mon/
    - /opt/shift-mon/victoriametrics
    - /opt/shift-mon/victoriametrics-storage

- name: generate vm-auth config
  template:
    src: auth-config.yml
    dest: /opt/shift-mon/victoriametrics/auth-config.yml
  become: true