- name: Create Victoriametrics directory
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    mode: '770'
    setype: container_file_t
  become: true
  with_items:
    - /opt/shift-mon/
    - /opt/shift-mon/victoriametrics
    - /opt/shift-mon/victoriametrics-storage
    - /opt/shift-mon/vmalert/rules
