providers:
  file:
    #filename: /etc/traefik/traefik.yml
    directory: /etc/traefik/traefik.d
serversTransport:
  insecureSkipVerify: true
tls:
  certificates:
{% if grafana.cert_path is defined and grafana.key_path is defined %}
    - certfile: /etc/traefik/certs/grafana.crt
      keyfile: /etc/traefik/certs/grafana.key
{% endif %}
{% if victoria.cert_path is defined and victoria.key_path is defined %}
    - certfile: /etc/traefik/certs/victoria.crt
      keyfile: /etc/traefik/certs/victoria.key
{% endif %}
{% if loki.cert_path is defined and loki.key_path is defined %}
    - certfile: /etc/traefik/certs/loki.crt
      keyfile: /etc/traefik/certs/loki.key
{% endif %}
{% if victorialogs.cert_path is defined and victorialogs.key_path is defined %}
    - certfile: /etc/traefik/certs/victorialogs.crt
      keyfile: /etc/traefik/certs/victorialogs.key
{% endif %}
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
ping: {}
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
  websecure:
    address: ":443"
    http2:
  metrics:
    address: ":8082"
certificatesResolvers:
  dynamicResolver:
    acme:
      storage: /etc/traefik/acme.json
{% if dns.provider is not defined %}
      httpChallenge:
        entryPoint: web
{% if acme_url is defined %}
      caServer: '{{ acme_url }}'
{% endif %}
      email: '{{ tls.email }}'
{% else %}
      dnsChallenge:
        provider: '{{ dns.provider }}'
        delayBeforeCheck: 0
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
{% endif %}
accessLog:
  format: json
  filters:
    statusCodes:
      - "400-499"
      - "500-599"
metrics:
  prometheus:
    entrypoint: metrics
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0
    addRoutersLabels: true
    addServicesLabels: true
