providers:
  file:
    filename: /etc/traefik/traefik.yml
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
  websecure:
    address: ":443"
    http2:
certificatesResolvers:
  shiftResolver:
    acme:
      storage: /etc/traefik/acme.json
{% if tls.dns_provider is not defined %}
      httpChallenge:
      email: '{{ tls.email }}'
        # used during the challenge
        entryPoint: web
{% else %}
      dnsChallenge:
        provider: '{{ tls.dns_provider }}'
        delayBeforeCheck: 0
{% endif %}
api:
  dashboard: true
  insecure: true
  debug: true
log:
  filePath: '/etc/traefik/traefik.log'
  level: DEBUG
metrics:
  influxDB:
    address: victoriametrics:8428
    protocol: http
    database: linux
    addRoutersLabels: true
    addServicesLabels: true
http:
  middlewares:
    basic-auth:
      basicAuth:
        usersFile: "/etc/traefik/htpasswd"
  routers:
    grafana:
      rule: Host(`{{ grafana.domain }}`)
      tls:
        certResolver: shiftResolver
      service: grafana
      entryPoints:
        - websecure
    loki:
      rule: Host(`{{ loki.domain }}`)
      tls:
        certResolver: shiftResolver
      service: loki
      middlewares:
        - basic-auth
      entryPoints:
        - websecure
    victoriametrics:
      rule: Host(`{{ victoria.domain }}`)
      tls:
        certResolver: shiftResolver
      service: victoriametrics
      middlewares:
        - basic-auth
      entryPoints:
        - websecure
  services:
    grafana:
      loadBalancer:
        servers:
          - url: http://grafana:3000
    loki:
      loadBalancer:
        servers:
          - url: http://loki:3100
    victoriametrics:
      loadBalancer:
        servers:
          - url: http://victoriametrics:8428