- name: install packages
  block:
    - name: install packages for configuring traefik
      package:
        name: python3-passlib
        state: latest
      become: true
  rescue:
    - name: install pip
      package:
        name: python3-pip
        state: latest
      become: true

    - name: install packages for configuring traefik from pip
      pip:
        name: passlib
        state: latest
      become: true
   

- name: create traefik folders
  file:
    path:  '{{ item }}'
    state: directory
    mode: '777'
    setype: container_file_t
  become: true
  with_items:
    - '/opt/shift-mon/traefik'
    - '/opt/shift-mon/traefik/certs'
    - '/opt/shift-mon'

- name: generate http usernames and passwords
  htpasswd:
    path: /opt/shift-mon/traefik/htpasswd
    name: '{{ item.key }}'
    password: '{{ item.value }}'
  become: true
  no_log: true
  with_dict: '{{ users }}'

- name: copy traefik config
  template:
    src: traefik.yml
    dest: /opt/shift-mon/traefik/traefik.yml
    mode: '770'
  become: true

- name: copy grafana cert
  copy:
    src: '{{ grafana.cert_path }}'
    dest: '/opt/shift-mon/traefik/certs/grafana.crt'
  when: grafana.cert_path is defined

- name: copy grafana key
  copy:
    src: '{{ grafana.key_path }}'
    dest: '/opt/shift-mon/traefik/certs/grafana.key'
  when: grafana.key_path is defined

- name: copy victoriametrics cert
  copy:
    src: '{{ victoria.cert_path }}'
    dest: '/opt/shift-mon/traefik/certs/victoria.crt'
  when: victoria.cert_path is defined

- name: copy victoriametrics key
  copy:
    src: '{{ victoria.key_path }}'
    dest: '/opt/shift-mon/traefik/certs/victoria.key'
  when: victoria.key_path is defined

- name: copy loki cert
  copy:
    src: '{{ loki.cert_path }}'
    dest: '/opt/shift-mon/traefik/certs/loki.crt'
  when: loki.cert_path is defined

- name: copy loki key
  copy:
    src: '{{ loki.key_path }}'
    dest: '/opt/shift-mon/traefik/certs/loki.key'
  when: loki.key_path is defined

- name: copy uptime-kuma cert
  copy:
    src: '{{ uptimekuma.cert_path }}'
    dest: '/opt/shift-mon/traefik/certs/uptime-kuma.crt'
  when: loki.cert_path is defined

- name: copy uptime-kuma key
  copy:
    src: '{{ uptimekuma.key_path }}'
    dest: '/opt/shift-mon/traefik/certs/uptime-kuma.key'
  when: loki.key_path is defined

- name: add Traefik log config to telegraf
  copy:
    src: telegraf-traefik.conf
    dest: /etc/telegraf/telegraf.d/traefik.conf
  become: true

- name: add logrotate config
  copy:
    src: logrotate-traefik.conf
    dest: /etc/logrotate.d/traefik.conf
  become: true
  notify: restart telegraf