- name: Create Victorialogs Folders
  ansible.builtin.file:
    path: /opt/shift-mon/victorialogs
    state: directory
    owner: shiftmon
    group: shiftmon
    mode: '770'
    setype: container_file_t
  become: true
