- name: add GPG key for repo on Debian based systems
  apt_key:
    url: https://repos.influxdata.com/influxdb.key
    state: present
  become: true
  when : ansible_facts['os_family'] == "Debian"

- name: add repo for Debian based systems
  apt_repository:
    repo: "deb https://repos.influxdata.com/ubuntu focal stable"
    state: present
    update_cache: no
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: add repo for Redhat based systems
  yum_repository:
    name: influxdb
    description: influx db software
    baseurl: https://repos.influxdata.com/centos/{{ ansible_distribution_major_version }}/x86_64/stable/
    gpgcheck: yes
    gpgkey: https://repos.influxdata.com/influxdb.key
    state: present
  become: true
  when: ansible_facts['os_family'] == "RedHat" and ansible_distribution != "Fedora"

- name: add repo for Fedora
  yum_repository:
    name: influxdb
    description: influx db software
    baseurl: https://repos.influxdata.com/centos/9/x86_64/stable/
    gpgcheck: yes
    gpgkey: https://repos.influxdata.com/influxdb.key
    state: present
  become: true
  when: ansible_distribution == "Fedora"

- name: install Telegraf on Debian based systems
  apt:
    name: telegraf
    update_cache: true
    state: present
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: install Telegraf on Redhat based systems
  dnf:
    name: telegraf
    state: present
  become: true
  when: ansible_facts['os_family'] == "RedHat"

- name: add telegraf defaults file
  template:
    src: telegraf-defaults.j2
    dest: /etc/default/telegraf
  become: true

- name: Download telegraf config
  get_url:
    url: https://gitlab.com/shiftsystems/shift-rmm/-/raw/master/telegraf-configs/linux/telegraf.conf
    dest: /etc/telegraf/telegraf.conf
  become: true

- name: Gather Systemd units
  service_facts:

- name: Add Meshcentral Config if Meshcentral is installed
  get_url:
    url: https://gitlab.com/shiftsystems/shift-rmm/-/raw/master/telegraf-configs/linux/mesh-central.conf
    dest: /etc/telegraf/telegraf.d/mesh-central.conf
  become: true
  when: "'meshagent.service' in ansible_facts.services"

- name: Add Crowdsec Config if Crowdsec is installed
  get_url:
    url: https://gitlab.com/shiftsystems/shift-rmm/-/raw/master/telegraf-configs/linux/crowdsec.conf
    dest: /etc/telegraf/telegraf.d/crowdsec.conf
  become: true
  when: "'crowdsec.service' in ansible_facts.services"

- name: Add Adguard Config if Adguard is installed
  get_url:
    url: https://gitlab.com/shiftsystems/shift-rmm/-/raw/master/telegraf-configs/linux/adgaurd.conf
    dest: /etc/telegraf/telegraf.d/adgaurd.conf
  become: true
  when: "'AdGuardHome.service' in ansible_facts.services"

- name: Add telegraf to the nginx group on RedHat based systems
  user: 
    name: telegraf
    groups: root
    append: true
  become: true
  when: "ansible_facts['os_family'] == 'RedHat' and 'nginx.service' in ansible_facts.services"

- name: Add telegraf to the nginx group on Debian based systems
  user:
    name: telegraf
    groups: adm
    append: true
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: Add Nginx config When nginx is installed
  get_url:
    url: https://gitlab.com/shiftsystems/shift-rmm/-/raw/master/telegraf-configs/linux/nginx.conf
    dest: /etc/telegraf/telegraf.d/nginx.conf
  become: true
  when: "'nginx.service' in ansible_facts.services"

- name: Add telegraf to docker group when docker is installed
  user:
    name: telegraf
    groups: docker
    append: true
  become: true
  when: "'docker.service' in ansible_facts.services"

- name: Deploy Docker config When Docker is installed
  get_url:
    url: https://gitlab.com/shiftsystems/shift-rmm/-/raw/master/telegraf-configs/linux/docker.conf
    dest: /etc/telegraf/telegraf.d/docker.conf
  become: true
  when: "'docker.service' in ansible_facts.services"

- name: MySQL config when MySQL is installed
  get_url:
    url: https://gitlab.com/shiftsystems/shift-rmm/-/raw/master/telegraf-configs/linux/mysql.conf
    dest: /etc/telegraf/telegraf.d/mysql.conf
  become: true
  when: "'mysqld.service' or 'mysql.service' in ansible_facts.services"

- name: Deploy Loki config when Loki is installed
  get_url:
    url: https://gitlab.com/shiftsystems/shift-rmm/-/raw/master/telegraf-configs/linux/loki.conf
    dest: /etc/telegraf/telegraf.d/loki.conf
  become: true
  when: "'loki.service' in ansible_facts.services"

- name: Deploy Victoriametrics config when Victoriametrics is installed
  get_url:
    url: https://gitlab.com/shiftsystems/shift-rmm/-/raw/master/telegraf-configs/linux/victoriametrics.conf
    dest: /etc/telegraf/telegraf.d/victoriametrics.conf
  become: true
  when: "'victoriametrics.service' in ansible_facts.services"

- name: Add telegraf to the MySQL group on Debian based systems
  file:
    path: '/tmp/stubby'
    state: absent
  when: "'mysql.service' in ansible_facts.services"

- name: install rsyslog
  package:
    name: rsyslog
    state: latest
  become: true
  when: syslog is defined and syslog

- name: place rsyslog config is installed when syslog is enabled
  get_url:
    url: https://gitlab.com/shiftsystems/shift-rmm/-/raw/master/telegraf-configs/linux/50-telegraf.conf
    dest: /etc/rsyslog.d/50-telegraf.conf
  become: true
  when: syslog is defined and syslog

- name: restart  and enable rsyslog service
  systemd:
    name: rsyslog
    state: restarted
    enabled: true
  become: true
  when: syslog is defined and syslog

- name: add telegraf config for syslog
  get_url:
    url: https://gitlab.com/shiftsystems/shift-rmm/-/raw/master/telegraf-configs/linux/syslog.conf
    dest: /etc/telegraf/telegraf.d/syslog.conf
  become: true
  when: syslog is defined and syslog

- name: add telegraf config for remote syslog
  get_url:
    url: https://gitlab.com/shiftsystems/shift-rmm/-/raw/master/telegraf-configs/linux/remote-syslog.conf
    dest: /etc/telegraf/telegraf.d/remote-syslog.conf
  become: true
  when: remote_syslog is defined and remote_syslog

- name: Allow remote syslog traffic on UFW
  community.general.ufw:
    rule: allow
    port: 6666
    proto: udp
  become: true
  when: "remote_syslog is defined and remote_syslog and 'ufw.service' in ansible_facts.services"

- name: Allow remote syslog traffic on firewalld
  ansible.posix.firewalld:
    state: enabled
    port: 6666/udp
  become: true
  when: "remote_syslog is defined and remote_syslog and 'firewalld.service' in ansible_facts.services"

- name: create telegraf override directory
  file:
    name: /etc/systemd/system/telegraf.service.d
    state: directory
  become: true

- name: configure telegraf to run as root
  copy:
    src: override.conf
    dest: /etc/systemd/system/telegraf.service.d/override.conf
  become: true

- name: Start and Enable Telegraf
  systemd:
    name: telegraf
    enabled: true
    state: restarted
  become: true
