- name: add GPG key for repo on Debian based systems
  apt_key:
    url: https://repos.influxdata.com/influxdb.key
    state: present
  become: true
  when : ansible_facts['os_family'] == "Debian"

- name: add repo for Debian based systems
  apt_repository:
    repo: "deb https://repos.influxdata.com/ubuntu bionic stable"
    state: present
    update_cache: no
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: add repo for Redhat based systems
  yum_repository:
    name: influxdb
    description: influx db software
    baseurl: https://repos.influxdata.com/centos/8/x86_64/stable/
    gpgcheck: yes
    gpgkey: https://repos.influxdata.com/influxdb.key
    state: present
  become: true
  when: ansible_facts['os_family'] == "RedHat"

- name: install Telegraf on Debian based systems
  apt:
    name: telegraf
    update_cache: true
    state: present
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: install Telegraf on Redhat based systems
  dnf:
    name: telegraf
    state: present
  become: true
  when: ansible_facts['os_family'] == "RedHat"

- name: add telegraf defaults file
  template:
    src: telegraf-defaults.j2
    dest: /etc/default/telegraf
  become: true

- name: Download telegraf config
  get_url:
    url: https://gitlab.com/shiftsystems/shift-rmm/-/raw/master/telegraf-configs/linux/telegraf.conf
    dest: /etc/telegraf/telegraf.conf
  become: true

- name: Download telegraf new outputs config
  get_url:
    url: https://gitlab.com/shiftsystems/shift-rmm/-/raw/master/telegraf-configs/linux/new-outputs.conf
    dest: /etc/telegraf/telegraf.d/new-outputs.conf
  become: true

- name: Gather Systemd units
  service_facts:

- name: Add Meshcentral Config if Meshcentral is installed
  get_url:
    url: https://gitlab.com/shiftsystems/shift-rmm/-/raw/master/telegraf-configs/linux/mesh-central.conf
    dest: /etc/telegraf/telegraf.d/mesh-central.conf
  become: true
  when: "'meshagent.service' in ansible_facts.services"

- name: Add Crowdsec Config if Crowdsec is installed
  get_url:
    url: https://gitlab.com/shiftsystems/shift-rmm/-/raw/master/telegraf-configs/linux/crowdsec.conf
    dest: /etc/telegraf/telegraf.d/crowdsec.conf
  become: true
  when: "'crowdsec.service' in ansible_facts.services"

- name: Add Nginx config When nginx is installed
  get_url:
    url: https://gitlab.com/shiftsystems/shift-rmm/-/raw/master/telegraf-configs/linux/nginx.conf
    dest: /etc/telegraf/telegraf.d/nginx.conf
  become: true
  when: "'nginx.service' in ansible_facts.services"

- name: Start and Enable Telegraf
  systemd:
    name: telegraf
    enabled: true
    state: restarted
  become: true
