- name: Make sure GPG is installed
  apt:
    name: gpg
    state: present
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: add GPG key for repo on Debian based systems
  apt_key:
    url: https://repos.influxdata.com/influxdata-archive_compat.key
    state: present
  become: true
  when : ansible_facts['os_family'] == "Debian"

- name: add repo for Debian based systems
  apt_repository:
    repo: "deb https://repos.influxdata.com/{{ ansible_distribution|lower }} {{ ansible_distribution_release|lower }} stable"
    state: present
    update_cache: no
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: add repo for Redhat based systems
  yum_repository:
    name: influxdb
    description: influx db software
    baseurl: https://repos.influxdata.com/centos/{{ ansible_distribution_major_version }}/x86_64/stable/
    gpgcheck: yes
    gpgkey: https://repos.influxdata.com/influxdata-archive_compat.key
    state: present
  become: true
  when: ansible_facts['os_family'] == "RedHat" and ansible_distribution != "Fedora"

- name: add repo for Fedora
  yum_repository:
    name: influxdb
    description: influx db software
    baseurl: https://repos.influxdata.com/centos/9/x86_64/stable/
    gpgcheck: no
    gpgkey: https://repos.influxdata.com/influxdata-archive_compat.key
    state: present
  become: true
  when: ansible_distribution == "Fedora"

- name: install Telegraf on Debian based systems
  apt:
    name: telegraf
    update_cache: true
    state: latest
  become: true
  when: ansible_facts['os_family'] == "Debian"
  notify: restart telegraf

- name: install Telegraf on Redhat based systems
  dnf:
    name: telegraf
    state: latest
  become: true
  when: ansible_facts['os_family'] == "RedHat"
  notify: restart telegraf

- name: add telegraf defaults file
  template:
    src: telegraf-defaults.j2
    dest: /etc/default/telegraf
  become: true
  notify: restart telegraf

- name: Download telegraf config
  copy:
    src: "{{ playbook_dir }}/telegraf-configs/linux/telegraf.conf"
    dest: /etc/telegraf/telegraf.conf
  become: true
  notify: restart telegraf

- name: Gather Systemd units
  service_facts:

- name: Add Meshcentral Config if Meshcentral is installed
  copy:
    src: "{{ playbook_dir }}/telegraf-configs/linux/mesh-central.conf"
    dest: /etc/telegraf/telegraf.d/mesh-central.conf
  become: true
  when: "'meshagent.service' in ansible_facts.services"
  notify: restart telegraf

- name: Add Crowdsec Config if Crowdsec is installed
  copy:
    src: "{{ playbook_dir }}/telegraf-configs/linux/crowdsec.conf"
    dest: /etc/telegraf/telegraf.d/crowdsec.conf
  become: true
  when: "'crowdsec.service' in ansible_facts.services"
  notify: restart telegraf

- name: Add Adguard Config if Adguard is installed
  copy:
    src: "{{ playbook_dir }}/telegraf-configs/linux/adgaurd.conf"
    dest: /etc/telegraf/telegraf.d/adgaurd.conf
  become: true
  when: "'AdGuardHome.service' in ansible_facts.services"
  notify: restart telegraf

- name: Add telegraf to the nginx group on RedHat based systems
  user: 
    name: telegraf
    groups: root
    append: true
  become: true
  when: "ansible_facts['os_family'] == 'RedHat' and 'nginx.service' in ansible_facts.services"
  notify: restart telegraf

- name: Add Caddy Config if Caddy is installed
  copy:
    src: "{{ playbook_dir }}/telegraf-configs/linux/caddy.conf"
    dest: /etc/telegraf/telegraf.d/caddy.conf
  become: true
  when: "'caddy.service' in ansible_facts.services"
  notify: restart telegraf

- name: Add telegraf to the nginx group on Debian based systems
  user:
    name: telegraf
    groups: adm
    append: true
  become: true
  when: ansible_facts['os_family'] == "Debian"
  notify: restart telegraf

- name: Add Nginx config When nginx is installed
  copy:
    src: "{{ playbook_dir }}/telegraf-configs/linux/nginx.conf"
    dest: /etc/telegraf/telegraf.d/nginx.conf
  become: true
  when: "'nginx.service' in ansible_facts.services"
  notify: restart telegraf

- name: Add telegraf to docker group when docker is installed
  user:
    name: telegraf
    groups: docker
    append: true
  become: true
  when: "'docker.service' in ansible_facts.services"
  notify: restart telegraf

- name: Deploy Docker config When Docker is installed
  copy:
    src: "{{ playbook_dir }}/telegraf-configs/linux/docker.conf"
    dest: /etc/telegraf/telegraf.d/docker.conf
  become: true
  when: "'docker.service' in ansible_facts.services"
  notify: restart telegraf

- name: Deploy Podman config When Podman service is present
  copy:
    src: "{{ playbook_dir }}/telegraf-configs/linux/podman.conf"
    dest: /etc/telegraf/telegraf.d/podman.conf
  become: true
  when: "'podman.service' in ansible_facts.services"
  notify: restart telegraf

- name: Deploy Podman config When Libvirt service is present
  copy:
    src: "{{ playbook_dir }}/telegraf-configs/linux/libvirt.conf"
    dest: /etc/telegraf/telegraf.d/libvirt.conf
  become: true
  when: "'libvirtd.service' in ansible_facts.services"
  notify: restart telegraf

- name: MySQL config when MySQL is installed
  copy:
    src: "{{ playbook_dir }}/telegraf-configs/linux/mysql.conf"
    dest: /etc/telegraf/telegraf.d/mysql.conf
  become: true
  when: "'mysqld.service' or 'mysql.service' in ansible_facts.services"
  notify: restart telegraf

- name: Deploy Loki config when Loki is installed
  copy:
    src: "{{ playbook_dir }}/telegraf-configs/linux/loki.conf"
    dest: /etc/telegraf/telegraf.d/loki.conf
  become: true
  when: "'loki.service' in ansible_facts.services"
  notify: restart telegraf

- name: Deploy Victoriametrics config when Victoriametrics is installed
  copy:
    src: "{{ playbook_dir }}/telegraf-configs/linux/victoriametrics.conf"
    dest: /etc/telegraf/telegraf.d/victoriametrics.conf
  become: true
  when: "'victoriametrics.service' in ansible_facts.services"
  notify: restart telegraf

- name: Add telegraf to the MySQL group on Debian based systems
  file:
    path: '/tmp/stubby'
    state: absent
  when: "'mysql.service' in ansible_facts.services"
  notify: restart telegraf

- name: install rsyslog
  package:
    name: rsyslog
    state: latest
  become: true
  when: syslog is defined and syslog == "rsyslog"
  notify: restart syslog

- name: place rsyslog config is installed when syslog is enabled
  copy:
    src: "{{ playbook_dir }}/telegraf-configs/linux/50-telegraf.conf"
    dest: /etc/rsyslog.d/50-telegraf.conf
  become: true
  when: syslog is defined and syslog == "rsyslog"
  notify: restart syslog

- name: start and enable rsyslog service
  systemd:
    name: rsyslog
    state: started
    enabled: true
  become: true
  when: syslog is defined and syslog == "rsyslog"

- name: add telegraf config for syslog
  copy:
    src: "{{ playbook_dir }}/telegraf-configs/linux/syslog.conf"
    dest: /etc/telegraf/telegraf.d/syslog.conf
  become: true
  when: syslog is defined 
  notify: restart telegraf

- name: add telegraf config for remote syslog
  copy:
    src: "{{ playbook_dir }}/telegraf-configs/linux/remote-syslog.conf"
    dest: /etc/telegraf/telegraf.d/remote-syslog.conf
  become: true
  when: remote_syslog is defined and remote_syslog
  notify: restart telegraf

- name: Allow remote syslog traffic on UFW
  community.general.ufw:
    rule: allow
    port: 6666
    proto: udp
  become: true
  when: "remote_syslog is defined and remote_syslog and 'ufw.service' in ansible_facts.services"

- name: Allow remote syslog traffic on firewalld
  ansible.posix.firewalld:
    state: enabled
    port: 6666/udp
  become: true
  when: "remote_syslog is defined and remote_syslog and 'firewalld.service' in ansible_facts.services"

- name: create telegraf override directory
  file:
    name: /etc/systemd/system/telegraf.service.d
    state: directory
  become: true
  when: telegraf_root is defined and telegraf_root

- name: configure telegraf to run as root
  copy:
    src: override.conf
    dest: /etc/systemd/system/telegraf.service.d/override.conf
  become: true
  when: telegraf_root is defined and telegraf_root
  notify: restart telegraf

- name: Start and Enable Telegraf
  systemd:
    name: telegraf
    enabled: true
    state: started
  become: true
